AlexsLemonade/refinebio

- workers/data_refinery_workers/processors/array_express.py
Super simple change, I just forgot to change this when I last changed this file's code.
> Removes a now out of date doc string.

- README.md
This still has our pilot stage funding sources. Making it a bit more current.
> funding sources -> note current ones

- common.sh
This was part of #81, but got left behind.
> I forgot to add this file in my last PR :(

- .circleci/config.yml
- .gitignore
- README.md
- common.sh
- common/install_db_docker.sh
- common/make_migrations.sh
- common/run_tests.sh
- foreman/run_tests.sh
- run_all_tests.sh
- run_postgres.sh
- run_psql_shell.sh
- workers/run_tests.sh
This dockerizes Postgres, updates the README and changes the CI config. Since nomad isn't Dockerized yet either, the build still doesn't work.
> Dockerize Postgres

- .git-crypt/keys/default/0/65EC6E219A655CA8CAC3096890D90E5F0A053C53.gpg
New collaborators:
0A053C53 Rich Jones <miserlou+alexs@gmail.com>
@Miserlou if you can checkout this branch, run `git-crypt unlock`, and then view an encrypted file such as `terraform/terraform.tfstate` then you'll know this worked and you can approve it.
> Add 1 git-crypt collaborator

- issue_template.md
I wanted to propose a template for issues with a checklist to help us create issues that multiple members of the team can more easily select and work on.
> propose new template for issues

- pull_request_template.md
Sourced from https://github.com/cognoma/frontend/edit/master/PULL_REQUEST_TEMPLATE.md
No issue has been created.
We do not currently have a pull request template. With the changes in #120 we have an issue template. This attempts to add a little bit of structure to PRs to help aid in review. This also means we won't have to type headers, and outside contributors can use the checkboxes to help us understand the types of changes and how tested they are.
_Put an `x` in the boxes that apply_
Unfortunately GitHub issue templates are only on the GitHub platform so I have not been able to test locally.
> Create a Pull Request Template

- README.md
NA
Changed a few wordings and corrected typos in `README.md`.
_Put an `x` in the boxes that apply_
> README Revised

- infrastructure/instances.tf
- infrastructure/logging.tf
- infrastructure/networking.tf
- infrastructure/nomad-configuration/nomad-client-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/nomad-server-instance-user-data.tpl.sh
- infrastructure/variables.tf
- workers/downloader.nomad.tpl
- workers/processor.nomad.tpl
Related: https://github.com/AlexsLemonade/refinebio/issues/146
Simple change: install the logger, configure and run it.
_Put an `x` in the boxes that apply_
> Installs, configures and executes AWS Log agent, passes vars to script

- README.md
- infrastructure/instances.tf
- infrastructure/logging.tf
- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
- infrastructure/permissions.tf
- infrastructure/users.tf
- infrastructure/variables.tf
- workers/data_refinery_workers/processors/array_express.py
https://github.com/AlexsLemonade/refinebio/issues/174
Adds autoscaling based on a new custom CW Metric based on the Nomad queue length. Also parameterizes some of the inputs. 
Needs a proper crunch test but I'm running the Neuroblastoma crunch already until tomorrow at least. I'm pretty sure this works though.
> Adds CloudWatch Metric Based Autoscaling

- api/data_refinery_api/serializers.py
* fixed a typo
* doing `created_at` queries on jobs works now without errors
> change "archve" to "archive"

- .circleci/config.yml
- .circleci/run_terraform.sh
- infrastructure/deploy.sh
#181 
Terraform was not completely working due to AWS resource conflictions. After cleaning up all unnecessary resources from AWS web console and fixing a couple of issues in `deploy.sh`, it is working now in CircleCI instance now.
I changed `config.yml` so that CircleCI will trigger `run_terraform.sh` in every commit. Eventually the terraform commands don't report any errors. 
> Terraform Fix

- .github/ISSUE_TEMPLATE.md
Re-works the issue template to make the checklist an actual checklist. It also re-orders context/problem.
#191 
This makes changes as described in #191. We retain the checklist but it becomes an actual checklist. For within-group tickets, this is probably less necessary, but making the checklist can make it clear to outside contributors that we expect these thinsg to be filled out.
N/A
> This closes #191 w/ checklist changes.

- common/data_refinery_common/models/__init__.py
- common/data_refinery_common/models/models.py
- foreman/data_refinery_foreman/surveyor/array_express.py
- foreman/data_refinery_foreman/surveyor/sra.py
https://github.com/AlexsLemonade/refinebio/issues/241
Adds a new ExperimentOrganismAssociation model and hooks it up in the surveyor. We need this to use an Organism filter efficiently. 
Uses existing tests
> Adds and connects ExperimentOrganismAssociation

- api/data_refinery_api/urls.py
Just documenting our added `/search` endpoing
`/search` shows up on API Root and takes you to appropriate route
> added search to the api root page

- run_postgres.sh
- workers/Dockerfile.tests
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/test_salmon.py
- workers/run_tests.sh
#83 and #244
This PR adds salmontools data analysis and two test cases, one for double reads, the other for single reads.
Unit tests were added and run to confirm the results.
> New feature: SalmonTools (and corresponding tests) in Salmon pipeline

- workers/data_refinery_workers/processors/array_express.py
- workers/data_refinery_workers/processors/test_array_express.py
- workers/run_tests.sh
https://github.com/AlexsLemonade/refinebio/issues/64
Small change to avoid failure when there is no BA package. I think this works as intended.
New test for sample GSM45588.PCL added
> Add Support for Non-BrainArray CELs, with Test

- foreman/data_refinery_foreman/surveyor/management/commands/survey_all.py
- format_nomad_with_env.sh
n/a
The job spec formatter improperly formats the awslogs driver specification, causing deployed job as they can't find the untemplated log stream.
Tested locally
> Fix awslogs Region, Group and Stream in Nomad Job Specs

- foreman/data_refinery_foreman/surveyor/management/commands/survey_all.py
- format_nomad_with_env.sh
Discussed here: https://github.com/AlexsLemonade/refinebio/pull/257
Trivial fix to a bug in survey_all lists that come from S3.
Run locally and in deployment
> Fixes S3:// URLs in `survey_all` Command

- api/data_refinery_api/tests.py
- foreman/data_refinery_foreman/surveyor/array_express.py
- foreman/data_refinery_foreman/surveyor/management/commands/survey_all.py
- foreman/data_refinery_foreman/surveyor/test_array_express.py
- format_nomad_with_env.sh
n/a
Analyzing the initial Zebrafish crunch results determined that the AE accession code detector is broken in some cases (failed to return a value). This PR adds a return value in all cases and adds a test case.
New test added for failing cases in ZF list.
> Fix AE Accession Detector

- LICENSE
N/A
Copyright used to be listed as the Greene Lab since that's where development started. Now it should also include Alex's since some lab members are employed there as well.
> note that recent development is copyright CCDL

- foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
- foreman/data_refinery_foreman/surveyor/transcriptome_index.py
- format_nomad_with_env.sh
n/a
Ensembl updated releases from 91 and 92. This broke indexing since we couldn't get the file any more, and we didn't notice because there's no test for it.
This bumps the version and adds a test so we know when it happens in the future.
New test added
> Bump Ensembl Version // Test for New Ensembl Versions

- api/serve.sh
- api/serve_production.sh
na
`serve.sh` is broken. Small fix.
> Fixes to serve scripts

- api/data_refinery_api/views.py
na
@Miserlou restricted the filter counts to the results in the query
* filter counts reflect what is expected from the query results
> count filters based on results of query

- common/data_refinery_common/models/models.py
- foreman/data_refinery_foreman/surveyor/array_express.py
- foreman/data_refinery_foreman/surveyor/geo.py
- foreman/data_refinery_foreman/surveyor/sra.py
Geo experiments had no organisms.
Association tables allowed duplicate rows.
This fixes both of those issues.
> Makes association tables unique, adds organisms to geo experiments.

- foreman/data_refinery_foreman/surveyor/sra.py
Super minor, but I didn't wanna leave this in `dev`.
> Fix a bad merge I noticed while dealing with new merge conflicts.

- api/data_refinery_api/views.py
- common/data_refinery_common/message_queue.py
- common/data_refinery_common/models/jobs.py
- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
- foreman/data_refinery_foreman/surveyor/external_source.py
- foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
- workers/data_refinery_workers/downloaders/transcriptome_index.py
- workers/data_refinery_workers/downloaders/utils.py
This will be necessary for redeploying
This makes the foreman relevant again!
Works locally.
> Kurtwheeler fix foreman

- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
* Filter samples by `accession_code`
* passing in a list of accession codes as a parameter to the `samples` endpoint will return a filtered list of samples by those accession codes
> add accession code filtering and tests

- workers/affymetrix_dependencies.R
#336 
Remove unnecessary packages from Affymetrix Docker image
Tested on my local desktop.
> Remove unnecessary R packages from affymetrix docker image

- README.md
- api/run_tests.sh
- common/run_tests.sh
- foreman/run_tests.sh
- format_nomad_with_env.sh
- infrastructure/deploy.sh
- prepare_image.sh
- run_all_tests.sh
- run_nomad.sh
- run_postgres.sh
- update_models.sh
- workers/run_tests.sh
N/A
I added more documentation on how to run individual tests rather than the full test suites. The tests now also make sure that Nomad and Docker are running before starting rather than failing silently afterwards. The help documentation in the test scripts was also rewritten in an explicit man pages-like format. I also added URLs to the dependencies in the README that were missing them before.
I reran all the scripts that I changed to make sure that they work exactly like the old ones when used correctly, and warn the user when used incorrectly.
> Improve scripts and documentation

- common/data_refinery_common/job_lookup.py
- foreman/data_refinery_foreman/surveyor/external_source.py
- workers/data_refinery_workers/downloaders/array_express.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/data_refinery_workers/processors/array_express.py
- workers/data_refinery_workers/processors/illumina.py
- workers/data_refinery_workers/processors/salmon.py
n/a
There were quite a few errors in the logs from the recent crunch that are pesky to debug because they don't provide enough filterable information to `awslogs`. This adds more information to the relevant log lines.
n/a
> More Useful Log Lines

- .circleci/run_terraform.sh
- .circleci/update_docker_img.sh
- infrastructure/networking.tf
N/A
In https://circleci.com/gh/AlexsLemonade/refinebio/3424 we got almost all the way through the deploy job but we ended up being in the wrong directory when checking the git branch.
I made these changes on the circleci instance and then ran the final `bash .circlceci/run_terraform.sh` command myself and it worked perfectly.
> Polish remaining deploy warts

- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio/issues/384
Searches more experiment fields.
New assertion added
> Adds more terms to search fields

- workers/data_refinery_workers/processors/agilent_twocolor.py
N/A
Tests are failing on `dev`: https://circleci.com/gh/AlexsLemonade/refinebio/3701?utm_campaign=build-failed&utm_medium=email&utm_source=notification
I think it's cause of this line https://github.com/AlexsLemonade/refinebio/pull/346/files#diff-7ad57c7a1d49ed9011056779c380b459R147 which references a model class which didn't get imported.
The unit tests should cover this pretty well since they're what discovered the issue in the first place.
> Adds an import which was left out.

- infrastructure/api-configuration/nginx_config.conf
https://github.com/AlexsLemonade/refinebio-frontend/issues/157
There is some weird behavior around really long URLs.
Sometimes, it 414s. Sometimes, it 404s. Sometimes, it 200s but without the querystring suffixed.
414:
https://api.staging.refine.bio/samples/?accession_codes=GSM2261538,GSM2261539,GSM2261540,GSM2261541,GSM2261542,GSM2261543,GSM2261544,GSM2261545,GSM2261546,GSM2261547,GSM2261548,GSM2261549,GSM2261550,GSM2261551,GSM2261552,GSM2261553,GSM2261554,GSM2261555,GSM2261556,GSM2261557,GSM2261558,GSM2261559,GSM2261560,GSM2261561,GSM2261562,GSM2261563,GSM2261564,GSM2261565,GSM2261566,GSM2261567,GSM2261568,GSM2261569,GSM2261570,GSM2261571,GSM2261572,GSM2261573,GSM2261574,GSM2261575,GSM2261576,GSM2261577,GSM2261578,GSM2261579,GSM2261580,GSM2261581,GSM2261582,GSM2261583,GSM2261584,GSM22615 …
> Hopefully Fix 414/404/200 Errors 

- api/data_refinery_api/serializers.py
Backend changes required to fix https://github.com/AlexsLemonade/refinebio-frontend/issues/124
Add the organisms and the technology to the DetailedExperimentSerializer so the frontend can use the values.
> Backend Changes for Frontend Issue 124

- .circleci/config.yml
- .circleci/slackpost.sh
https://github.com/AlexsLemonade/refinebio/issues/401
Small script call to poke Slack after deploys.
> Adds Slackbot Script to Deploy

- api/data_refinery_api/serializers.py
Fix the `DetailedExperimentSerializer` so it correctly serializes organisms.
I ran the API and confirmed that the organisms field was correct
> Fixed experiment serializer organisms field

- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/gene_convert.R
- workers/data_refinery_workers/processors/no_op.py
- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_smasher.py
n/a
R bug, Pandas Fail Tolerance, Split Upload and Notify into separate functions.
`¯\_(ツ)_/¯`
> Various Fixes - R bug, Pandas Fail Tolerance, Split Upload and Notify

- .circleci/config.yml
N/A
I made a typo that broke circle.
> I made a typo :(

- common/data_refinery_common/test_utils.py
- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/surveyor/array_express.py
- foreman/data_refinery_foreman/surveyor/geo.py
- infrastructure/permissions.tf
- workers/data_refinery_workers/processors/no_op.py
- workers/data_refinery_workers/processors/smasher.py
n/a
Fixes reported bug:
```
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging 2018-07-19 15:38:56,964 i-0cf6dcc12866b29c2/MainProcess data_refinery_workers.processors.utils ERROR [processor_job: 20809]: Unhandled exception caught while running processor function _prepare_files in pipeline
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging Traceback (most recent call last):
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging   File "/home/user/data_refinery_workers/processors/utils.py", line 212, in run_pipeline
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging     last_result = processor(last_result)
data-refinery-log-group-circleci-staging …
```
> Use UTF-8 Mode When Opening Foreign TSVs

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
> Add a second domain so we aren't limited to 5 let's encrypts a week.

- workers/data_refinery_workers/processors/agilent_twocolor.py
- workers/data_refinery_workers/processors/array_express.py
- workers/data_refinery_workers/processors/illumina.py
- workers/data_refinery_workers/processors/no_op.py
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/transcriptome_index.py
https://github.com/AlexsLemonade/refinebio/issues/428
Our processor jobs no longer fail...
I ran the training crunch with these changes.
> Comments out the code that breaks every one of our processors.

- .circleci/config.yml
- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/smasher.py
n/a
Only return Experiments with processed Samples via Search
New assertions.
> Adds and hopefully uses ProcessedPublicObjectsManager

- api/data_refinery_api/settings.py
- common/data_refinery_common/models/models.py
- common/data_refinery_common/settings.py
- foreman/data_refinery_foreman/settings.py
- foreman/data_refinery_foreman/surveyor/transcriptome_index.py
- workers/data_refinery_workers/downloaders/transcriptome_index.py
- workers/data_refinery_workers/processors/test_transcriptome_index.py
- workers/data_refinery_workers/processors/transcriptome_index.py
- workers/data_refinery_workers/settings.py
https://github.com/AlexsLemonade/refinebio/issues/163
Tracks the assembly name we use in addition to the assembly version. It does so in the same manner in which it tracks the assembly version.
I am running a transcriptome index job for `Caenorhabditis elegans` locally.
> Adds assembly_name to the OrganismIndex model and populates it.

- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/management/commands/create_compendia.py
- workers/data_refinery_workers/processors/management/commands/fetch_compendia.py
- workers/data_refinery_workers/processors/test_smasher.py
- workers/data_refinery_workers/processors/test_utils.py
- workers/run_command.sh
https://github.com/AlexsLemonade/refinebio/issues/448
Adds `create_compendia` and `fetch_compendia` management commands.
Get all experiments for each species, smash by species. Fetch when finished.
Tested locally, needs more data though to make sure smashers have enough RAM.
> Adds Create and Fetch Compendia Commands

- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio-frontend/issues/202
Remove the `has_publication` filter from the response if zero results match the filter.
I ran the frontend locally against a local API instance to make sure this fix fixes the problem on the frontend.
> Remove has_publication filter if 0

- api/data_refinery_api/serializers.py
Resolves #469 
Adds `scale_by` to the list of fields in the `DataSet` serializer.
I ran the frontend and API locally and confirmed that these are the correct changes for the frontend issue associated with #469 
> Expose scale_by to the API

- workers/data_refinery_workers/processors/gene_convert_illumina.R
- workers/data_refinery_workers/processors/no_op.py
- workers/data_refinery_workers/processors/test_no_op.py
- workers/run_tests.sh
Jackiecrunch.
Not all of Illumina files have the same header. This attempts to normalize them so that they can succesfully gene convert.
This doesn't support _all_ of the scenarios we've encountered (particularly, the one with lots of samples in a single file where the sample titles don't match the metadata), but does improve the amount we can support. 
New test file and tests added. More assertions for existing tests.
> Improvements for Different Illumina Headers in NO_OP

- .circleci/slackpost.sh
- foreman/data_refinery_foreman/foreman/main.py
Adds a missing `fi` to an unimportant script.
> Tiny Fix in Slackbot Script

- infrastructure/deploy.sh
- infrastructure/instances.tf
N/A
The API went down for both staging and the dev stack. This is why.
I deployed to the dev stack and the API started working again!
> Fix restarting API server after deploys. Switch AGS to 1b.

- workers/data_refinery_workers/processors/illumina.py
- workers/data_refinery_workers/processors/management/commands/delete_local_files.py
- workers/data_refinery_workers/processors/test_geo.py
- workers/data_refinery_workers/processors/utils.py
n/a
Keeping all of our OriginalFiles on S3 is going to be far too expensive. This deletes them when we're through with them. Additionally adds a new management command to help with clean-up.
No
> Dont S3-Sync OriginalFiles // Adds delete_local_files command

- foreman/data_refinery_foreman/surveyor/geo.py
- workers/data_refinery_workers/processors/illumina.py
- workers/data_refinery_workers/processors/test_geo.py
https://github.com/AlexsLemonade/refinebio/issues/499
Experiment was being processed with the wrong processor. Use the right processor.
Ran sample locally
> Dont Trust GEO to Accurately Describe Data As Raw Or Not

- workers/data_refinery_workers/processors/agilent_twocolor.py
- workers/data_refinery_workers/processors/array_express.py
- workers/data_refinery_workers/processors/illumina.py
- workers/data_refinery_workers/processors/no_op.py
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/test_salmon.py
- workers/data_refinery_workers/processors/transcriptome_index.py
NA
`utils.handle_processor_error` function was not called correctly by processors.
> Call utils.handle_processor_error properly

- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/test_transcriptome_index.py
- workers/data_refinery_workers/processors/transcriptome_index.py
- workers/run_tests.sh
https://github.com/AlexsLemonade/refinebio/issues/455
Adds `/<length>` to working directories. Uses S3-synced file paths in Salmon.
New assertions are added that process both `long` and `short` and ensure that the resulting archives are unique.
> Safer Parallel TXI

- workers/data_refinery_workers/downloaders/geo.py
NA
We were noting as an error, even for expected failures to download. Now we only note an error if things totally failed and the routine becomes a warning. This will make sentry slightly more useful.
N/A
> Routine issues -> warning; total fail -> error

- common/data_refinery_common/utils.py
NA
Function was double indented. Make it single indented.
NA
NA
> style: double indent -> single indent

- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_smasher.py
https://github.com/AlexsLemonade/refinebio/issues/506
Different logic for delivering data depending on aggregation type.
Assertions updated to reflect new formats.
> Deliver Experiment-Aggregated Metadata in Seperate Files

- infrastructure/disk.tf
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_qn_reference.py
n/a
Tiny fix to the QN test. Not a problem with the implementation, just makes the test pass again.
> Fixes QN Ref Target Test Inputs

- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
n/a
Retry if volume mounting fails
Ran on remote
> Add Retrier to EBS Mounter

- api/data_refinery_api/serializers.py
- common/data_refinery_common/models/models.py
n/a
Adds a boolean property to Dataset API response to state the existence/nonexistence of an email without revealing the email itself.
> Adds `has_email` property to Dataset API response

- .dockerignore
N/A
I ran into some permissions issues while setting up my Ubuntu desktop. @kurtwheeler added this, which fixed my woes.
- Bugfix
N/A
> Update .dockerignore nomad-job-specs

- .circleci/update_docker_img.sh
N/A, cleaning up after #575 
I had some mistakes in the script. It kinda worked, but very oddly. This should fix things up to be perfect though.
I tested that all the images got skipped when I ran locally with the same env vars as prod would have. (or close enough for jazz.)
> Fixes up a few mistakes in the last deploy PR.

- .boto
- foreman/dockerfiles/Dockerfile.foreman
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- workers/dockerfiles/Dockerfile.affymetrix
- workers/dockerfiles/Dockerfile.downloaders
- workers/dockerfiles/Dockerfile.illumina
- workers/dockerfiles/Dockerfile.no_op
- workers/dockerfiles/Dockerfile.salmon
- workers/dockerfiles/Dockerfile.smasher
- workers/dockerfiles/Dockerfile.transcriptome
na
Make Boto shush up.
(sneaks in adding `awcli` and Docker for non-us-east-1 Ubuntu)
> Adds .boto file for globablly changing boto log config

- format_nomad_with_env.sh
- infrastructure/deploy.sh
- infrastructure/disk.tf
- infrastructure/instances.tf
- infrastructure/list_hosts.sh
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- infrastructure/security.tf
n/a
Purges last remnants of EFS, adds better support for the `eu-west-2` region by adding logic to the `aws_ami` TF object.
> Purge EFS, Better eu-west-2 support

- api/data_refinery_api/serializers.py
- api/data_refinery_api/tests.py
- common/data_refinery_common/models/models.py
https://github.com/AlexsLemonade/refinebio-frontend/issues/268
Adds `get_sample_technologies` to model and `technologies` to API response
New assertion
> Adds `get_sample_technologies` to model and `technologies` to API response

- workers/dockerfiles/Dockerfile.no_op
https://github.com/AlexsLemonade/identifier-refinery/issues/5
https://github.com/AlexsLemonade/identifier-refinery/issues/1
Trivial change to use a different Zenodo URL.
> Update to Latest Version of Identifier Refinery

- common/dockerfiles/Dockerfile.common_tests
- workers/dockerfiles/Dockerfile.affymetrix
- workers/dockerfiles/Dockerfile.downloaders
- workers/dockerfiles/Dockerfile.illumina
- workers/dockerfiles/Dockerfile.no_op
- workers/dockerfiles/Dockerfile.salmon
- workers/dockerfiles/Dockerfile.smasher
```git
- ha.pool.sks-keyservers.net
+ na.pool.sks-keyservers.net
```
😎
> HA Pool -> NA Pool

- workers/data_refinery_workers/downloaders/utils.py
N/A came up during crunch
This missing dependency breaks all downloader jobs.
N/A
> Fix a stupid missing dependency.

- foreman/data_refinery_foreman/surveyor/management/commands/unsurvey.py
N/A came up during crunch.
This is dumb. To be fair though, this line only runs if a processor jobs succeeds in the cloud. This scenario was hard to test.
Testing in my dev stack.
> Fixes unsurveyor typo

- common/data_refinery_common/models/models.py
- foreman/data_refinery_foreman/surveyor/management/commands/survey_all.py
- workers/data_refinery_workers/processors/management/commands/create_qn_target.py
- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_qn_reference.py
- workers/dockerfiles/Dockerfile.downloaders
- workers/install_downloader_R_only.R
- workers/run_tests.sh
https://github.com/AlexsLemonade/refinebio/issues/599
Various changes described in title, mostly about functionality and quality assurance. 
See related ticket.
Running..
> SRA Fixes // Different R Downloader Deps // QN Target QA // K-S QA Test

- workers/data_refinery_workers/processors/salmon.py
Discussed IRL, prevents fasterq-dump from using the local FS.
> give fasterqdump its own tempdir

- foreman/nomad-job-specs/surveyor.nomad.tpl
- foreman/nomad-job-specs/surveyor_dispatcher.nomad.tpl
- workers/data_refinery_workers/downloaders/sra.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/data_refinery_workers/processors/salmon.py
- workers/nomad-job-specs/affymetrix.nomad.tpl
- workers/nomad-job-specs/downloader.nomad.tpl
- workers/nomad-job-specs/illumina.nomad.tpl
- workers/nomad-job-specs/no_op.nomad.tpl
- workers/nomad-job-specs/salmon.nomad.tpl
- workers/nomad-job-specs/smasher.nomad.tpl
- workers/nomad-job-specs/transcriptome.nomad.tpl
N/A came up during crunch
Fix SRA path collision, bump up downloader ram, improve handling of already downloaded files.
Tested in crunches
> Minor fixes from running crunches

- infrastructure/instances.tf
- workers/data_refinery_workers/processors/salmon.py
N/A came up while doing pre-prod-deploy test
A couple fields gave me some issues while running one last deploy against my dev stack just for the purpose of catching this kind of thing:
```
Error: aws_db_instance.postgres_db: backup_retention_period: cannot parse '' as int: strconv.ParseInt: parsing "": invalid syntax
Error: aws_db_instance.postgres_db: only alphanumeric characters and hyphens allowed in "final_snapshot_identifier"
```
Ran a deploy to my dev stack.
> Adds some minor infra fixes.

- workers/README_DATASET.md
#333 
The README file we included with downloads was pretty sparse. This update adds more information about the contents of the download zip file and some very basic usage example.
N/A
> Add contents description and some usage information to README included in download

- .circleci/update_docker_img.sh
N/A Came up during master deploy.
This is a nice check to have, but it needed an `-f` flag.
N/A
> Prevent a very stupid deploy failure.

- .circleci/update_docker_img.sh
Deploying this change: https://github.com/AlexsLemonade/refinebio/pull/658
> Improve the way we check the git branch while deploying. (#658)

- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio-frontend/issues/140
This adds all the statics required by the dashboard to the `/stats` endpoint.
When the parameter `range` is included (can be one of `day`, `week`, `month` or `year`), the endpoint will also return statics for several time intervals that we use to build the graphs in the front-end.
I didn't add any tests for this, should we?
Check the dashboard in the front-end.
This is the dashboard running locally.
> Modify stats endpoint to include all data we need on the dashboard

- api/data_refinery_api/views.py
N/A
We were only counting samples.
> Dashboard count experiment/samples separately

- workers/data_refinery_workers/downloaders/test_array_express.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/data_refinery_workers/processors/utils.py
https://github.com/AlexsLemonade/refinebio/issues/708
Adds a `SIGTERM` handler for downloaders and processor jobs.
Very difficult to write a test for this, but tried it manually for downloaders and it works.
> Add Handling of SIGTERM Signals

- api/data_refinery_api/serializers.py
- api/data_refinery_api/tests.py
- common/data_refinery_common/models/models.py
Related:
https://github.com/AlexsLemonade/refinebio/pull/589
https://github.com/AlexsLemonade/refinebio/issues/701
This was already approved by got reverted by mistake.
> Re-Adds Technologies

- foreman/data_refinery_foreman/foreman/main.py
https://github.com/AlexsLemonade/refinebio/issues/679
Avoid Nomad being down flooding our logs.
> Adds Better Nomad Exception Handling in the Foreman

- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_smasher.py
> Remove Affy Control Probes When Smashing 

- common/data_refinery_common/job_lookup.py
- common/data_refinery_common/message_queue.py
- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/data_refinery_workers/processors/management/commands/run_processor_job.py
- workers/data_refinery_workers/processors/utils.py
- workers/nomad-job-specs/janitor.nomad.tpl
- workers/run_tests.sh
Despite our best efforts, our EBS volumes were filling up with trash.
Adds a new processor, JANITOR, which will clean up jobs which get killed by OOM or AWS interruption.
Dispatched by the foreman, runs every 30 minutes on each volume.
New tests added.
> Adds JANITOR Processor

- .circleci/config.yml
- workers/data_refinery_workers/processors/janitor.py
- workers/data_refinery_workers/processors/management/commands/run_janitor.py
- workers/data_refinery_workers/processors/test_janitor.py
- workers/run_janitor.sh
n/a
Adds `run_janitor` command and `run_janitor.sh` script.
Also, includes the actual janitor file, which wasn't added in the last PR. Which still passed review. Hrm.
Also added to CircleCI conf, as that's why it still "passed" the tests despite the missing file.
> Janitor, Part 2

- workers/data_refinery_workers/processors/janitor.py
> Have Janitor skip _index directories so we dont redownload TXI

- api/data_refinery_api/views.py
- infrastructure/networking.tf
https://github.com/AlexsLemonade/refinebio/issues/707
TODO..
> [WIP] Various Stats/Dash Improvements

- common/install_devtools.R
- workers/affymetrix_dependencies.R
- workers/data_refinery_workers/downloaders/test_array_express.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/illumina_dependencies.R
- workers/install_affy_only.R
- workers/install_downloader_R_only.R
- workers/install_gene_convert.R
- workers/install_tximport.R
- workers/qn_dependencies.R
Hotfix for a CCI issue. 
Related: 
https://circleci.com/gh/AlexsLemonade/refinebio/8975
https://github.com/AlexsLemonade/refinebio/pull/764
https://github.com/AlexsLemonade/refinebio/pull/763
> Only Throttle Download Job Dispatching When Running in Cloud 

- infrastructure/networking.tf
https://github.com/hashicorp/terraform/issues/19315
Apparently  this bug is fixed in the newest version of the AWS provider, assuming that this is actually the same bug.
I am going to test this with a staging deploy because testing a dev stack wouldn't include migrating an existing stack which I think is what should really be tested here.
> Upgrades AWS terraform provider to v1.37.0

- .circleci/remote_deploy.sh
Adds some output to `remote_deploy.sh` so we can tell roughly where in the deploy process cirlceci is without popping onto the deploy box.
N/A
> Add a couple progress outputs to remote_deploy.sh.

- workers/illumina_dependencies.R
N/A: R decided that we shouldn't deploy for a few hours.
The R dependency `doParallel` randomly broke... We should probably put more effort into figuring out why but at the moment we just need to get a deploy out so the API will go back up.
Unit tests cover this well
> Change CRAN URL, of course

- foreman/data_refinery_foreman/surveyor/management/commands/surveyor_dispatcher.py
- foreman/run_surveyor.sh
N/A, noticed it while testing https://github.com/AlexsLemonade/refinebio/pull/834
These variable names didn't match. Now they do!
It's getting late here, I'll test this tomorrow.
> Fixes a variable name mismatch.

- .circleci/remote_deploy.sh
https://github.com/AlexsLemonade/refinebio/issues/844
Hopefully a hotfix for [this problem](https://circleci.com/gh/AlexsLemonade/refinebio/9721).
> Fix permissions error for individual logs

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
N/A I broke the tests by getting overeager with merging
These tests were broken but I didn't wanna wait for Circle so I ran them locally and merged, turns out these didn't actually run before the end_to_end tests which I thought were the end (and they take a while so I didn't wait on them).
This is a unit test fix so the unit tests test it.
> Fix two tests that I thought I had made sure passed before merging.

- foreman/data_refinery_foreman/foreman/main.py
N/A Came up during deploy tests
I didn't think I needed that, thanks unit tests for catching it!
N/A
> Add a line escape to fix a dumb dumb mistake.

- common/data_refinery_common/models/models.py
- foreman/data_refinery_foreman/foreman/main.py
- infrastructure/instances.tf
- workers/data_refinery_workers/processors/janitor.py
- workers/data_refinery_workers/processors/test_janitor.py
- workers/data_refinery_workers/processors/test_smasher.py
n/a
Small fixes, one to make the Janitor slightly more robust but slightly less aggressive, and one more to ensure that indexes aren't corrupt after download.
> Better Janitor Error Handling // Index Integrity Verification

- infrastructure/instances.tf
We were having better luck with our capacity until yesterday, when we got nothing across the board.
This adds some of the smaller types so that at least we keep things moving while the big fellas are occupied.
The 'a' types are interesting as they use cheaper AMD chips. I'm curious how this will affect Salmon performance.
n/a
> Add More Shwaggy Instance Types

- workers/data_refinery_workers/processors/salmon.py
n/a
We identified some nastiness with the logic of how indexes are installed. This attempts to correct some of that.
> Make index unpacking considerably more robust

- common/data_refinery_common/message_queue.py
- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/surveyor/external_source.py
- foreman/data_refinery_foreman/surveyor/geo.py
- workers/data_refinery_workers/processors/janitor.py
- workers/data_refinery_workers/processors/no_op.py
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/utils.py
n/a
Fixes our largest source of error (although these jobs aren't actually processable) and improves debuggability elsewhere.
> Fixes Bug In Affy Processor When Files Are Missing  // Blacklist Unsupported Files // Improve Debuggability

- common/data_refinery_common/models/models.py
- common/data_refinery_common/models/test_models.py
> HOTFIX - dont call db in get_sample_metadata_fields

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
https://github.com/AlexsLemonade/refinebio/pull/889
When I optimized the prioritization code, I forgot to actually reenable it :man_facepalming: 
This just turns it and its tests back on.
This was in fact all tested for #889
> Reeable foreman prioritization, which I forgot to do after optimizing it.

- api/data_refinery_api/views.py
close #755 
By default, show processed first.
Check samples table locally.
> Default sort for `/samples` endpoint

- api/data_refinery_api/views.py
- workers/data_refinery_workers/processors/salmon.py
> HOTFIX: Restore fasterq-dump to default behavior, raise timeout 

- README.md
This required some fumbling around to get working again, thought I'd document the process for next time.
- Documentation
> Document Database Backup and Restore Process

- workers/data_refinery_workers/processors/test_utils.py
- workers/data_refinery_workers/processors/utils.py
> Support Nomad Retrying a Job Even When It Shouldnt

- workers/data_refinery_workers/processors/salmon.py
https://github.com/AlexsLemonade/refinebio/issues/930
This change is isolated from this branch: https://github.com/AlexsLemonade/refinebio/pull/932/files
but that changeset can't land until Nomad 0.8.7+ is released, which won't be for another ~2(+?) weeks.
> Backup .sra Files Before fasterq-dump

- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
They take a while, don't kill them like we do the others.
> Dont Timekill QN and Compendia Jobs

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
N/A trying to give the DB some relief
Our DB has been having some trouble recently. The job prioritization code is pretty DB heavy, so we're gonna see if disabling it gives the DB some relief. Also we aren't processing RNA-Seq right now anyway so it's not really even doing anything at the moment.
N/A unit tests cover this.
> Disable job prioritization in the Foreman and the tests.

- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
N/A Github found it for us
Sets the minimum version as recommended by github.
Unit tests outta cover this.
> Addresses a security alert that github clued us into.

- README.md
> Remove a potentially controversial sentence in the README.

- api/data_refinery_api/settings.py
https://github.com/AlexsLemonade/refinebio/issues/990
Describe the big picture of your changes.
Very small change, please confirm this is fixes your problem
> Raise CORSMiddleware Higher In Order

- api/data_refinery_api/views.py
N/A
Add title to the list of fields that we use to filter samples by a query.
> Include title field when filtering samples

- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio/issues/1000
Some of the fields aren't being searched. This searches those too.
> Search more fields via ES

- workers/data_refinery_workers/processors/smasher.py
https://github.com/AlexsLemonade/refinebio/issues/1001
Makes missing QN target error prettier.
> More Graceful Missing QN Target Error

- api/data_refinery_api/views.py
close https://github.com/AlexsLemonade/refinebio-frontend/issues/512
Make samples search case insensitive.
Tested locally
> Enable case insensitive samples search

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
Trivial, fixes ES redeploy requiring manual intervention
> No -it Inside AWS Init Data Script

- common.sh
- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_qn_reference.py
- workers/run_tests.sh
https://github.com/AlexsLemonade/refinebio/issues/1026
> Sanitize Inputs to QN Target Creation

- .circleci/config.yml
- .circleci/remote_deploy.sh
- .circleci/run_terraform.sh
https://github.com/AlexsLemonade/refinebio/issues/1030
I'm not as Circle familiar as you are but I think that takes care of it.
> Begin Support for -hotfix Deployments

- README.md
- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio/issues/1031
Part 1/4
> Dataset Download Slackbot Notifier

- foreman/data_refinery_foreman/foreman/management/commands/organism_shepherd.py
- foreman/data_refinery_foreman/foreman/management/commands/test_organism_shepherd.py
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/data_refinery_workers/processors/test_array_express.py
N/A came up during staging test of #1032 
I forgot to add the add_arguments method to the management command.
I also forgot that sometimes it's valid for samples to not have any jobs associated with them because sometimes we don't want to process them. So this handles that case as well.
I've run this on the staging box by pushing a new image to my own Docker repo and then running the command using that image.
> Fix shepherd command options, handle samples who don't have jobs.

- workers/data_refinery_workers/processors/management/commands/create_compendia.py
> Missing compendia management command import

- workers/nomad-job-specs/create_compendia.nomad.tpl
This killed the instance, let's tone it down a bit.
> Nerf Compendia Jobspec CPU

- workers/nomad-job-specs/create_compendia.nomad.tpl
> No Compendia OOM

- workers/data_refinery_workers/processors/create_compendia.py
Stupid one, I had to manually retrieve the compendium because of this.
> Wrong Bucket

- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio/issues/1075
> Fix Platform Filter Type

- api/requirements.in
- api/requirements.txt
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
N/A Github alerted about vulnerable dependencies.
Just bumped django versions. Also fixed requirements.txt files that had been manually modified instead of just adding the deps to requirements.in.
> Update Django to latest vulnerability and fix requirements.txts

- api/requirements.in
- api/requirements.txt
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
Reverts AlexsLemonade/refinebio#1086
I merged it before tests passed. That was dumb. I'll reopen once I fix whatever's going on.
> Revert "Update Django to latest vulnerability and fix requirements.txts"

- common/data_refinery_common/models/documents.py
https://github.com/AlexsLemonade/refinebio/issues/1078
I don't know why this works, but reordering the filters seems to fix it.
> Reorder Tokenizers

- install_nomad.sh
I also custom built a bespoke version as well but this is fine I GUESS
> Bump from nomad from 0.9.0-beta2 to 0.9.0-beta3, Parameterize

- api/data_refinery_api/views.py
n/a
I needed a better way to diagnose issues related to available transcriptome indexes. This adds a secret API option to list all available TXIs.
> Add ?all=True to TXI API endpoint

- foreman/data_refinery_foreman/surveyor/sra.py
- foreman/data_refinery_foreman/surveyor/test_sra.py
#1116
We've been told that these dedicated Aspera servers are faster than the old anonftp ones. Let's find out.
> Use Newer SRA Endpoints

- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio/issues/1120
Trivial fix
> Accept Organism in both ID and Named Forms

- common/data_refinery_common/models/models.py
- infrastructure/disk.tf
- workers/data_refinery_workers/processors/smasher.py
> Keep Results In Bucket For 7 Days 

- foreman/data_refinery_foreman/foreman/main.py
- format_nomad_with_env.sh
#1067 
Looks like some salmon jobs are still getting OOM killed. Not too many ways we can deal with that other than just adding a larger tier.
WIP.
> Adds an additional tier for Salmon jobs.

- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
close #1063 
Adds total sample counts to the filters in the API. This will require changes in the frontend as well.
Tested endpoint locally
> Add total sample counts to facets

- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio/issues/1136
Boosts title and adds support for `_score` ordering.
> Boost title result, add _score ordering

- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/surveyor/sra.py
- workers/data_refinery_workers/downloaders/sra.py
- workers/data_refinery_workers/downloaders/test_array_express.py
- workers/data_refinery_workers/downloaders/test_sra.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/nomad-job-specs/downloader.nomad.tpl
https://github.com/AlexsLemonade/refinebio/issues/1146
Forces new SRA endpoints. Detailed testing actually reveals that these endpoints are way way slower (20 vs 150 Mb/s) than the old ones, but hopefully they are less prone to failure. Not sure how we want to proceed, but here it is.
> [Discussion] Force New Endpoints

- README.md
> Update README with better instructions for triggering deploys.

- common/data_refinery_common/models/documents.py
https://github.com/AlexsLemonade/refinebio-frontend/issues/535
Faaaiiiirly certain this was the problem given this demo:
http://snowballstem.org/demo.html
(type in homo sapiens)
> No snowball for organism_names

- foreman/data_refinery_foreman/surveyor/array_express.py
Source was bad data in the metadata files, not the API response.
> Fix for #1080

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
N/A trying to get elasticsearch index working automatically again.
I should have included this in #1157 but I didn't think about it. /var/log/api_cron.log is empty so I guess all the output is happening on stderr.
I tested that a command like this works as expected.
> Log stderr too when populating elasticsearch index.

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/performant_pagination/__init__.py
- foreman/data_refinery_foreman/foreman/performant_pagination/pagination.py
- foreman/data_refinery_foreman/foreman/performant_pagination/runtests/runcoverage.py
- foreman/data_refinery_foreman/foreman/performant_pagination/runtests/runtests.py
- foreman/data_refinery_foreman/foreman/performant_pagination/runtests/settings.py
https://github.com/AlexsLemonade/refinebio/issues/1155
We still haven't actually confirmed that the old pagination was actually the problem since the problem only manifests at very high levels of load, but that was my primary theory. This uses the `performant_pagination` package (hard-imported since it unfortunately isn't available on PyPI) to attempt to alleviate some of the load.
We won't know if this really works the way we want until we try it at scale on staging though.
> Improve Pagination Performance

- foreman/data_refinery_foreman/foreman/main.py
#1175 
Pagination performance didn't fix this issue. We think it's related to having too many downloader jobs committing harakiri which involves database calls.
Unit tests!
> Prevent the Foreman from queuing more than 200 downloader jobs at once.

- workers/data_refinery_workers/processors/janitor.py
- workers/data_refinery_workers/processors/salmon.py
Some small changes here, one fix of a broken TXI failure logger, the other making a very chatty janitor shut up.
> Small Fixes

- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
- common/data_refinery_common/utils.py
https://github.com/AlexsLemonade/refinebio-frontend/issues/566
Add improvements to stats endpoint that were suggested on https://github.com/AlexsLemonade/refinebio-frontend/issues/566. The most important ones are:
- Use `last_modified` when calculating stats on processed samples
- Fix nomad jobs aggregation by volume.
Not sure why tests are failing ... seems the mocks don't work. WIll look into it
> Fixes for the stats endpoint

- foreman/data_refinery_foreman/foreman/test_main.py
https://github.com/AlexsLemonade/refinebio/pull/1176
Changes from #1176 fixed but did not automatically test new functionality. This adds a test which covers the updated code.
> Adds Test for Updated Pagination Code

- common/data_refinery_common/models/documents.py
https://github.com/AlexsLemonade/refinebio/issues/1198
Single character change.
> Lower Min NGram

- foreman/data_refinery_foreman/foreman/main.py
65 kills SRA after about an hour and a half. Also fixes a log statement.
> Lower the Max Again, Fix Log Line

- workers/data_refinery_workers/processors/salmon.py
> Fix SyntaxError

- common/data_refinery_common/models/models.py
- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/foreman/main.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/tximport.py
- workers/data_refinery_workers/processors/utils.py
https://github.com/AlexsLemonade/refinebio/issues/1203
My theory is that these were being cleaned up early and causing TXI failures for larger jobs as the inputs were being cleaned up too early.
> Force TXI downloads to local working directory

- foreman/data_refinery_foreman/foreman/main.py
https://github.com/AlexsLemonade/refinebio/issues/944
The foreman currently ignores lost smasher jobs. Somehow, Nomad can drop dispatched smasher jobs that get dispatched but never started. This hopefully adds support for those Smashers which get dropped.
> Add Smasher Support To The Foreman

- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/downloaders/utils.py
- workers/data_refinery_workers/processors/salmon.py
- workers/data_refinery_workers/processors/utils.py
N/A 
We've been redownloading and reprocessing data in part because of this. Other thing that needed fixing is in #1208 
None but unit tests cover this code well.
> Improve our start_job functions to better prevent and log completed work

- foreman/data_refinery_foreman/foreman/main.py
> Missing library on timedelta call

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
> Add test for new foreman smasher checker

- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
That last test didn't work yet and got merged too early. This makes the test actually _pass_.
> Make That New Test Pass

- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_smasher.py
https://github.com/AlexsLemonade/refinebio/issues/1216
Less pretty, more functional.
> Use accession_code rather than title to label smashed metadata

- api/data_refinery_api/views.py
#707 
- Change job status to successful, failed, pending and open
- Ensure we only count datasets with an associated email in the stats
> Updates to dashboard endpoint

- foreman/data_refinery_foreman/foreman/main.py
We were counting blacklisted jobs as successful dispatches, which meant we were under-allocating.
> Only Increment Job Counter On Succesful Dispatching

- foreman/data_refinery_foreman/foreman/main.py
I think the Novocaine was getting to me yesterday. It was logging, but not returning. With this change, it'll also set it as failure and mark it as a no-retry.
> Clean up that has_been_processed checker

- foreman/data_refinery_foreman/foreman/main.py
SRA capacity seems greatly reduced. We need to re-lower our DLJ/Node until it's capable again.
> Reduce jobs/node

- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/server-instance-user-data.tpl.sh
#1235 
Same as #1235 but in additional places I should have done in that PR.
> Increase monit timeout in three additional places it's needed.

- workers/data_refinery_workers/processors/salmon.py
N/A found it while looking at what happened over the weekend.
Trivial
> Fix a variable name that caused only 90 failures over the weekend.

- workers/README_DATASET.md
Improvements to the aggregated dataset README meant to mirror the **Getting Started** section of the documentation (https://github.com/AlexsLemonade/refinebio-docs/pull/84).
N/A
> Minor improvements to aggregated dataset README

- .circleci/config.yml
N/A https://circleci.com/gh/AlexsLemonade/refinebio/16712
#1243 
We didn't quite get that test disabled properly, this fixes it.
> Stop deleting an image we aren't building temporarily.

- .github/ISSUE_TEMPLATE.md
We have a template. Skip the checklist.
N/A
At the moment, we are not receiving too many external contributions that do not complete the elements of our template. this removes the checklist.
N/A
- Issue template
N/A
> Remove the checklist from the issue template.

- foreman/data_refinery_foreman/foreman/management/commands/organism_shepherd.py
N/A came up when I turned the organism shepherd loose on humanity
The organism shepherd was designed before we figured out our solution for controlling the rate of our downloads. This makes it so that it doesn't directly queue downloader jobs so that the foreman can control the flow of them.
N/A
> Limits the rate at which the shepherd queues downloader jobs.

- foreman/data_refinery_foreman/foreman/main.py
#1234 staging test
I didn't know this could happen, fun stuff Nomad!
> Handles the case where downloader jobs don't have any children.

- foreman/data_refinery_foreman/foreman/main.py
#1263 
I used the wrong key...
> That was a dumb mistake, it's nice that tests caught it though.

- infrastructure/permissions.tf
- infrastructure/users.tf
- infrastructure/variables.tf
https://github.com/AlexsLemonade/refinebio/issues/1256
AWS resource permissions lockdown.
> IAM Lockdown

- infrastructure/deploy.sh
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
This is a nasty one. Will also be handled by the IAM lockdown, but this should be the correct behavior.
Also cleans out old job specs.
> Don't Let Staging Mount Prod Volumes

- workers/dockerfiles/Dockerfile.salmon
#1287
Upgrade Salmon to 0.13.1
> Upgrade Salmon to 0.13.1

- workers/run_tests.sh
> Ignore salmon tests

- foreman/data_refinery_foreman/surveyor/test_end_to_end.py
#1287 
This test will probably also break, so let's skip it too.
> Skip the salmon end-to-end test.

- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_smasher.py
#1288 
Adds this field to the metadata.
N/A, I plan on testing this on staging since I don't have an experiment's worth of data I can smash locally.
> Adds quantile_normalized field to metadata for downloads.

- .circleci/remote_deploy.sh
- .circleci/verify_tag.sh
#1261 
Double quoting this variable exposed that it was always empty and that we weren't actually verifying anything :scream: This fixes that issue (hopefully, it's hard to test without a deploy).
Gotta deploy to test
> Fixes verification of our git tags

- README.md
- foreman/data_refinery_foreman/surveyor/external_source.py
#1287 
Ensure jobs are executed even when a transcriptome indexes have been generated.
Tested locally
> Allow regenerating transcriptome indices

- infrastructure/permissions.tf
Fix aws policies were failing when max_clients=0.
> Fix aws permissions

- infrastructure/permissions.tf
- run_nomad.sh
> [Master] Deploy

- workers/data_refinery_workers/processors/smasher.py
close #1251 
Send notification to slack when a dataset processing fails
Tested [slack config](https://api.slack.com/docs/messages/builder?msg=%7B%22username%22%3A%22EngagementBot%22%2C%22icon_emoji%22%3A%22%3Ajack_o_lantern%3A%22%2C%22attachments%22%3A%5B%7B%22fallback%22%3A%22Required%20plain-text%20summary%20of%20the%20attachment.%22%2C%22color%22%3A%22danger%22%2C%22author_name%22%3A%22author%40email.com%22%2C%22title%22%3A%22Dataset%20failed%20processing%22%2C%22title_link%22%3A%22http%3A%2F%2Fwww.google.com%22%2C%22text%22%3A%22Missing%20QN%20targets%20(reason)%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Dataset%20id%22%2C%22value%22%3A%2223231231%3D1232123%3D12313%22%2C%22short%22%3Atrue%7D%5D%7D%5D%7D)
> Send notification to slack when a dataset processing fails

- workers/data_refinery_workers/processors/smasher.py
close #1306 
Link 'Download' to dataset page instead of S3
none
> Link 'Download' to dataset page instead of S3

- workers/data_refinery_workers/processors/smasher.py
N/A Came up while working on unrelated tests
This is a bad one. The smasher's code had a syntax error so all the smasher jobs failed. We didn't even get notified about it.
N/A but the tests are actually running now.
> Fix a syntax error in the smasher.

- foreman/data_refinery_foreman/surveyor/sra.py
- foreman/data_refinery_foreman/surveyor/test_sra.py
#542 
A bug was preventing us from getting metadata from SRA samples. I fixed the bug and added a test for harmonized SRA metadata.
https://github.com/AlexsLemonade/refinebio/issues/542#issuecomment-505498535
I also wrote a new test to verify that SRA metadata is harmonized.
> Allow SRA metadata to be processed, and test the harmonization

- foreman/data_refinery_foreman/surveyor/harmony.py
Fixes #1332 
I added a field to the harmonizer for age.
If this pull request has any implications for data or metadata processing or addresses an issue labeled `sci review`, please include an overview of the methods used (e.g., briefly explain _how_ the data gets processed). 
Include sufficient detail for reviewers or users that are not expert developers to evaluate the validity of the approach. 
Any pull request with a methods section requires scientific review in addition to code review.
What types of changes does …
> Added 'age (yrs)' to harmonizer

- foreman/data_refinery_foreman/foreman/main.py
N/A tuning
We're downloading data faster than we can process it. Since we're gonna do a master deploy today let's include this.
- Tuning
N/A
> Bump downloader jobs down by 25 

- workers/data_refinery_workers/processors/salmon.py
N/A noticed this when checking on things
I should have set this a while ago, but I thought that I had.
N/A this is rather straight forward and testing takes a really long time :/
> Set no_retry=True for jobs that timed out

- scripts/install_all.sh
N/A
Add a line to source the virtualenv in case the host computer doesn't have setuptools. I also added a line to tell the user to log out and log back in after changing the docker permissions, because otherwise the rest of the script would fail with a permissions error.
I ran the script inside a virtual machine.
> Bugfixes in install_all.sh

- scripts/common.sh
#753 
We got close but this function wasn't quite exact. This should fix it.
I tested the new function.
> Fix the docker_img_exists function in common.sh

- .circleci/config.yml
- workers/data_refinery_workers/processors/smasher.py
Fixes #1348 
I added a CircleCI test that runs `flake8`, a python linter. Eventually, if we migrate to full-on PEP8 standards, this could check all of PEP8, but for now I only have it check for `E9` (syntax errors).
I undid the changes from #1347 to make sure that the syntax test would catch that error, and then I re-did the changes to make sure the tests passed.
> Added a Syntax Test

- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/test_smasher.py
Closes #1296 
I added a column for the experiment accession to the smasher TSV files.
I added to the smasher tests.
> Added experiment_accession column to smasher TSV files

- api/data_refinery_api/settings.py
- api/data_refinery_api/tests.py
- api/data_refinery_api/urls.py
- api/data_refinery_api/views.py
close #1345 
Adds `/v1` api version to all urls
Tested urls locally as well as the docs
> Api version

- .circleci/remote_deploy.sh
- .circleci/update_docker_img.sh
- scripts/common.sh
Closes #1404
I removed the lines that automatically put every hotfix onto master.
NOTE: In order for the dev hotfix deploys to work, the proper tag format is v$VERSION-dev-hotfix.
I tested the changes to `get_master_or_dev()` locally.
> Allow hotfixes from dev

- api/data_refinery_api/views.py
#1271
Since we know that people might want to search for their own name (and maybe their institution/a famous one), boost those in elasticsearch.
I ran the API locally. It's kind of hard to tell the difference with the few experiments I had locally, but it should help surface names easier.
> Boost authors and institution in Elasticsearch

- api/data_refinery_api/views.py
Closes #1397 
I added `DjangoFiltersBackend` to the `SamplesList` view, and added the fields to filter against to the view.
I ran the API locally to make sure that the filters work, then I ran the frontend against the local API to make sure that the search on the website was not broken by the filters.
> Add filters to the samples endpoint

- .circleci/run_terraform.sh
N/A came up while debugging deploy
Fix `run_terraform.sh`
If this pull request has any implications for data or metadata processing or addresses an issue labeled `sci review`, please include an overview of the methods used (e.g., briefly explain _how_ the data gets processed). 
Include sufficient detail for reviewers or users that are not expert developers to evaluate the validity of the approach. 
Any pull request with a methods section requires scientific review in addition to code review.
What types of changes …
> Fix problems with deploy

- common/data_refinery_common/job_lookup.py
- foreman/data_refinery_foreman/foreman/main.py
#1427
I noticed these things while debugging #1427. I don't think they will actually fix that issue, but they're bugs that should be squashed regardless.
I tested the regex locally and the other filters I am confidant about.
> Fixes some small issues I noticed while trying to figure out the infinite job loop.

- common/data_refinery_common/job_lookup.py
- common/data_refinery_common/models/jobs.py
- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
> Revert data cleanup changes

- .circleci/config.yml
Closes #1426 
I removed the ignore line from the CircleCI config, because it seems like it doesn't work properly (at least according to how we read the docs). Instead, the filter uses regex lookahead to filter against `-hotfix` at the end of a version tag.
https://regexr.com/4iisi
I used the regex tester above to test the regex on possible version tags.
> Changed circleci config to avoid confusion

- foreman/data_refinery_foreman/foreman/management/commands/create_missing_downloader_jobs.py
#1391 
The `create_missing_downloader_jobs` takes a long time because it tries to create downloader jobs for samples with unsupported platforms. This checks that a downloader job can be created before actually trying to create a new downloader job.
Didn't tested locally.
> Ensure a downloader job can be created before trying to create one

- workers/R_dependencies/README.md
N/A
It should say "transitive" dependencies, not "transient" dependencies.
N/A
> Fix typo in R_dependencies README

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/test_main.py
Should fix tests for #1479 and #1478
> Adds mock for get_active_volumes on foreman test

- foreman/data_refinery_foreman/foreman/test_main.py
#1488 
I forgot to make sure I didn't break any tests. It's not a big deal though, the code is fine, the test just had to change.
> Fix a unit test that my last PR broke.

- foreman/data_refinery_foreman/foreman/management/commands/feed_the_beast.py
#1500 
I meant to include this in #1500 but I forgot to commit it :/
> I don't know why wasn't an issue before but it turned out to be necessary.

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/management/commands/feed_the_beast.py
I forgot to include #1503 a minute ago :(
> [HOTFIX] Merge missing commit from the feed the beast branch

- foreman/data_refinery_foreman/foreman/management/commands/feed_the_beast.py
#1505 
I kicked off a functional test for #1505 before stepping away and forgot to check that it actually worked. This time I've actually done that though.
> Fix a typo. I forgot to actually check the output of my functional test :(

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/foreman/management/commands/feed_the_beast.py
> [HOTFIX] Improves the way we manage the queue of downloader jobs.

- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1258 
Also make the smasher instance large enough to handle them.
> Bump up RAM amount for compendia job

- workers/data_refinery_workers/processors/utils.py
N/A
I was reading this code and found a few queries that can be optimized.
None
> Query improvements to prepare_original_files

- .circleci/run_terraform.sh
- scripts/install_nomad.sh
> We were on 0.8.3 not 0.8.4

- infrastructure/permissions.tf
#1581 
I didn't know this was a thing. Maybe not the most scalable pattern, but right now I just wanna make use of the 11 expensive volumes we just got!
> Add capabilities to use more volumes!

- infrastructure/instances.tf
N/A tuning cause we have no capacity
We disabled these instance types a while ago. It looks like now that's biting us.
- Tuning
> Re-add 10-weight instances to try to get some capacity going.

- foreman/data_refinery_foreman/foreman/management/commands/feed_the_beast.py
Unintentional mistake in #1597
> Readd sleep to feed_the_beast.

- workers/data_refinery_workers/processors/create_compendia.py
- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/smasher.py
#1537 
-Logs system resources cpu/ram percents and also function opens and closes
-removes bottleneck appends from input files / technology columns in smasher
smasher
create compendia
Logs 
Bug fix
Lots of local testing
> logs and perf update

- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/test_qn_reference.py
#1537 
This should have been included with #1611
> fix notation

- workers/data_refinery_workers/processors/management/commands/qn_dispatcher.py
#1572 
@jaclyn-taroni mentioned that this should be the case but it never got implemented. Now it is!
Unit tests I suppose, I don't have 100 MA samples on my local machine.
> Make sure that QN targets are only built using Affy platforms.

- api/data_refinery_api/views.py
https://github.com/AlexsLemonade/refinebio-frontend/issues/759
https://github.com/AlexsLemonade/refinebio/issues/1604
https://github.com/AlexsLemonade/refinebio-frontend/issues/320
Adds the following numbers to the stats endpoint
So that we can display them accurately in the FE. I'll file another PR in the frontend to use them.
Tested locally
> Add stats for the about page

- api/data_refinery_api/views.py
#1570 
Process organism name parameter in samples endpoint
None
> Process organism name parameter in samples endpoint

- foreman/data_refinery_foreman/foreman/management/commands/retry_samples.py
#1627 
Add option to `retry_samples` command to find the samples that are associated with computed files that weren't uploaded to S3, and requeue those samples.
Tested queries locally.
> add option to retry samples command

- infrastructure/variables.tf
- workers/data_refinery_workers/processors/management/commands/create_compendia.py
Reverts AlexsLemonade/refinebio#1622
We aren't ready to run compedia jobs yet, so let's not pay 27 dollars an hour for the smasher until we're ready.
> Revert "Make smasher HUGE. Also make it so that human and mouse compendia mus…"

- api/data_refinery_api/views.py
> Disable about page stats

- infrastructure/variables.tf
- workers/data_refinery_workers/processors/management/commands/create_compendia.py
Reverts AlexsLemonade/refinebio#1633
I pushed this out too early so I reverted in order to keep the costs of the smasher instance lower. Now we're ready for it so it's gotta be re-reverted.
> Revert "Revert "Make smasher HUGE. Also make it so that human and mouse compendia mus…""

- common/data_refinery_common/migrations/0038_set_existing_compendia_svd_algorithm.py
#1645 
Paginate compendia svd algorithm assignments in migration as to not overload the DB
> paginate svd migration

- common/data_refinery_common/migrations/0038_paginate_default_svd_algorithm.py
#1650 
We didn't quite paginate/update correctly. This fixes that.
> Update each page of the migration.

- common/data_refinery_common/migrations/0038_paginate_default_svd_algorithm.py
N/A - fixing deploy - migration hangs on batch updates
This is a custom implementation of the pagination util that will allow for update calls on a queryset.
> batch pagination update

- api/data_refinery_api/views.py
#1604 
Added a parameter with a precalculated response for the stats in the about page.
Also modified the queries, the one to calculate the number of experiments was timing out.
Tested queries in prod.
> add dummy response to about stats endpoint

- workers/data_refinery_workers/processors/management/commands/create_compendia.py
#1631 
There was a typo so we can't kick off compendia jobs.
> Fix a small typo which prevented compendia from running.

- workers/data_refinery_workers/processors/management/commands/correct_affy_samples.py
That was `correct_affy_samples` not `correct_affy_cdfs`... My bad.
> Revert "Clean up disk space better in correct_affy_cdfs"

- common/data_refinery_common/models/models.py
> Check null computed file

- api/data_refinery_api/serializers.py
This will help identify the type of compendia in the frontend.
> Add quant_sf_only field to compendia serializer

- infrastructure/variables.tf
I haven't made an issue yet, but I will before Monday morning.
We can't run compendia right now, so let's make the smasher less expensive until we can.
> Scale down smasher since we can't make compendia right now.

- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/foreman/management/commands/check_computed_files.py
#1699 
The command `check_computed_files` failed while we were running on staging, seems that it was the `iterator()` function that we were trying. It failed after iterating over `50k` elements.
```
2019-09-30 20:20:44,196 i-0a35b53f5566c9a51 [volume: -1] data_refinery_foreman.foreman.management.commands.check_computed_files INFO: Checked 50000 computed files to see if they are in S3, so far found 58
File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 96, in inner
return func(*args, **kwargs)
psycopg2.OperationalError: cursor "_django_curs_139838820988672_1" does not exist
The above exception was the direct cause of the following exception:
File …
```
> Add utility function to iterate over large datasets using performant paginator

- workers/data_refinery_workers/processors/create_compendia.py
- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/smasher.py
#1697 
I took out all the places we logged a list and I changed a bunch of ERROR level logs to be less severe.
Unit tests should cover these fine, they're just logging. I did make sure that the pattern I used is valid and gets formatted nicely though.
> Tune smash logging

- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/foreman/management/commands/check_computed_files.py
#1696 
Parallelize command to check computed files. Hopefully, it will run faster like this.
None
> Parallelize command to check computed files

- foreman/data_refinery_foreman/foreman/management/commands/check_computed_files.py
#1696 
The previous command was failing because we were sending generators for each new process. This sends only the computed files 🕯 
Will test in staging
> Another attempt at parallelizing checking computed files on S3

- infrastructure/variables.tf
Reverts AlexsLemonade/refinebio#1684
We can run compendia again!! Now we need a bigger smasher!!!
> Revert "Scale down smasher since we can't make compendia right now."

- infrastructure/variables.tf
- workers/data_refinery_workers/processors/create_compendia.py
> [HOTFIX] Scale smasher down

- foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py
close #1729 
Aggregate quantpendia by experiment
None
> Aggregate quantpendia by experiment

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1743 
We finished the rat job! We're gonna try more compendia once #1749 goes out, but I don't expect that to be today and this big instance costs a lot of money so let's save money overnight!!
> Scale smasher back down because the rat job finished.

- api/data_refinery_api/views.py
close #1569 
It will be added under the field `generated_on` in the response.
> Add time when the cache was last busted

- api/data_refinery_api/views.py
> Include accession code on sample endpoint

- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/create_compendia.py
- workers/data_refinery_workers/processors/qn_reference.py
- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/smashing_utils.py
- workers/data_refinery_workers/processors/test_qn_reference.py
- workers/data_refinery_workers/processors/test_smasher.py
- workers/data_refinery_workers/processors/utils.py
#1258 
I found an optimization!!!! I think it's a pretty good one, should save 2 full copies of the data from being made. While I was in there I did some refactoring just because it was harder not to.
The changes I made could have some scientific implications, but my goal was that this shouldn't change the end result at all @jaclyn-taroni 
What we were doing:
* Copy the dataframe twice, once for RNA-seq and once for MA
* Delete RNA-seq columns from MA dataframe and vice versa
* Manipulate these new matrices to 
What we're doing now:
* Sort the dataframe by technology (actually before we've created it).
* Use slices so that we get views of the dataframe rather than a new copy.
- Refactor
WIP
> Refactor and improve some smasher/compendia code to reduce its memory footprint.

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
Undo #1754 except go big enough for 2 compendia!
> Rescale smasher to be big enough to run 2 compendia.

- workers/data_refinery_workers/processors/smashing_utils.py
#1764 
We skipped like 80% of the frames for rat, I can't figure out why. I'm hoping this makes figuring that out easier.
> Don't set maxtasksperchild and log more about each chunk

- workers/data_refinery_workers/processors/smashing_utils.py
> [HOTFIX] Deploy additional multiprocessing logs

- infrastructure/variables.tf
- workers/data_refinery_workers/processors/smashing_utils.py
> [HOTFIX] No compendia multiprocessing

- common/data_refinery_common/job_management.py
- common/data_refinery_common/models/models.py
- common/data_refinery_common/utils.py
- foreman/data_refinery_foreman/foreman/management/commands/create_missing_processor_jobs.py
- foreman/data_refinery_foreman/surveyor/test_end_to_end.py
- workers/data_refinery_workers/downloaders/array_express.py
N/A
Our tests seem to be broken, trying to fix them here.
Local tests
> Fix Main tests + small refactors

- workers/data_refinery_workers/processors/create_compendia.py
- workers/data_refinery_workers/processors/smashing_utils.py
N/A
We were not passing `job_context`
#1686  `pylint` 💯
> Discovered missing param in create compendia job

- workers/nomad-job-specs/create_compendia.nomad.tpl
#1258 
I made a bad typo. At least it explains the hanging we saw earlier today and again now.
\
> How big of a deal is one measley order of magnitude anyway?

- workers/data_refinery_workers/processors/smashing_utils.py
#1804 
I'm a bit embarassed about this one.
> Fix the way we build the matrices for compendia

- workers/data_refinery_workers/processors/smashing_utils.py
#1806 
We were doing checking whether these are None or not incorrectly.
> Fix the frame loop by checking for frame existence correctly

- workers/data_refinery_workers/processors/qn_reference.py
Tests are broken in master
_prepare_files moved to the smashing_utils, qn_reference didn't get updated.
> Fix QN tests

- common/data_refinery_common/message_queue.py
- foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py
- foreman/data_refinery_foreman/foreman/management/commands/test_create_compendia.py
- workers/data_refinery_workers/processors/create_quantpendia.py
#1751 
close #1816 
This was missing to call the quantpendia job correctly.
Trigger the command in the tests + test locally.
```
$ nomad status | grep QUANT
CREATE_QUANTPENDIA                               batch/parameterized  80        running  2019-10-21T14:24:26-04:00
CREATE_QUANTPENDIA/dispatch-1571683898-66a14629  batch                80        pending  2019-10-21T14:51:38-04:00
```
> Trigger quant-pendia job correctly

- workers/data_refinery_workers/processors/create_quantpendia.py
#1823 
Added additional logging in the quantpendia.
None
> Additional logging for quantpendia

- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/smashing_utils.py
N/A
Fix typo and remove unnecessary call
None
> Fix typo and remove unnecessary call

- workers/data_refinery_workers/processors/utils.py
close #1874 
Fix typo on `job.success`
None
> Fix typo and include context in ProcessorJobError

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1724 
We're ready to try the human compendia again. This gets the smasher up to an appropriate scale to do so.
> Scale smasher for compendia

- workers/data_refinery_workers/processors/create_quantpendia.py
https://github.com/alexslemonade/refinebio/issues/1823#issuecomment-552933457
When the quantpendia fails while creating the zip file we end up with an empty `ComputationalResult`.
This makes sure we only create the DB objects after everything is ready.
None
> Small refactor to avoid creating empty `ComputationalResults` in quantpendia

- common/data_refinery_common/job_lookup.py
- foreman/data_refinery_foreman/surveyor/external_source.py
- foreman/data_refinery_foreman/surveyor/geo.py
- foreman/data_refinery_foreman/surveyor/surveyor.py
close #1857 
We were assuming that all `OriginalFiles` in GEO were archives. However, some of them were `.CEL` files. This fixes this in the surveyor.
Tested surveying a sample locally.
> Detect archive files when surveying GEO samples

- foreman/data_refinery_foreman/foreman/management/commands/create_quantpendia.py
- foreman/data_refinery_foreman/foreman/management/commands/test_create_quantpendia.py
- workers/data_refinery_workers/processors/test_create_quantpendia.py
close #1887 
Split the query to calculate the quantpendia dataset, so that it doesn't timeout. 
Tested function in prod for `MUS_MUSCULUS`
> Modify how we create the dataset so it doesn't timeout

- workers/data_refinery_workers/processors/create_quantpendia.py
- workers/data_refinery_workers/processors/utils.py
#1823 
Cache the major steps for the quantpendia: downloading files, creating metadata, making the archive.
Wrote this with a decorator, do you think it's confusing like this @kurtwheeler?
Tested locally
> Additional caching for quantpendias

- infrastructure/variables.tf
- workers/data_refinery_workers/processors/smashing_utils.py
- workers/data_refinery_workers/processors/test_compendia.py
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1258 
Also scale down compendia and scale up the smasher.
> Skip QN for mouse compendia, cache ONLY mouse compendia

- foreman/data_refinery_foreman/foreman/management/commands/create_quantpendia.py
N/A
New option to for create quantpendia command.
> include all organisms

- workers/data_refinery_workers/processors/utils.py
> Don't retry ProcessorJobs without datasets

- common/data_refinery_common/migrations/0045_svd_algorithm.py
#1927 
This adds a migration to iterate over the `computed_files` and reassign the `svd_algorithm`
> add migration to correct svd attributes

- workers/data_refinery_workers/processors/smashing_utils.py
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1922 
I missed this line in my other PR :(
Not sure why the tests aren't testing this, I'm looking into that now.
I'm working on getting the unit tests to cover this still.
> Fix the smasher ferreal by removing reference to organism_name

- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1258 
Mouse compendium ran outta RAM. This about quadruples the RAM it has.
> Roughly quadruple RAM for mouse compendia.

- common/data_refinery_common/migrations/0046_compendium_version_number.py
- common/data_refinery_common/models/models.py
> Fix typo in migration and also fix a path issue in sync_from_s3.

- common/data_refinery_common/migrations/0046_compendium_version_number.py
- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/qn_reference.py
> [HOTFIX] Fix typo in migration

- workers/data_refinery_workers/processors/qn_reference.py
N/A related to trying to regenerate QN targets
We ran into:
```
File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 96, in inner
return func(*args, **kwargs)
psycopg2.OperationalError: cursor "_django_curs_140027036677888_1" does not exist
The above exception was the direct cause of the following exception:
File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1512, in cursor_iter
for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1512, in <lambda>
for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
File …
```
> Use our own queryset iterator avoid using a server side cursor.

- README.md
Also remove a now defunct option from compendia commands.
> Specify how to create QN targets for all organisms

- common/data_refinery_common/models/models.py
- workers/data_refinery_workers/processors/smasher.py
- workers/data_refinery_workers/processors/smashing_utils.py
#1838 
Modified the functions `process_frames_for_key` and `process_frames`
Ran test locally.
> A few additional refactors to simplify the process frame functions in the smasher

- workers/data_refinery_workers/processors/create_compendia.py
- workers/data_refinery_workers/processors/smashing_utils.py
> [HOTFIX] Fix _process_frames_for_key for compendia jobs

- workers/data_refinery_workers/processors/smashing_utils.py
- workers/nomad-job-specs/create_compendia.nomad.tpl
> [HOTFIX] Change size of Nomad compendia jobs

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#1258 
We did it!!! Now we don't need such an expensive smasher instance/disk!!!
> Scale smasher down to just large enough to run one smasher job at a time

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/data_refinery_workers/processors/smashing_utils.py
- workers/nomad-job-specs/create_compendia.nomad.tpl
> Scale smasher down to a sustainable size.

- common/data_refinery_common/migrations/0048_processorjob_abort.py
- common/data_refinery_common/migrations/0049_processorjob_abort_alter.py
https://github.com/AlexsLemonade/refinebio/pull/1991#issuecomment-565132889
Hopefully this will make it not fail.
Ran them locally.
> Split big migration into two

- api/requirements.in
- api/requirements.txt
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
Reverts AlexsLemonade/refinebio#2009
I wanted to let CI tests finish before merging, but then I went on autopilot and just clicked merge. This PR needs more work first.
> Revert "Bump django versions"

- api/requirements.in
- api/requirements.txt
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
Reverts AlexsLemonade/refinebio#2010
I didn't need to revert that. When I saw the tests fail it was actually a previous commit that I fixed before merging. My bad :(
> Revert "Revert "Bump django versions""

- foreman/data_refinery_foreman/surveyor/harmony.py
N/A
It looks like our surveyor's harmony code for SRA is merging two fields by accident because of a comma.
If this pull request has any implications for data or metadata processing or addresses an issue labeled `sci review`, please include an overview of the methods used (e.g., briefly explain _how_ the data gets processed). 
Include sufficient detail for reviewers or users that are not expert developers to evaluate the validity of the approach. 
Any pull request with a methods section requires scientific review in …
> SRA cell_type organismpart concat

- api/data_refinery_api/serializers.py
This is #2027 (fix unused imports) but using dev instead of master as a base 🤦‍♂ 
Fixes unused imports + changes one comparison to be `is not None`
N/A
> Fix Unused Imports

- api/data_refinery_api/views.py
- common/data_refinery_common/models/models.py
close #2032 
This fixes the engagement bot.
> Fix engagement bot

- api/data_refinery_api/views.py
[#820](https://github.com/AlexsLemonade/refinebio-frontend/issues/820)
Sorts prefetched samples' computational results by start time.
Tested on foreman.
> Sort prefetched computational results

- common/data_refinery_common/models/models.py
- common/data_refinery_common/rna_seq.py
- workers/data_refinery_workers/processors/salmon.py
#2054 
A few opportunities for improvement that I saw while trying to fix #2054.
None
> Some refactors for Salmon

- scripts/common.sh
#2053 
I think #2053 was opened before #2058 got merged and it somehow caused this file to get missed. I noticed it because of https://circleci.com/gh/AlexsLemonade/refinebio/29436
- Syntax
> Fix a line ending that got messed up by a merge-timeline or something.

- .pre-commit-config.yaml
N/A
The syntax test was failing on merge.
> pre-commit don't block commits on dev/master

- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/instances.tf
#2072 
Pass aws keys into the foreman scripts.
None
> Pass aws credentials into the foreman script

- common/data_refinery_common/models/organism.py
- foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
- foreman/data_refinery_foreman/surveyor/transcriptome_index.py
#1722 
https://github.com/AlexsLemonade/refinebio/issues/2087
There was an issue with organism names coming out of the processor job. I think it's because I tested this end-to-end with LEISHMANIA_MAJOR but only the surveying for ESCHERICHIA_COLI and ESCHERICHIA_COLI comes back from the ensembl API with some addtional junk in its organism name.
This fixes that issue by using the taxonomy_id that ensembl returns instead of the organism name, and then also by creating the organism object at surveyor time instead of waiting until the processor job to do it.
I created organism indices locally for E. coli:
```
id |     index_type      | source_version | assembly_name | salmon_version |                            absolute_directory_path …
```
> Fix creating transcriptome indices for bacteria

- foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
#2096 
I made some last minute changes to the tests and one of them got botched. Should have waited for the tests to pass. My bad :(
> I changed this line twice and it stopped making sense.

- foreman/data_refinery_foreman/foreman/main.py
N/A
Allows noop jobs should they fail potentially from OOM to be retried.
N/A
None.
> allow noop to have more ram

- api/requirements.in
- api/requirements.txt
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
#2139 
This handles the django updates and replaces:
* https://github.com/AlexsLemonade/refinebio/pull/2137
* https://github.com/AlexsLemonade/refinebio/pull/2136
* https://github.com/AlexsLemonade/refinebio/pull/2135
* https://github.com/AlexsLemonade/refinebio/pull/2134
> Bump django version in all sub-projects.

- README.md
- infrastructure/deploy_box_instance_data.sh
N/A Came up whilst deploying.
Not sure why this didn't come up during my staging test... Maybe I didn't test it properly or maybe I made additional changes after the staging test? Either way it's fixed now!
I made these changes live to get the prod stack back to working.
> The deploy was failing because of this, I fixed it live and this fixes it forever.

- infrastructure/variables.tf
I meant to include this in #2158 but github wasn't accepting pushes.
> The DATABASE_HOST needs to be the public IP so we can connect to it for dev deploys.

- api/data_refinery_api/serializers.py
- foreman/data_refinery_foreman/foreman/main.py
#2191 
This doesn't fix the issue with #2191, but I discovered these two bugs along the way and I need this endpoint fixed to fix my script.
I created transcriptome indices locally with these changes.
> Fix resizing of transcriptome jobs and add result_id to endpoint.

- infrastructure/instances.tf
#2200 
I should have done it before, but at least I remembered before kicking the job back off.
> Make smasher volume bigger.

- workers/data_refinery_workers/downloaders/sra.py
N/A
I have been trying to process several samples, all with similar original files and some of the SRA jobs are being OOM-Killed.
This uses a different method for the HTTP downloads, @kurtwheeler do you think this could be more stable? I got it from [here](https://stackoverflow.com/a/39217788/763705)
None
> Different HTTP download method

- infrastructure/instances.tf
Reverts AlexsLemonade/refinebio#2238
I'm going to file another PR increasing the volume size in `root_block_device`
> Revert "Use instance c5d.9xlarge for spot fleet with 900gb disk"

- common/data_refinery_common/utils.py
#2258 
mb -> MiB
Any pull request with a methods section requires scientific review in addition to code review.
- Bugfix …
> make size precise

- common/data_refinery_common/utils.py
#2254
http://masnun.com/2016/09/18/python-using-the-requests-module-to-download-large-files-efficiently.html
> iterate over response chunks

- common/data_refinery_common/utils.py
Test iterate over content when downloading files https://github.com/AlexsLemonade/refinebio/pull/2261
> [Hotfix] Deploy

- api/data_refinery_api/management/commands/post_downloads_summary.py
Fixes #2264 
I renamed the query from `is_new_user` to `is_returning_user` and swapped the if statement, since the query looks for previous downloads from the same email address, so it should actually be non-empty when the user is a *returning* user.
I also included more detailed download statistics like was mentioned in the first comment. `total_downloads` is calculated instead of using `annotation_queryset.count()` so that downloads are not counted if they come from an email associated with CCDL users.
I ran the frontend and the API locally and downloaded some datasets with different emails. I changed the webhook URL to point to …
> Fix EngagementBot's slack messages

- .circleci/remote_deploy.sh
#2291 
Sorry to keep spamming you with these, but I can't really test it any other way :(
> Remove out-of-date comment and wrap openssl key in quotes for bash.

- workers/data_refinery_workers/processors/smashing_utils.py
N/A Deepa asked a question and noticed the bug
We weren't updating this after filtering samples.
I actually haven't :/
> Fix how we calculate num_samples for compendia.

- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
#2291 
So it turned out that my last issue was that Nomad wasn't being started correctly. Not exactly sure why not.... but https://stackoverflow.com/a/51960034 suggests the error I'm seeing from monit could be fixed by this:
```
nomad' failed to start (exit status -1) -- no output
```
Even if it doesn't fix the issue, it does start when I run the script so we can actually deploy. (now that I think about it, I think this has been happening for a while. I've had to run the nomad script before. I think maybe we don't actually cycle the nomad instance frequently enough that it seemed like an all-the-time error before.)
None, it's gotta happen in the cloud.
> Maybe improve nomad startup script

- common/data_refinery_common/migrations/0056_auto_20200529_1230.py
N/A
I accidentally merged #2287 without updating the migration, so we had two leaf migrations.
The migrations now work again locally
> Fix migrations

- .circleci/remote_deploy.sh
N/A deploy is failing
It looks like our deploy box might have the same issue with the CA certs.
> Also fix the CA cert on the deploy box

- foreman/data_refinery_foreman/foreman/main.py
- foreman/data_refinery_foreman/surveyor/geo.py
- foreman/data_refinery_foreman/surveyor/test_end_to_end.py
- foreman/test_survey.sh
- workers/data_refinery_workers/processors/illumina.py
- workers/data_refinery_workers/processors/test_geo.py
Closes #2290
Closes #2288
We should now be able to process #2275 and #2274
Fix a bunch of bugs in our Illumina pipeline that were causing the requested samples to fail.
I processed the above requested samples successfully with all of the changes.
> Fix illumina bugs

- README.md
N/A
Added note about using pre-commit to main README and fixed small typo.
> Added note about pre-commit to README

- README.md
- api/data_refinery_api/serializers.py
- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
> [Deploy] accession code parameter for search endpoint

- api/data_refinery_api/serializers.py
- api/data_refinery_api/tests.py
- common/data_refinery_common/models/sample.py
Fixes https://github.com/AlexsLemonade/refinebio/issues/1871
Include experiment accessions in the sample detail view.
I added a unit test that failed before but now passed, and I ran the API locally to make sure.
> Add experiment accessions to the sample detail view

- api/data_refinery_api/tests.py
- api/data_refinery_api/views.py
- infrastructure/instances.tf
- scripts/run_es.sh
Fixes https://github.com/AlexsLemonade/refinebio/issues/2326
I had to extend FilteringFilterBackend to make it take parameters from `request.data` instead of `request.query_params`.
I added unit tests, which now pass, and I also verified that it works using `curl`.
> Modify /search to accept POST requests

- infrastructure/instances.tf
Debugging for https://github.com/AlexsLemonade/refinebio/issues/2342
Temporarily add x1e.4xlarge to the spot fleet so we can use a smaller instance to debug why the jobs are looping.
> Temporarily add x1e.4xlarge for debugging

- infrastructure/instances.tf
- infrastructure/permissions.tf
N/A
Our infrastructure was failing to be recreated with
```
Error: aws_spot_fleet_request.cheap_ram: resource depends on non-existent resource 'aws_ebs_volume.data_refinery_ebs'
Error: resource 'aws_iam_policy.ec2_access_policy' config: unknown resource 'aws_ebs_volume.data_refinery_ebs' referenced in variable aws_ebs_volume.data_refinery_ebs.*.id
```
so I commented out these references.
Include sufficient detail for reviewers or users that are not expert developers to evaluate the validity of …
> Whoops, missed some references to EBS

- README.md
N/A, we forgot to do this recently when David got a new GPG key. 
Just updating the readme.
> Add a couple lines to README about keys/

- infrastructure/permissions.tf
N/A deploy was failing
I changed some more things in the terraform config and made sure they worked by spinning up a dev stack.
Any pull request with a methods section requires …
> Actually fix terraform this time

- api/data_refinery_api/urls.py
N/A I just found it while testing locally
Not sure why our tests didn't catch it until I made changes but we were missing an import in `urls.py`.
> Add missing import in URLs file

- .circleci/remote_deploy.sh
The deploy broke
We didn't quote all of the environment variables so when one of them had a bash control character the deploy broke.
> Fix our deploy

- .circleci/remote_deploy.sh
- .circleci/run_terraform.sh
- .circleci/update_docker_img.sh
- .circleci/upload_test_coverage.sh
Our deploy broke
More fixes, my bad.
I ran shellcheck on the .circleci directory and now it doesn't warn about unquoted variables any more.
> Fix quoting issues in our deploy scripts part 2

- .circleci/remote_deploy.sh
Deploy still broken
Switch to using a HEREDOC and single quotes instead of echo and double quotes.
I ran the changed line real quick and made sure the generated `env_vars` file looked right.
> Use single quotes in the env_vars file instead

- infrastructure/variables.tf
Deploy is still broken.
This time it was a typo in `variables.tf`
I ran a staging deploy to make sure that the file was formatted correctly. I wonder if we can add another pre-commit hook for our terraform files.
> Fix typo in variables.tf

- .circleci/remote_deploy.sh
- infrastructure/variables.tf
> Fix deploy finally/hopefully

- api/data_refinery_api/views/stats.py
#2371
I split out the stats code more so that if you pass `?dashboard=true` to `/stats/`, it excludes all of the stats that are not on the dashboard. From the profile I took, the rough estimate is that this should result in the dashboard being ~2x faster to load once we update the frontend, but I'll keep testing once this gets deployed.
I ran the frontend locally, patched it to send `?dashboard=true`, and made sure that none of my changes broke the dashboard.
> Tweaks to improve dashboard performance

- workers/data_refinery_workers/processors/salmon.py
https://github.com/AlexsLemonade/refinebio/pull/2394#issuecomment-655655430
Add a comment for our future selves explaining why we are preferring annotations to `sra-stat`.
> Add a comment explaining why we prefer annotations

- infrastructure/deploy.sh
N/A deploy failed for :candle: the last time
Shellcheck had a false positive on one of our scripts.
Any pull request with a methods section requires scientific review in addition …
> Fix quoting issue in deploy script

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/pg-bouncer-instance-user-data.tpl.sh
None
It turns out that these are not shell variables, they are format specifiers for terraform. I'll document this when I fix it.
Any pull request with a methods section requires …
> Rollback some of the shellcheck fixes

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/deploy.sh
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/pg-bouncer-instance-user-data.tpl.sh
> [HOTFIX] Rollback some breaking script improvements

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/pg-bouncer-instance-user-data.tpl.sh
None, tests are failing
We had to roll back some of the shellcheck fixes because they broke our deploy. Here's the fixes done correctly.
> Fix the lint errors caused by the rollback

- infrastructure/instances.tf
Deploying
Apparently the AMI's name is actually `ubuntu-18-04-docker`.
> The AMI name has 18-04, not 18.04

- api/data_refinery_api/urls.py
Fixes https://github.com/AlexsLemonade/refinebio/issues/2391
We were missing another import.
I ran the API locally with debug off, and it gave me a 500 error hitting `localhost:8000/samples`. Then I fixed the import and hitting `localhost:8000/samples` again gave me a 404 with the correct error message.
> Fix 404 handler

- infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
- infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
- scripts/install_nomad.sh
None, nomad is being weird on prod
Let's try upgrading nomad and disabling the killer
I manually upgraded nomad on a spot instance and it still worked.
> Some nomad fixes

- api/data_refinery_api/views/api_token.py
Piggy back on #2425 to make sure our docs link to the materials one agrees to.
The lawyers who advised us wanted accepting to be an affirmative state instead of a default state if data were being downloaded, so this makes things clear via the API docs, which is how one would encounter the token materials. …
> make explicit the T&C + privacy policy

- workers/data_refinery_workers/processors/smashing_utils.py
- workers/data_refinery_workers/processors/test_smasher.py
- workers/run_tests.sh
#2191 
Since the quant.sf files that were causing issues are the ones that are missing their headers, let's filter out files that are missing the correct header.
I added a new quant test file that is one of the truncated files from our human quantpendia and modified the quant.sf only smash test to make sure it was filtered.
> Filter truncated quant.sf files

- infrastructure/nomad-configuration/nomad-server.service
None, noticed it on my devstack
Fix the description for the nomad server service, it still said "client".
Made the change on my devstack and it still works.
> Fix description for nomad server systemd unit

- .gitignore
None, came up when I was deploying the dev stack
Ignore the environment files from a deploy. Otherwise we might accidentally check in secrets after testing on a dev stack.
The files no longer show up in my `git status`.
> Ignore terraform environment files

- api/data_refinery_api/tests.py
- api/data_refinery_api/views/dataset.py
Fixes #2443
The datasets were all failing because they had accessions that are not available on refine.bio. This happened because our validation code only checked samples that existed.
Also, some of them were missing email addresses because we (implicitly) allowed empty email addresses in our validation code.
All of the tests that I added originally failed and now they all pass.
> More dataset validation

- api/data_refinery_api/tests.py
- api/data_refinery_api/urls.py
- api/data_refinery_api/views/__init__.py
- api/data_refinery_api/views/api_token.py
Fixes #2423
Make the same changes I made to the dataset endpoint so we don't have two separate views for creating and updating API keys.
I added a test to verify that both the old and the new way of getting API keys works.
> Refactor the token API endpoint

- api/data_refinery_api/tests.py
None, tests are failing on master
In https://github.com/AlexsLemonade/refinebio/pull/2425 I refactored how we got API tokens in our tests, but in another PR I added a new dataset test that did not have these changes, so when we merged both of them the tests began failing.
API tests now pass locally
> Fix new API test

- api/data_refinery_api/tests.py
Tests failing on deploy PR
Fix the black issue
> Make black happy

- foreman/data_refinery_foreman/foreman/management/commands/update_experiment_metadata.py
- foreman/data_refinery_foreman/foreman/management/commands/update_sample_metadata.py
None, came up because we wanted to run it
Actually use the paginator in the management command. This would explain why it took so long to run before.
Tests still pass
> Fix pagination in management commands

- api/data_refinery_api/tests.py
- foreman/data_refinery_foreman/foreman/management/commands/update_experiment_metadata.py
- foreman/data_refinery_foreman/foreman/management/commands/update_sample_metadata.py
- workers/data_refinery_workers/downloaders/sra.py
> Deploy fix for pagination and missing import

- api/data_refinery_api/views/organism.py
N/A
The organisms_read endpoint says that it retrieves an organism by ID but it retrieves by organism name so that has been changed
> Fixed typo for organism read API

- api/data_refinery_api/views/transcriptome_index.py
https://github.com/AlexsLemonade/refinebio/issues/2459
When I profiled this API endpoint, we were spending 262s (profiler time, not necessarily accurate, but a large portion of the total time) inside of `ComputationalResult`'s `__str__` method, but we are only trying to filter based on `result_id`. For some reason `django_filters` lets us down, so let's just filter this one manually.
The `transcriptome_index` endpoint still works locally and all of the tests still pass.
> Just filter  ourselves

- api/data_refinery_api/management/commands/post_downloads_summary.py
From Slack
Add `@ccdatalab.org` to the list of email addresses we ignore (and fix a typo in the comment).
None
> Ignore @ccdatalab.org emails in downloads summary

- DEBUGGING.md
N/A
Add a few debugging tips. These are all things I wrote for debugging the failing processor jobs.
I am opening this as a draft PR in case I come up with more before we finish getting the processors back up and running.
- More documentation
> Added a few debugging tips

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
Lots of compendia issues
Scale up the smasher so we can rerun the compendia. I just copied the changes from https://github.com/AlexsLemonade/refinebio/pull/2219
> Scale up the smasher

- foreman/data_refinery_foreman/surveyor/sra.py
- foreman/data_refinery_foreman/surveyor/test_sra.py
- test_volume/cassettes/surveyor.sra.arrayexpress_alternate_accession.yaml
Fixes https://github.com/AlexsLemonade/refinebio/issues/2488
Now we check for ArrayExpress accessions too when surveying SRA samples.
I added a test that surveys an ENA experiment.
> Detect alternate accessions for ENA experiments

- infrastructure/instances.tf
- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#2368 and other compendia issues
I want to kick off the quantpendia jobs for human and mouse, and then throw all the rest of the compendia jobs on top.
- Infrastructure tuning
> Tweak sizes for next processing goals.

- workers/data_refinery_workers/processors/smasher.py
#2061 
Added a BCC to the email that is sent when smasher runs (I wrote "fails" in commit message but that was an accident)
None
> BCC Slack email when smasher runs

- .github/workflows/config.yml
#2504 
It seemed to be implied this would happen by default...
> I guess I have to provide GITHUB_WORKSPACE like this?

- .github/scripts/git_decrypt.sh
- .github/scripts/remote_deploy.sh
#2508 
I was trying to avoid completely hardcoding it. That was a mistake.
> Github actions makes filepaths hard

- .github/scripts/git_decrypt.sh
- .github/scripts/remote_deploy.sh
- .github/workflows/config.yml
#2510 
We'll see, but I think maybe just assuming they dropped us in the correct place will be for the best.
> I think I might have gotten it?

- .github/workflows/config.yml
#2512 
Seems like what's provided as the tag is different than expected. This might compensate for that
> Fix tag manipulation.

- .github/scripts/run_terraform.sh
- scripts/common.sh
#2351  Issue Number
#2514 
I missed this env var in a couple places. This fixes that, and maybe the deploys?
> I think this is what is wrong with the deploy. I found it cause I was curious.

- infrastructure/deploy_box_instance_data.sh
- infrastructure/instances.tf
> Deploy bigger smasher disk

- infrastructure/instances.tf
- infrastructure/variables.tf
> Turn the smasher on down

- README.md
N/A David asked and it wasn't here.
Adds instructions for running API locally to README.md.
> Update README with how to run the API locally.

- api/data_refinery_api/exceptions.py
- api/data_refinery_api/settings.py
- api/data_refinery_api/test/test_api_general.py
- api/data_refinery_api/utils.py
- api/data_refinery_api/views/compendium_result.py
- api/data_refinery_api/views/computational_result.py
- api/data_refinery_api/views/computed_file.py
- api/data_refinery_api/views/experiment.py
- api/data_refinery_api/views/original_file.py
- api/data_refinery_api/views/sample.py
- api/data_refinery_api/views/transcriptome_index.py
- common/data_refinery_common/utils.py
#2560 
Validate filters and return a nice error message if invalid filters have been provided.
Any pull request with a methods section requires scientific review in addition to …
> Validate Filters

- infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
#2565 
I think this will fix auto mounting of the EBS volume.
- Devops
> Add small sleep to allow EBS volume to be attached.

- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
- workers/nomad-job-specs/create_quantpendia.nomad.tpl
Hmm, not sure which is most appropriate. We want to rerun compendia though.
This makes the smasher and compendia job settings large enough to run human/mouse compendia jobs.
- Devops
> Reset quantpendia RAM, up compendia RAM, increase smasher size.

- infrastructure/variables.tf
- workers/nomad-job-specs/create_compendia.nomad.tpl
#2484 
This gets us back to running lean!
- Devops
> Scale down now that we're done with compendia.

- api/data_refinery_api/views/original_file.py
- infrastructure/variables.tf
> [HOTFIX] Fix prod volume size issue

- api/data_refinery_api/views/jobs/downloader_job.py
- api/data_refinery_api/views/jobs/processor_job.py
- api/data_refinery_api/views/jobs/survey_job.py
#2560 
Validate filters for job endpoints
Any pull request with a methods section requires scientific review in addition to code review.
What types of changes does your code …
> Validate Filters for Job Endpoints

- workers/qn_dependencies.R
#2458 
I'm unsure why this didn't fail during the tests...
I can build the image locally.
> Fix R dependencies for smasher image.

- .github/scripts/install_terraform.sh
- .github/workflows/config.yml
- infrastructure/deploy.sh
#2588 
Also silence an error that is ok.
I want to also upgrade to the latest version of the AWS provider in a subsequent PR.
- Upgrade
I was able to deploy successfully with these changes.
> Upgrade to latest version of terraform: 0.13.5

- api/data_refinery_api/exceptions.py
- api/data_refinery_api/test/test_api_general.py
- api/data_refinery_api/test/test_dataset.py
- api/data_refinery_api/views/compendium_result.py
- api/data_refinery_api/views/computational_result.py
- api/data_refinery_api/views/computed_file.py
- api/data_refinery_api/views/dataset.py
- api/data_refinery_api/views/experiment.py
- api/data_refinery_api/views/experiment_document.py
- api/data_refinery_api/views/jobs/downloader_job.py
- api/data_refinery_api/views/jobs/processor_job.py
- api/data_refinery_api/views/jobs/survey_job.py
- api/data_refinery_api/views/original_file.py
- api/data_refinery_api/views/sample.py
- api/data_refinery_api/views/transcriptome_index.py
#2546 
Standardize errors returned by the api so that they can be easily parsed and handled in client applications.
single validation error handling:
http://localhost:8000/v1/samples/?organism=bad
<details><summary>response</summary>
<p>
```json
{
"error_type": "invalid_choice",
"message": "Select a valid choice. That choice is not one of the available choices.",
"details": "organism"
}
```
</p>
</details>
multiple validation error handling:
http://localhost:8000/v1/samples/?organism=bad&age=no
<details><summary>response</summary> …
> Standardize Errors

- workers/affymetrix_dependencies.R
#2603 
Looks like SCAN.UPC is failing to install. I think I need to run a staging deploy to update the cached image.
I haven't finished building the image yet, but it gets farther and I don't want to wait 6 hours for it to build before starting to build it on the deploy box.
> Fix affy image better

- .dockerignore
- config/externally_supplied_metadata/metasra/translate.py
- config/externally_supplied_metadata/metasra/translate.sh
- foreman/data_refinery_foreman/foreman/management/commands/import_external_sample_attributes.py
#2491 
We specified a slightly different format here https://github.com/AlexsLemonade/refinebio/issues/2127#issuecomment-591651893 than we had in our own data. This fixes by fixing the `translate.py` script.
I've run 
```
./foreman/run_surveyor.sh import_external_sample_attributes --source-name=MetaSRA --methods-url='https://github.com/AlexsLemonade/refinebio/pull/2491'  --file config/externally_supplied_metadata/metasra/metasra_translated.json
```
and
```
./foreman/run_surveyor.sh import_external_sample_keywords --source-name=MetaSRA --methods-url='https://github.com/AlexsLemonade/refinebio/pull/2491'  --file config/externally_supplied_metadata/metasra/metasra_keywords.json
```
with no errors!
> Fix formatting of Metasra data for loading in

- infrastructure/instances.tf
#2582 
I know that issue says version 12, but the Preferred Upgrade Target for our current version is 11.1 as per https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion.Process. If we want to go up to 12 we can do so in a subsequent PR.
This ought to do the trick, for starters. It leaves some things that will have to be cleaned up though. Upgrading the version requires a new parameter group and they cannot be destroyed and then created because apparently there's a super ultra secret backup copy of the RDS instance that's made that still uses for some number of hours. I read 30 minutes, but I waited hours and it was still failing. Then I tried it the next morning and it worked.
What that means is that …
> Upgrade to Postgres 11

- api/data_refinery_api/middleware.py
- api/data_refinery_api/pagination.py
- api/data_refinery_api/settings.py
- api/data_refinery_api/test/test_api_general.py
- api/data_refinery_api/test/test_dataset.py
- api/data_refinery_api/test/test_search.py
- api/data_refinery_api/views/sample.py
- infrastructure/api-configuration/nginx_config.conf
https://github.com/AlexsLemonade/refinebio/issues/2659
https://github.com/AlexsLemonade/refinebio/issues/2663
I haven't been able to reproduce that 404 issue but it seems like if we don't have the html setup for nginx that we should just remove the custom config, especially since we don't even have a custom page.
The throttling doesn't seem to work but I can't figure out why not. It seems like it should be set up correctly according to https://www.django-rest-framework.org/api-guide/throttling/#throttling and we already have a cache table setup in our DB so I'm not sure what's going on...
In addition to unit tests I used the following script to test this:
```python
import multiprocessing
import requests
url = …
```
> API stability improvements

- .pre-commit-config.yaml
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/instances.tf
- infrastructure/variables.tf
https://github.com/AlexsLemonade/refinebio/pull/2601
This removes the Nomad instances now that jobs can complete on Batch.
As promised, this reenables the terraform precommit check!
Same tests as https://github.com/AlexsLemonade/refinebio/pull/2601!
> Remove configuration for nomad instances.

- .github/FUNDING.yml
N/A I saw this on https://github.com/AlexsLemonade/training-modules/ and wanted one!
Copied from https://github.com/AlexsLemonade/training-modules/blob/master/.github/FUNDING.yml
> Setup sponsor button for repo.

- api/requirements.in
- api/requirements.txt
- common/data_refinery_common/models/computational_result_annotation.py
- common/data_refinery_common/models/dataset.py
- common/data_refinery_common/models/dataset_annotation.py
- common/data_refinery_common/models/experiment.py
- common/data_refinery_common/models/experiment_annotation.py
- common/data_refinery_common/models/jobs/downloader_job.py
- common/data_refinery_common/models/jobs/processor_job.py
- common/data_refinery_common/models/jobs/survey_job.py
- common/data_refinery_common/models/processor.py
- common/data_refinery_common/models/sample.py
- common/data_refinery_common/models/sample_annotation.py
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
https://github.com/AlexsLemonade/refinebio/pull/2688
https://github.com/AlexsLemonade/refinebio/pull/2687
https://github.com/AlexsLemonade/refinebio/pull/2686
https://github.com/AlexsLemonade/refinebio/pull/2685
https://github.com/AlexsLemonade/refinebio/pull/2684
https://github.com/AlexsLemonade/refinebio/pull/2683
https://github.com/AlexsLemonade/refinebio/pull/2682
Do all these PRs the right way in one shot.
> Update dependencies based on dependabot suggestions.

- api/data_refinery_api/test/test_api_general.py
#2717 
I forgot there was a unit test for it.
- Testing
Unit tests!
> Fix test that changing throttles broke.

- api/data_refinery_api/test/test_api_general.py
#2718 
I merged too quick, it didn't actually fix it. This does.
> Actually fix throttling test

- .github/scripts/remote_deploy.sh
- .github/workflows/config.yml
#2720 
I broke the tests with #2720. This fixes them by properly signing into docker. I've also since set the registry access in the packages which was important.
The unit tests pass again!! I want to try a staging deploy now!
> Fix signing into GHCR

- .github/workflows/config.yml
https://github.com/AlexsLemonade/refinebio/pull/2720
Add INSTANCE_SSH_KEY to the github actions env.
> Pass github actions env var through

- common/data_refinery_common/models/jobs/downloader_job.py
- common/data_refinery_common/models/jobs/job_managers.py
- common/data_refinery_common/models/jobs/survey_job.py
- foreman/data_refinery_foreman/foreman/downloader_job_manager.py
- foreman/data_refinery_foreman/foreman/job_control.py
- foreman/data_refinery_foreman/foreman/job_requeuing.py
- foreman/data_refinery_foreman/foreman/survey_job_manager.py
- foreman/data_refinery_foreman/surveyor/geo.py
- foreman/data_refinery_foreman/surveyor/management/commands/surveyor_dispatcher.py
- foreman/requirements.in
- foreman/requirements.txt
- scripts/format_batch_with_env.sh
#2584
This is a stepping stone to end to end tests. This makes tracking jobs a bit easier, and doesn't waste a retry on nonsense.
This also includes a fix to the GEO downloader. This required tweaking the RAM amount for its jobs.
I've tested this with my end to end tests that will be coming in a following PR.
> Requeue unqueued jobs rather than recreating them and fix GEO downloader

- infrastructure/batch/compute.tf
- infrastructure/batch/launch_templates.tf
- infrastructure/batch/roles.tf
- infrastructure/deploy.sh
- infrastructure/deregister_batch_job_definitions.py
- infrastructure/disk.tf
- infrastructure/instance-ecs-agent.config
- infrastructure/policies.tf
- infrastructure/workers-configuration/workers-instance-user-data.tpl.sh
- scripts/kill_all_jobs.py
- scripts/kill_all_jobs.sh
#2584 
While working on end to end tests I had to make a lot of changes to terraform configs and the way we configure ECS in order to get all the jobs to run correctly and quickly. I also wrote some scripts to help along the way. I also improved the deploy process more.
I tested this with my end to end tests that will be coming in a following PR.
> Tune ECS for AWS Batch, add convenience scripts

- infrastructure/environments/staging.tfvars
#2734 
I want to make sure the smasher smashes, I will reset this after.
> Set full stack to true to make sure staging stack is lookin good.

- infrastructure/environments/staging.tfvars
#2735 
Undoes full stack for staging.
> Revert staging instance back to full_stack=false

- infrastructure/batch.tf
- infrastructure/batch/compute.tf
- infrastructure/batch/job_queue.tf
- infrastructure/batch/variables.tf
- infrastructure/disk.tf
- infrastructure/instances.tf
- infrastructure/logging.tf
- infrastructure/networking.tf
- infrastructure/permissions.tf
- infrastructure/security.tf
- infrastructure/variables.tf
#2704 
This adds a bunch of tags with `team=engineering` and `project=refine.bio`.
I've deployed this to a dev stack and it wroked second try!
> Tag AWS resources with team and project

- .github/workflows/config.yml
- common/README.md
- scripts/update_models.sh
- scripts/update_my_docker_images.sh
- workers/data_refinery_workers/downloaders/test_sra.py
- workers/data_refinery_workers/processors/test_transcriptome_index.py
N/A
Fixing some small bugs that I ran into while trying to get the tests running on my machine. It looks like there was a bug in the transcriptome tests that wasn't caught because we have them disabled, so I fixed that. Also, on my machine
```
$ readlink -f /usr/bin/python
/usr/bin/python2.7
```
so I had a couple issues running tests until I replaced `python ...` with `python3 ...`.
The transcriptome tests pass locally and the other tests were able to start running.
> Small Fixes for Test Bugs

- workers/dockerfiles/Dockerfile.compendia
N/A came up while working on revamping the tests.
I cherrypicked this commit from my changes so we can get it merged and fix the tests.
Tensorflow updated, and the new version was incompatible with fancyimpute, so I had to freeze tensorflow at 2.4.1.
All the tests pass now for the compendia.
> Fix the compendia tests

- workers/data_refinery_workers/processors/test_qn_reference.py
- workers/dockerfiles/Dockerfile.compendia
Related to #2749
It looks like we had one other import that was wrong, which caused the QN tests to fail.
The QN tests now pass locally.
> Fix an import in the QN tests

- api/data_refinery_api/settings.py
- api/data_refinery_api/test/test_compendia.py
- api/requirements.in
- api/requirements.txt
- common/data_refinery_common/performant_pagination/runtests/settings.py
- common/data_refinery_common/settings.py
- common/requirements.in
- common/requirements.txt
- foreman/data_refinery_foreman/settings.py
- foreman/requirements.in
- foreman/requirements.txt
- scripts/update_models.sh
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
- workers/data_refinery_workers/settings.py
#2708
#2707
#2706 
#2705
#2704
#2695
#2694
#2693
Update dependencies.
> Bump versions of django and pyyaml up.

- .github/scripts/install_terraform.sh
- .github/scripts/run_terraform.sh
Fix deploy for #2601 
Also remove unused file that made me think I already had.
Describe the big picture of your changes.
> Install correct version of terraform

- infrastructure/deploy.sh
Fix the ordering of things even better... It needs to be create job definitons, deregister, and THEN reregister.
Also sets the AWS_DEFAULT_REGION env var for the AWS CLI.
> A few tweaks to the deploy script to get things working

- api/data_refinery_api/test/test_stats.py
- api/data_refinery_api/views/stats.py
- codecov.yml
Fixes https://github.com/AlexsLemonade/refinebio/issues/2701
Query batch for the stats endpoint.
I feel like this is really slow, but from the comments on @kurtwheeler's other PR it looks like what I am doing is the fastest way to get all of the information that we need from Batch, so we might just have to deal with it.
I ran the API with my changes locally pointed at my devstack and made sure that everything worked before spinning the devstack down.
> Add Batch info to the `/stats` endpoint

- common/data_refinery_common/models/dataset.py
- foreman/data_refinery_foreman/foreman/test_end_to_end.py
Not sure, came up during https://github.com/AlexsLemonade/refinebio/actions/runs/991049749
Only query for samples related to experiments surveyed by the end to end tests since staging has so many samples.
The end to end tests pass locally for me (well at least they make it part-way through the final downloader jobs before ENA ruins them).
> Fix end to end tests in staging

- .gitignore
- README.md
- infrastructure/destroy_terraform.sh
- scripts/install_all.sh
Fixes https://github.com/AlexsLemonade/refinebio/issues/2810
Fixes https://github.com/AlexsLemonade/refinebio/issues/2808
There were some little issues with scripts and our gitignore that I found while deploying and tearing down a devstack. I also updated the README with some of the things I figured out while deploying.
I successfully deployed and tore down a devstack
> Fix some issues I found while deploying a devstack

- infrastructure/instances.tf
#2739 
I missed these before. Noticed a large percentage of our untagged costs were coming from RDS and found these!
- Infrastructure tagging
I deployed a dev stack with these to make sure it was a valid configuration.
> Tag database instance and parameter group.

- scripts/calculate_ram_hours.py
#2815 
I made these changes to calculate cost for GSE85217 
- Script improvement
I calculated RAM hours for GSE85217 and added it to a spreadsheet. Looks pretty good
> Update calculate_ram_hours to output TSV and work for entire experiments

- infrastructure/deploy.sh
- infrastructure/instances.tf
#2832 
While testing staging I noticed that I need this flag. I think this one is probably good as a permanent change because we already have downtime during deploys so we may as well change the DB then.
I've spun up a dev stack with the changes to make sure they're valid.
> Apply db password change immediately

- foreman/data_refinery_foreman/surveyor/array_express.py
- foreman/data_refinery_foreman/surveyor/geo.py
- foreman/data_refinery_foreman/surveyor/harmony.py
- foreman/data_refinery_foreman/surveyor/sra.py
- foreman/data_refinery_foreman/surveyor/test_geo.py
- foreman/data_refinery_foreman/surveyor/test_harmony.py
- workers/batch-job-templates/illumina.tpl.json
#2828 
Try to make the harmonizer more reliable, readable, and maintainable. Also try to address the issue https://github.com/AlexsLemonade/refinebio/pull/2807 was trying to fix.
I was able to change the GEO and SRA surveyors to harmonize the metadata sample by sample, which should eliminate the kind of mismatch errors that could exist before. Array express can't be done that way because we're combining two different responses, metadata from one and file data from the other.
- refactor, bug fixes
Unit tests are passing! I added one for the experiment that wouldn't survey before
> Refactor harmonizer

- foreman/data_refinery_foreman/foreman/management/commands/create_missing_processor_jobs.py
- foreman/data_refinery_foreman/foreman/utils.py
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
Updates job cutoff date to yesterday.
- bugfix
I'll test this on staging, but really I also need to test it production. I need to make sure in both places it doesn't queue jobs it doesn't, because before I disabled it, it was queuing a lot of jobs repeatedly costing money.
> Adds a cutoff to the job filler and reenables it

- foreman/data_refinery_foreman/foreman/management/commands/generate_dataset_report.py
Yum yums
This will be useful in the future, although I'll need to modify it a bit for next quarter.
> Adds a management command for building a chart to show dataset downloads

- foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py
- workers/data_refinery_workers/processors/create_compendia.py
- workers/data_refinery_workers/processors/test_compendia.py
- workers/data_refinery_workers/processors/test_create_quantpendia.py
- workers/data_refinery_workers/processors/testing_utils.py
Fixes https://github.com/AlexsLemonade/refinebio/issues/2849
Add some more tests to the compendia:
- Make sure that we can smash with microarray data only
- The comments in `create_compendia.py` indicate that it was designed to do this, but we never verified that it still worked
- Check that we drop rows correctly when their row sums are in the < 10th percentile
- Check that we drop samples correctly when there is >50% missing observations
- Try removing some values and performing imputation, and verify that the results are close to expected
- Check that QN is skipped for quantpendia by checking the output metadata
The one thing I would like some science input on is the imputation testing. I picked 3 entries to set to NA, which I do here: …
> Compendia Test Improvements

- .dockerignore
- .gitignore
- config/externally_supplied_metadata/metasra/README.md
- config/externally_supplied_metadata/metasra/filter_accessions.awk
- config/externally_supplied_metadata/metasra/translate.py
- config/externally_supplied_metadata/metasra/translate.sh
Related to https://github.com/AlexsLemonade/refinebio/issues/2868
Fixes https://github.com/AlexsLemonade/refinebio/issues/2890
Fixes a couple of things in the MetaSRA importer that needed to be done before importing. Also adds some documentation about how to import new MetaSRA data.
Everything works now and I was able to import the MetaSRA data. It did fail, but not because of any of the code I changed here.
> Fix some stuff in the MetaSRA importer

- common/data_refinery_common/message_queue.py
- infrastructure/networking.tf
We should probably have an issue, but we've just been working off an email AWS sent about our cert being unable to renew
This hopefully will allow our cert to renew.
Can't really test without at least staging.
> Fix the ACM certs and also remove a debugging log.

- common/data_refinery_common/message_queue.py
- infrastructure/networking.tf
> Add lifecycle to ACM cert in terrafomr 

- infrastructure/networking.tf
https://github.com/AlexsLemonade/refinebio/pull/2913
This has broken the deploy. We're just trying to get things back to working.
> Revert ACM change to try to fix deploy.

- infrastructure/networking.tf
https://github.com/AlexsLemonade/refinebio/pull/2921
> Revert ACM change to try to fix deploy

- .github/workflows/combine-prs.yml
https://github.com/AlexsLemonade/refinebio/pull/2920
https://github.com/AlexsLemonade/refinebio/pull/2918
https://github.com/AlexsLemonade/refinebio/pull/2917
https://github.com/AlexsLemonade/refinebio/pull/2916
https://github.com/AlexsLemonade/refinebio/pull/2915
https://github.com/AlexsLemonade/refinebio/pull/2909
I wanna merge all these together automatically. This gives me a button to do so.
> Add workflow to combine dependabot PRs.

- infrastructure/batch/compute.tf
- workers/batch-job-templates/create_compendia.tpl.json
- workers/batch-job-templates/create_quantpendia.tpl.json
> Deploy timeout increase for compendia jobs

- workers/data_refinery_workers/processors/smashing_utils.py
Compendia
This is attempting to prevent this error:
```
File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.QueryCanceled: canceling statement due to statement timeout
The above exception was the direct cause of the following exception:
File "/home/user/data_refinery_workers/processors/utils.py", line 387, in run_pipeline
last_result = processor(last_result)
File "/home/user/data_refinery_workers/processors/smashing_utils.py", line 685, in write_non_data_fil
job_context["metadata"] = compile_metadata(job_context)
File "/home/user/data_refinery_workers/processors/smashing_utils.py", line 649, in compile_metadata
for sample …
```
> Paginate iteration of samples in dataset

- api/requirements.in
- api/requirements.txt
- common/requirements.in
- common/requirements.txt
- foreman/requirements.in
- foreman/requirements.txt
- workers/data_refinery_workers/downloaders/requirements.in
- workers/data_refinery_workers/downloaders/requirements.txt
- workers/data_refinery_workers/processors/requirements.in
- workers/data_refinery_workers/processors/requirements.txt
#2937
#2938
#2939 
#2940 
#2941
Bump the deps based on dependabot's suggestions.
> Combine dep bumps and do 'em right.

- infrastructure/batch/compute.tf
- infrastructure/batch/launch_templates.tf
- infrastructure/deploy.sh
#2945 
While running compendia I saw:
```
2021-10-03 14:57:54,739 i-0cd9f0cf2335b98e3 data_refinery_workers.processors.create_compendia DEBUG [to
2021-10-03 22:53:57,993 i-0cd9f0cf2335b98e3 data_refinery_workers.processors.utils ERROR [no_retry: Fal
File "/usr/lib/python3.6/zipfile.py", line 1646, in write
shutil.copyfileobj(src, dest, 1024*8)
File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
fdst.write(buf)
File "/usr/lib/python3.6/zipfile.py", line 1015, in write
self._fileobj.write(data)
OSError: [Errno 28] No space left on device
During handling of the above exception, another exception occurred:
File "/usr/lib/python3.6/shutil.py", line 704, in _make_zipfile
zf.write(path, path)
File …
```
> Make compendia use a larger volume. Make everything else's volume a lil smaller

- infrastructure/batch/launch_templates.tf
#2947 
These changes were supposed to be in that last PR. I had to change this to get the deploy to work, but I forgot to commit the changes.
I tested this for the last PR, just forgot these tweaks.
> Give unique names for launch templates.

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/disk.tf
- infrastructure/instances.tf
- infrastructure/permissions.tf
- infrastructure/policies.tf
https://github.com/AlexsLemonade/scpca-portal/pull/109
Same idea, but for this project!
I will test this in a dev stack tomorrow to make sure the terraform is legit, then in staging.
> Add cert bucket and policy, and then change API startup script to use it

- foreman/run_end_to_end_tests.sh
- infrastructure/deploy.sh
- infrastructure/workers-configuration/pg-bouncer-instance-user-data.tpl.sh
N/A came up while going through deploy processes
We haven't been doing this since we switched over to AWS Batch, but we should. However staging and dev still need access to the database to test end to end tests.
I am testing this in a dev stack, then will test with a staging deploy.
> Remove CI ingress for production environment.

- infrastructure/batch/launch_templates.tf
https://github.com/AlexsLemonade/refinebio/issues/2822
This tags the EBS volumes for the Batch instances!
I've tested this in a dev stack!
> Tag Batch instances and volumes.

- api/data_refinery_api/views/stats.py
This will close 2 issues:
https://github.com/AlexsLemonade/refinebio/issues/2881
https://github.com/AlexsLemonade/refinebio/issues/2837
Change the date to be after Batch deployed. This now matches https://github.com/AlexsLemonade/refinebio/blob/dev/foreman/data_refinery_foreman/foreman/utils.py#L29
N/A
> Change the start date for the dashboard to July 2021.

- common/data_refinery_common/models/sample.py
- infrastructure/deploy_box_instance_data.sh
https://github.com/AlexsLemonade/refinebio/pull/2978
My functional tests didn't include cases where there were no jobs for a sample. This happens in staging/prod.
I've tested this before, just not without jobs. Once this command runs it can be removed so I don't want to add unit tests.
> Handle the cases where a sample doesn't have any jobs.

- .github/FUNDING.yml
Related https://github.com/AlexsLemonade/AdminItems/issues/477.
Changed the donate link
> changed donate link

- workers/install_affy_only.R
#3020 
Enforce locfit version.
> Fix test_common job.

- ami/instance.tf
- ami/user-data-script.tf
- infrastructure/backend.tf
- infrastructure/batch.tf
- infrastructure/database.tf
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- infrastructure/instances.tf
- infrastructure/variables.tf
Resolves #3107 
Update terraform config:
- Migrate `template_file` to `templatefile`
- Inline user_data templates.
- Fix s3 backend configuration.
- Set postgres version to 11.16.
- Change DB `name` to `db_name`.
> Make deploy runnable on arm64.

- foreman/data_refinery_foreman/foreman/management/commands/import_external_sample_attributes.py
- foreman/data_refinery_foreman/foreman/management/commands/import_external_sample_keywords.py
- foreman/data_refinery_foreman/surveyor/management/commands/clear_database.py
- workers/data_refinery_workers/processors/management/commands/correct_affy_samples.py
#3019 
Use explicit import model names.
> Get rid of wildcard imports.

- api/data_refinery_api/management/commands/post_downloads_summary.py
- api/data_refinery_api/management/commands/test_post_downloads_summary.py
> Fix post_downloads_summary command singular/plural nouns.

- workers/run_tests.sh
#3223 
- This PR contains changes to pull the salmontools test data from the S3 bucket `data-refinery-test-assets`
- The new zip is called `salmontools_test_data.tar.gz`
You can download the test  data from here to review: https://data-refinery-test-assets.s3.amazonaws.com/salmontools_test_data.tar.gz
Below is a copy of the `README.md` that is available in the downloadable zip.
The test data contained in this zip applies to two types of tests; double and single read. Each test has a `[read]_input`, `[read]_output`, `[read]_salmontools`, `expected_[read]_output`.
- `[read]_input`
- Contains the `fastq` files for the `salmontools` command
- `[read]_output`
- Contains the `aux_info/unmapped_names.txt` files for the `salmontools` command
- `[read]_salmontools`
- This folder should be empty, …
> Pull salmontools test data from s3

- foreman/dockerfiles/Dockerfile.foreman
N/A
Minor foreman Docker file clean up. Reorder and clean up the instructions.
N/A
N/A
N/A
N/A
> Update foreman Docker image.

- workers/dockerfiles/Dockerfile.transcriptome
Update transcriptome Docker image.
Simplify Python requirements.
Add cache clean up command.
This PR also addressed #3204 issue.
> Update transcriptome Docker image

- foreman/data_refinery_foreman/foreman/management/commands/automatic_survey.py
- foreman/data_refinery_foreman/gatherer/agents/base.py
Resolves #3070 
Add basic command for survey job automation.
- Add automatic accession command.
- Exclude `SurveyAccession` accessions instead of `Experiment` accessions.
> Add automatic survey accession command.

- foreman/data_refinery_foreman/gatherer/agents/geo_agent.py
- foreman/data_refinery_foreman/gatherer/management/commands/gather_accessions.py
- foreman/dockerfiles/Dockerfile.foreman
#3247 
Add available at the moment GEOMeta DB SQLite file into Foreman Docker image.
> Add GEOMeta DB support

- api/data_refinery_api/management/commands/post_downloads_summary.py
- api/tests/management/commands/test_post_downloads_summary.py
- foreman/data_refinery_foreman/foreman/management/commands/import_external_sample_attributes.py
- foreman/data_refinery_foreman/foreman/management/commands/import_external_sample_keywords.py
- foreman/data_refinery_foreman/surveyor/management/commands/clear_database.py
- workers/data_refinery_workers/processors/management/commands/correct_affy_samples.py
- git cherry-pick 231a8e1f20ce3c61936db3b3cd8f0a5f731155b3
- git cherry-pick 8ad2452bd158273d08444bb362e3f59409fb0b7a
- git cherry-pick f777db3f61f723ab9b46dd1ff5102cc93964a223
> Cherry pick missing commits

- infrastructure/security.tf
#3253 
Replace old r.bio public key with a new one.
NA
NA
NA
> Update refine.bio public key

- .github/scripts/verify_tag.sh
#3253 
Update key path to match the expected one.
NA
NA
NA
> Fix keys path

- api/dockerfiles/Dockerfile.api_local
- api/dockerfiles/Dockerfile.api_production
- common/dockerfiles/Dockerfile.base
- workers/dockerfiles/Dockerfile.compendia
#3253 
Add a workaround for invalid version format.
> Pin setuptools to version 65.7

- api/dockerfiles/Dockerfile.api_local
- api/dockerfiles/Dockerfile.api_production
- common/dockerfiles/Dockerfile.base
- common/setup.py
- workers/dockerfiles/Dockerfile.compendia
#3253 
Revert setuptools version pinning changes.
Change common package version format
> Fix invalid version error

- api/run_tests.sh
- common/run_tests.sh
- foreman/run_end_to_end_tests.sh
- foreman/run_management_command.sh
- foreman/run_tests.sh
- foreman/test_survey.sh
- scripts/run_manage.sh
- scripts/run_shell.sh
- workers/run_command.sh
- workers/run_job.sh
Always set $volume_directory permissions (either just created or already existed).
> Fix `volume_directory` permissions

- foreman/run_end_to_end_tests.sh
#3273 
Set a correct path for foreman end2end test runner
NA
NA
> Update Foreman end2end test runner location

- foreman/tests/foreman/test_end_to_end.py
#3253 
Comment out the unservayable experiment accession.
NA
NA
NA
> Add a temporary workaround for failing end2end test

- .github/workflows/config.yml
Update the version to clean up GH workflow run summary page.
> Bump setup-terraform action from v1 to v2

- config/supported_rnaseq_platforms.txt
Closes #3280 
Here I'm adding newer (and some older) Illumina instrument models to our list of supported RNA-seq platforms.
I am requesting both David and Josh to review due to these methods.
My approach was to snag a TSV of human or mouse RNA-seq data with raw reads that were generated on an Illumina platform from European Nucleotide Archive:
```sh
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'result=read_run&query=(tax_eq(9606)%20OR%20tax_eq(10090))%20AND%20instrument_platform%3D%22ILLUMINA%22%20AND%20library_strategy%3D%22RNA-Seq%22&fields=study_accession%2Cinstrument_model%2Ctax_id&format=tsv' "https://www.ebi.ac.uk/ena/portal/api/search"
```
Then over to R:
```r
refinebio_supported_df <- read_csv("https://raw.githubusercontent.com/AlexsLemonade/refinebio/ac3170 …
```
> Add newer and additional RNA-seq supported platforms

- scripts/prepare_image.sh
It supposed to by fixed by https://github.com/AlexsLemonade/refinebio/pull/3199 but it wasn't for some reason (bad merge?)
> Fix GHCR URL typo

- .github/workflows/config.yml
Resolves #3289 
The main purpose of the PR is to introduce Docker base image CI/CD step. Other notable changes include:
- Add common Dockerfile.base image job
- Add dependencies: syntax check -> base image -> test jobs
- Migrate to pre-commit actions
- Add and title-case job/step names
- Group and reorder jobs
> Update Github workflows config

- .github/workflows/config.yml
- api/dockerfiles/Dockerfile.api_base
- api/run_tests.sh
- common/dockerfiles/Dockerfile.base
- common/dockerfiles/Dockerfile.common_tests
- common/dockerfiles/Dockerfile.migrations
- common/run_tests.sh
- foreman/dockerfiles/Dockerfile.foreman
- foreman/run_tests.sh
- scripts/common.sh
- scripts/prepare_image.sh
- setup.cfg
- workers/dockerfiles/Dockerfile.affymetrix
- workers/dockerfiles/Dockerfile.compendia
- workers/dockerfiles/Dockerfile.downloaders
- workers/dockerfiles/Dockerfile.illumina
- workers/dockerfiles/Dockerfile.no_op
- workers/dockerfiles/Dockerfile.salmon
- workers/dockerfiles/Dockerfile.smasher
- workers/dockerfiles/Dockerfile.transcriptome
- workers/run_tests.sh
Update tests running scripts
- Use versioned docker images
- Move common configs to the base image
- Exclude tests from coverage run
- Remove ghcr.io image uploads
> Update tests running scripts

- .github/workflows/config.yml
A post-refactoring troubleshooting change. It's very likely this is not the last one for today.
> Fix staging deploy process

- .github/scripts/remote_deploy.sh
- .github/workflows/config.yml
- api/dockerfiles/Dockerfile.api
- foreman/run_end_to_end_tests.sh
- infrastructure/batch.tf
- infrastructure/instances.tf
- scripts/common.sh
Resolves https://github.com/AlexsLemonade/refinebio/issues/3332
Various fixes for the issues I experienced during today's staging deploy attempt.
> Fix staging deploy

- workers/data_refinery_workers/processors/smasher.py
- workers/tests/processors/test_smasher.py
Resolves #3322 
Set a new name for smasher's email sender.
The workers/tests/processors/test_smasher.py's L1332-1335 are relevant changes only. 
All other changes are just format updates.
> Update smasher email sender address

- api/tests/views/test_api_general.py
Resolves #3259 
Fix flaky API throttling test.
Update test_api_general::APITestCases::test_all_endpoints
> Fix flaky API throttling test

- foreman/data_refinery_foreman/surveyor/sra.py
Fix SRA surveyor method name typo. 
> Correct SRA surveyor method typo

- foreman/data_refinery_foreman/surveyor/sra.py
Update experiment generation method to obtain experiment object correctly.
> Update SraSurveyor experiment generation method

- foreman/tests/foreman/test_end_to_end.py
N/A
We had originally commented out the ArrayExpress samples from the end to end tests because the surveying from that source is currently not functional. When we commented those samples out we forgot to update the number of expected samples to be successful later on in the test. This PR addresses that and adds a note to remove the omission of AE samples when that is functional again.
N/A
n/a
n/a
> adjust asserted counts for missing AE samples

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
Update API instance user data to fix the typo preventing Docker container start properly.
> Fix API server user data error

- common/dockerfiles/Dockerfile.common_tests
- workers/dockerfiles/Dockerfile.affymetrix
- workers/dockerfiles/Dockerfile.compendia
- workers/dockerfiles/Dockerfile.downloaders
- workers/dockerfiles/Dockerfile.illumina
- workers/dockerfiles/Dockerfile.no_op
- workers/dockerfiles/Dockerfile.salmon
- workers/dockerfiles/Dockerfile.smasher
Use image name specific syntax for docker RUN commands.
> Use unique names for docker renv loading commands

- infrastructure/deploy_box_instance_data.sh
- scripts/common.sh
- scripts/make_migrations.sh
- workers/dockerfiles/Dockerfile.downloaders
Update deploy configuration
- Set initial setup umask
- Show additional docker builder information
- Use versioned migrations image
- Update downloaders docker image
> Update deploy configuration

- foreman/run_end_to_end_tests.sh
- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/deploy.sh
- infrastructure/disk.tf
These changes are related to my recent e2e tests troubleshooting (an attempt to run the dev stack in a non-default region).
It updates the deploy configuration:
- Explicitly set docker commands platform option
- Update S3 buckets ACL/lifecycle configuration syntax
> Update terraform configuration

- common/data_refinery_common/models/original_file.py
- foreman/data_refinery_foreman/surveyor/geo.py
- foreman/tests/foreman/test_end_to_end.py
- infrastructure/batch/compute.tf
- infrastructure/batch/launch_templates.tf
- scripts/format_batch_with_env.sh
- workers/data_refinery_workers/downloaders/geo.py
- workers/data_refinery_workers/processors/utils.py
- workers/run_command.sh
Add e2e tests troubleshooting changes
- Increase batch launch template volume size from 300G to 500G
- Fix random syntax/comments/style/typo issues
> Add e2e tests troubleshooting changes

- common/data_refinery_common/rna_seq.py
N/A
When determining if `TXImport` can be run on a particular experiment either as part of the `Salmon` job or run early via the management command `run_tximport` we verify that the latest trascriptome index is what that salmon job was run with.
The problem encountered prior to this PR is that if the order of transcriptome indices is different, ie `SHORT` was created after `LONG`, this function would return `SHORT` even though we are interested in checking if the latest `LONG` index matches the index used to process the quant file. 
My understanding is that this is to prevent different versions of salmon from being used throughout processing, which this change would still preserve. 
This PR makes the following changes:
- Rename `get_latest_organism_index` to `get_latest_organism_indices`. …
> TXImport Eligibility - Check if SHORT and LONG indices exist

- infrastructure/delete_batch_job_queue.py
- infrastructure/deploy.sh
- infrastructure/deregister_batch_job_definitions.py
- infrastructure/destroy_terraform.sh
- scripts/format_batch_with_env.sh
Resolves #3359 
Update batch job definitions clean up process
- Narrow down expected exceptions for batch job queue deletion
- Use nextToken for 100+ duplicate entries cases
- Add `create_qn_target.json` to the list of fixed RAM jobs
> Update batch job definitions clean up process

- foreman/data_refinery_foreman/foreman/utils.py
Not an issue
These slight code adjustments aim to enhance Pythonic quality by incorporating the list comprehension 
Code Refactoring
> Update foreman utils.py: use list comprehension for collecting hung/lost jobs

- .github/workflows/config.yml
- README.md
Use GH workflow badge for refine.bio status
> Update build status badge

- api/data_refinery_api/management/commands/post_downloads_summary.py
- api/tests/management/commands/test_post_downloads_summary.py
Resolves #3382
Update post downloads summary job. Don't include 0 downloads users into stats calculation
> Update post downloads summary job

- foreman/run_management_command.sh
- scripts/common.sh
Update common/foreman scripts:
- Export SYSTEM_VERSION when unset
- Set platform for `run_management_command.sh`
> Update common/foreman scripts

- .github/workflows/config.yml
Make api base image tests explicitly wait for base image tests completion as migrations images need that.
> Update GH workflows: add test_base to test_api_base dependencies

- api/serve.sh
- api/serve_production.sh
- foreman/test_survey.sh
- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
- scripts/run_shell.sh
- workers/run_command.sh
- workers/run_janitor.sh
This is the scripts updates based on my #3392 investigation. It mostly populates absent platform and system version values for docker run commands.
> Update scripts: set platform and system version

- .github/scripts/remote_deploy.sh
- .github/workflows/config.yml
https://github.com/AlexsLemonade/refinebio/issues/3406
Update SENTRY_DSN secret configuration. Remove OPENSSL_KEY secret as it's been unused.
> Update secrets configuration

- .github/workflows/config.yml
Update names for SENTRY_DSN env variables.
> Fix SENTRY_DSN env name mismatch

- api/data_refinery_api/settings.py
- common/data_refinery_common/settings.py
- foreman/data_refinery_foreman/settings.py
- workers/data_refinery_workers/settings.py
Resolves #3410 
Partially addresses #3411 
(Re-) use STAGE variable for Sentry environment tag
> Use STAGE variable for Sentry environment tag

- workers/dockerfiles/Dockerfile.downloaders
#3413 
Update downloaders image: fix rvm.io keys issue
> Update downloaders image: fix rvm.io keys issue

- foreman/batch-job-templates/surveyor.tpl.json
Add missing `STAGE` to surveyor batch job environment.
> Add STAGE to surveyor batch environment
