.circleci/config.yml
data_models/install.sh
docker-compose.yml
foreman/data_refinery_foreman/surveyor/array_express.py
foreman/data_refinery_foreman/surveyor/end_to_end_tests.py
foreman/data_refinery_foreman/surveyor/external_source.py
foreman/run_tests.sh
run_compose.sh
workers/data_refinery_workers/downloaders/utils.py
workers/data_refinery_workers/processors/array_express.py
workers/data_refinery_workers/processors/test_array_express.py
workers/environments/test

Adds end-to-end tests for the Data Refinery. These run separately from all the other tests, using Docker Compose. Docker Compose runs 4 containers:
- Workers (in normal mode, but with an environment of `test`)
- Foreman (run via the test-runner)
- Rabbit
- Nginx (used to download data from within the workers)
The Foreman runs a survey job, which discovers a batch, queues a downloader job, and then waits for it to finish so it can discover its processor job, then waits for the processor job to finish. The workers run the downloader and processor jobs. The Foreman tests then check that `SCAN.UPC` outputting a processed file. More in depth testing of the contents of that file are upcoming.
I tested this without an internet connection to be sure that no external requests were actually being …

End to end tests

---

foreman/run_surveyor.sh
run_nomad.sh
run_shell.sh
workers/run_tests.sh
workers/worker.sh

Rich and I ran into an issue where nomad containers could not write to their volumes. This will prevent this from happening when the project is setup on future boxes, however it will not retroactively fix the permissions for existing volumes.
This will also redirect stderr from Nomad into the nomad.logs file so the terminal doesn't output stuff randomly.

Ensure that permissions on docker volumes gets intialized correctly.

---

run_nomad.sh

This PR was written by @dongbohu @kurtwheeler while pairing so it is automatically approved!
Just found and fixed this bug.
When setting up the project locally, `run_nomad.sh` failed to properly initialize the `workers/volume` directory.
_Put an `x` in the boxes that apply_
We ran a downloader job and saw it complete successfully, whereas before it failed because it could not use the local filestore.

Fixes the creation of the volume for workers locally.

---

workers/Dockerfile.base
workers/data_refinery_workers/processors/array_express.py
workers/install_ensg_pkgs.R
workers/r_dependencies.R

#85 
Instead of hard coding the species name (such as `hs`) in BrainArray packages, this PR parses an MBNI  
webpage and saves all chip names and corresponding R package URLS in an external file before installing them. `array_express.py` will then read this file to get the package name.

Use MBNI webpage to determine R package name

---

common/setup.py

A couple dependencies weren't specified in `api/requirements.txt` because they were relied upon solely by the `data_refinery_common` sub-project. However these requirements did not get added to `common/setup.py` in the `install_requires` list. This cause the `api/serve.sh` script to error out because it did not have all the python dependencies it needed.
I reran `update_models.sh` and then ran `api/serve.sh` and it started the server successfully.

Make the common project specify the dependencies it needs.

---

foreman/data_refinery_foreman/surveyor/management/commands/survey_sra.py

Allow this management command to specify both a regular file path and AWS s3 path.
I manually ran this management command a few times with regular file, s3 path and "--accession" option.

survey_sra.py: add support of s3 path

---

run_postgres.sh

I needed to reset my database. The scripts weren't working for them so I fixed the creation of `volumes_postgres`.
I ran:
```
docker kill drdb
docker container prune -f
sudo rm -r volumes_postgres
./run_postgres.sh
./common/install_db_docker.sh
./update_models.sh
```
and everything worked and was happy.

The creation of the volume for the postgres container got mangled.

---

common/data_refinery_common/models/organism.py
foreman/data_refinery_foreman/surveyor/array_express.py
foreman/data_refinery_foreman/surveyor/external_source.py
foreman/data_refinery_foreman/surveyor/geo.py
foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/surveyor.py
format_nomad_with_env.sh

n/a
From the [docs](https://docs.python.org/3/library/exceptions.html#base-classes):
> The base class for all built-in exceptions. It is not meant to be directly inherited by user-defined classes (for that, use Exception).
We have lots of cases where our custom exceptions aren't being caught by our catch-alls because we've been inheriting from the wrong type.
Essentially a trivial change. Fixes places where failing in experiments.

Move all Custom Exceptions to Exception from BaseException

---

format_nomad_with_env.sh
run_nomad.sh

n/a
`run_nomad.sh`  has a formatting error for non-test running. This whole file is still an XXX-riddled mess but at least with this fix it isn't broken-broken. Previously would cause `env: setenv =: Invalid argument`.
Runs now as described by README. This is a trivial change.

Fix Syntax Error in run_nomad.sh

---

format_nomad_with_env.sh
infrastructure/instances.tf
infrastructure/variables.tf

n/a
Connecting to the API during heavy scrape can cause `django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections`.
This adds a) an RDS Parameter Group so we can configure the timeout and b) variablizes a hard-coded RDS instance type string so that we can beef it up to something better that a t2.micro in production.
This actually doesn't solve the underlying problem, but it does make it rarer. The correct solution in the future will be to have separate database users for API and Foreman/Worker instances, and then to reserve a minimum number of connections just for the API user (which should also have PgBouncer installed).
Tested, and got this result:
Before: …

Adds RDS Parameter Groups and Instance Type Variable

---

foreman/data_refinery_foreman/surveyor/external_source.py
foreman/data_refinery_foreman/surveyor/test_external_source.py
foreman/data_refinery_foreman/surveyor/test_geo.py

I found a bug where we would only queue a single downloader job for paired RNASeq reads, when really we need to queue two: one for each member of the pair.
I ran:
```
./foreman/run_surveyor.sh survey_sra --accession ERR1562482
```
and made sure that the processor job was able to complete successfully. Before I made this change, the surveyor would queue only a single downloader job which would complete, but because the other half of the pair hadn't been downloaded yet it wouldn't queue a processor job.

Fixes issue with queue_downloader_jobs and adds an unit test for it.

---

foreman/data_refinery_foreman/surveyor/harmony.py
foreman/data_refinery_foreman/surveyor/test_harmony.py

While testing my routing refactor branch I ran into an experiment `E-TABM-38` which caused surveyor jobs to crash because of an uncaught KeyError. This is because `extract_title` was returning different titles for the samples which came from the JSON endpoint and samples which came from the SDRF.
I ran `./foreman/run_surveyor.sh survey_all --accession=E-TABM-381` and it finished successfully, whereas before my fix it crashed because of a KeyError.

Sorts sample dictionaries before trying to extract the title in harmony.

---

workers/data_refinery_workers/downloaders/geo.py
workers/data_refinery_workers/downloaders/test_geo.py

https://github.com/AlexsLemonade/refinebio/issues/325
GEO has an Aspera endpoint. We should use it when possible, as we do for SRA. It is significantly faster.
A new `test_download_aspera_and_ftp` has been added with many assertions. Also, the `test_geo` file was totally disabled, so it has been re-enabled with this PR. Another good reason to address #326.
```
$ .aspera/cli/bin/ascp -i .aspera/cli/etc/asperaweb_id_dsa.openssh -k1 -T anonftp@ftp-trace.ncbi.nlm.nih.gov:/geo/series/GSE22nnn/GSE22427/suppl/GSE22427_non-normalized.txt.gz /home/user/data_store/derp
```

Aspera Downloader for GEO

---

README.md
common.sh

The old command to detect IP addresses on Linux was `ip route get 8.8.8.8 | awk '{print $NF; exit}'`,
but that did not work on my machine or the default Ubuntu docker image I tested. It turns out that `ip route` does not
appear to have standardized output across different versions and distros. I found this alternate option that is hopefully
standardized and installed by any sane Linux distro to give us the internal ip address for the setup scripts.
N/A
Make the install scripts work on more people's hardware.
N/A
- Bugfix
Running the get_ip_address function on my laptop gave the correct internal ip address, and it made the install scripts start working properly.
N/A

Hopefully better Linux IP address detection

---

.circleci/config.yml

NA
The downloader tests have been failing because of a timeout. This has been fixed in a couple branches already, so this works, this just makes it so others don't need to repeat that change.
This is a change to CI and it already works here: https://circleci.com/gh/AlexsLemonade/refinebio/2683?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Prevent the downloaders tests from timing out in CCI.

---

.circleci/config.yml
.circleci/run_terraform.sh
README.md
infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
infrastructure/instances.tf
infrastructure/networking.tf
infrastructure/nomad-configuration/client.tpl.hcl

#342 
Because AWS doesn't support the top level domain `.bio`, we cannot use Route53 to manage the domain and therefore cannot use the Amazon Certificate Manager like we did in cognoma. This enables HTTPS (and forces redirection from HTTP). Additionally this uses an AWS Network Load Balancer with an Elastic IP to make it so that when the API server goes down and comes back up with a new IP, our DNS settings are still valid for forwarding traffic to it.
I ran the new configuration with the Load Balancer from CCI and made sure that the elastic IP address was properly working especially when forwarded to via DNS. I also ran the `certbot` commands directly on the API instance to verify that they worked.
I am going to use the merge …

Make API persistent and support HTTPS

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py

https://github.com/AlexsLemonade/refinebio/issues/332
For some peculiar reason, some people prefer TSVs over JSON files for metadata. This adds those files to smasher-produced archives.
Fields are provided by the Sample object's `to_metadata_dict` class, so any missing fields should be added there in the future.
New test assertions have been added.

Add TSV Metadata to Smasher Output

---

foreman/run_tests.sh
run_all_tests.sh

N/A
When I was running tests through emacs it was repeatedly telling me that I had to run nomad. After a lot of confusion I realized that it was because when emacs ran `ps aux` in its shell, the output was truncated:
```
root      6238  1.4  0.2 865196 37800 pts/0    Sl   15:37   0:45 nomad agent -bind 192.168.150.16 -data-dir /home/k
```
This is a feature of `ps`, I guess to make it more usable on terminals with limited width. However it made it so `test_nomad` didn't appear in the command, so it was caught by `grep test_nomad`.
`ps` has the option:
```
w      Wide output.  Use this option twice for unlimited width.
```
which prevents this behavior. Since we're just grepping this output, there's no benefit to ever having it truncated so I think this is a fix which will be generally …

Fixes ps sometimes not outputting enough output to show up in grep.

---

common/Dockerfile.tests
workers/dockerfiles/Dockerfile.affymetrix
workers/dockerfiles/Dockerfile.downloaders
workers/dockerfiles/Dockerfile.illumina
workers/dockerfiles/Dockerfile.salmon

n/a
The Ubuntu keyserver is constantly down and it's causing our tests to fail all the time for no fault of our own. 
This switches to a high availability public keyserver that should fix some of our problems.

Switch from Ubuntu to High Availablity Keyserver

---

workers/data_refinery_workers/processors/test_transcriptome_index.py
workers/data_refinery_workers/processors/transcriptome_index.py
workers/run_tests.sh
workers/tester.sh

N/A
Every now and then I run out of space and have to clean some things up. The `workers/test_volume` seemed larger than it needed to be so I found a few quick changes I could make to reduce the size by a little more than 6GB on a permanent basis.
Unit tests cover all the functionality I've changed.

Reduces size of test_volume on developer machines

---

infrastructure/networking.tf

N/A
As part of getting the API using HTTPS, I tested some terraform configurations for the staging stack directly from CircleCI. Once I got a working configuration I then made (what I thought were) the same changes in #343. However I didn't properly test them since the HTTPS stuff isn't really testable without a DNS configuration pointing to it. @Willv19 ran into the issues caused by this bug while trying to stand up a dev stack.
Will has been able to run terraform successfully with these changes.

Fixes some bad resource references in terraform networking config

---

infrastructure/api-configuration/nginx_config.conf
workers/data_refinery_workers/processors/salmon.py

n/a
The logs are now full of: 
```
data-refinery-log-group-circleci-staging log-stream-api-nginx-error-circleci-staging 2018/07/02 23:43:45 [info] 6311#6311: *84929 client closed connection while SSL handshaking, client: 10.0.126.33, server: 0.0.0.0:443
data-refinery-log-group-circleci-staging log-stream-api-nginx-error-circleci-staging 2018/07/02 23:43:45 [info] 6311#6311: *84930 client closed connection while waiting for request, client: 10.0.126.33, server: 0.0.0.0:80
data-refinery-log-group-circleci-staging log-stream-api-nginx-error-circleci-staging 2018/07/02 23:43:46 [info] 6311#6311: *84931 client closed connection while SSL handshaking, client: 10.0.126.33, server: 0.0.0.0:443
data-refinery-log-group-circleci-staging log-stream-api-nginx-error-circleci-staging 2018/07/02 23:43:46 …
```

Make Nginx Hush Up

---

.circleci/config.yml
workers/data_refinery_workers/processors/requirements.txt
workers/data_refinery_workers/processors/salmon.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py

https://github.com/AlexsLemonade/refinebio/issues/330
Depends on: https://github.com/AlexsLemonade/refinebio/pull/355
Conflicts with: https://github.com/AlexsLemonade/refinebio/pull/307
Adds ability to smash RNASeq/Microarray data together. 
Jackie recommended: 
```
aggregating by experiment -> return untransformed output from tximport
aggregating by species -> log2(x + 1) tximport output
```
For `SPECIES`, this is accomplished by: 
```
data = data + 1
data = np.log2(data)
```
I don't understand the inclusion of `aggregating by experiment`, since there are no experiments (as far as I am aware) which use both technologies at once. Still, if it does occur, the transformation above won't.
- New feature (non-breaking change which adds …

Dualsmash Part 2: Transform and Smash

---

.circleci/config.yml
.circleci/run_terraform.sh
.circleci/update_docker_img.sh
prepare_image.sh

N/A
I had two tagged workflows fail recently. One was because of a keyserver issue. The other was because we're checking the `$CIRCLE_BRANCH` env var to make sure we're on dev or master before deploying and that var isn't set by circle. This PR addresses both of these issues.
It addresses the first by retrying building docker images 3 times in `prepare_image.sh`.
It addresses the second by verifying that the commit is on either dev or master a different way.
I've tested that these things work locally, but the real proof will be in the production pudding.

Fix the issues preventing tag commits from successfully deploying.

---

api/data_refinery_api/middleware.py

N/A
While trying to debug an issue with requesting a dataset, I found that I could not see the stack trace for the exception triggered by the `Submit` button. Therefore I've added some additional middleware code to capture the exception information for bad requests.
Here is an example I triggered on my local server (configured to use the staging API Sentry project for testing): https://sentry.io/greenelab/staging-refinebio-api/issues/607845320
I wasn't able to get a unit test to trigger my process_exception function. My suspicion is that there's different Django magic at play during tests, but I don't really know. I've typed up a description of what I've tried into this [stackoverflow post]() and if someone comes along and answers it …

Sends exception info into sentry from the API.

---

.circleci/update_docker_img.sh
infrastructure/deploy.sh

N/A
I ran a deployment but my new API code didn't make it out. I realized that it's cause the server never got restarted. This makes the server restart.
This perhaps could be done in a way which results in less downtime if we ssh'd onto the API server and used `docker restart` but that seems like it'd be more brittle and not the right way to avoid downtime anyway.
I ssh'd onto a circleci box and ran these commands manually and saw the API server get restarted as a result.

Taints the API server during deploys so a new container will start

---

foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py

N/A
This test broke because Ensembl added some more organisms to their Plant division. This will happen over time, so we should just not check hard numbers and instead make sure we're generating a lot of jobs for them.
Broken build: https://circleci.com/gh/AlexsLemonade/refinebio/3723
This is a unit test fix.

Ensembl adds organisms sometimes, so let's not check hard numbers.

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py
common/data_refinery_common/models/models.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/108
Doesn't return `null` organisms, however the fact that these were being returned at all suggests that there is an underlying data problem that this PR doesn't address (in particular, a missing `ExperimentOrganismAssociation`, which if I remember was added so that we could have this feature in the first place).
New assertions added.

Prettier handling of null organisms

---

infrastructure/networking.tf
infrastructure/security.tf

https://github.com/AlexsLemonade/refinebio-frontend/issues/155
Allows the API security group to talk to the nomad server group on port 4646 so we can dispatch Nomad jobs.
I haven't tried this yet. My gut says this is the problem.

Allow API to nomad API communication

---

api/serve_production.sh
api/uwsgi.ini

https://github.com/AlexsLemonade/refinebio-frontend/issues/121
uWSGI barfs on large requests by default. This raises that limit.  Also fixes `serve_production.sh` script.
Verified the cause and effect locally.

Bump uWSGI buffer size to 32768

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

This is the backend fix for:
https://github.com/AlexsLemonade/refinebio-frontend/issues/108
(1) Add `organisms__name` filter
(2) Skip `technology` counter if it is None or a string of white space characters only.

Add "organisms__name" filter in SearchResult API

---

api/dockerfiles/Dockerfile.api_local
api/dockerfiles/Dockerfile.api_production
workers/dockerfiles/Dockerfile.affymetrix
workers/dockerfiles/Dockerfile.illumina
workers/dockerfiles/Dockerfile.salmon
workers/dockerfiles/Dockerfile.smasher
workers/dockerfiles/Dockerfile.transcriptome

https://sentry.io/greenelab/staging-refinebio/issues/612490086/?query=is:unresolved failed because of not being able to lookup an accession code. Turns out this fix isn't actually related because the no_op image actually had the config in it already, but it's what made me realize we should probably make this change.
Every image we have has access to code which relies on the config directory. They may not have actually been calling it so it may not have been an issue, but they can and so it will be much better if they all do.
None because this only adds the config, it can't break anything.

Make sure that config is on every docker image.

---

common/data_refinery_common/test_utils.py
common/data_refinery_common/utils.py

https://sentry.io/greenelab/staging-refinebio/issues/612490086/?query=is:unresolved
We try to translate external platform accession codes to a common representation we call internal accession codes. However if we end up with an accession code which is already internal, we fail to match it. This makes us able to match those.
New test case.

Kurtwheeler match internal accessions

---

workers/nomad-job-specs/affymetrix.nomad.tpl
workers/nomad-job-specs/downloader.nomad.tpl
workers/nomad-job-specs/illumina.nomad.tpl
workers/nomad-job-specs/no_op.nomad.tpl
workers/nomad-job-specs/salmon.nomad.tpl
workers/nomad-job-specs/smasher.nomad.tpl
workers/nomad-job-specs/transcriptome.nomad.tpl

n/a
Scraping and processing can happen at their own pace, but people who are smashing need the data as soon as possible. This will create a priority for Smash over Crunch.
I have no idea what these values actually mean, and I can't find any documentation about it. I assume assuming that 100 good, 50 less good.
No

Sets Smash Priority to 100 and All Other Priorities to 50

---

workers/nomad-job-specs/transcriptome.nomad.tpl

n/a
Similar to prioritizing Smasher jobs over all, we want to prioritize txindex jobs over Salmon jobs so that the required indexes are always available.

Make Transcriptome Index Processing Higher Priority than Other Jobs

---

.circleci/config.yml
workers/data_refinery_workers/processors/no_op.py

N/A
I noticed an error log in the staging logs that said it couldn't find a gene conversion file for `hgu133aplus2`, which is definitely a platform we support.
It turns out the directory path for those files was wrong, and worse our `no_op` tests weren't being run in circleCI.
There's another bug in `gene_convert.R` that will prevent these tests from passing, but I believe another PR will address those.
It doesn't work yet.

Kurtwheeler fix gene conversion

---

api/data_refinery_api/middleware.py
api/data_refinery_api/tests.py

N/A
We're getting a ton of 404 errors in sentry about people trying to scrape for common vulnerabilities. This is spammy so I'm filtering out the 404s.
I configured raven on my local server and hit some bad routes and nothing went to sentry.
Also unit tests.

Don't send 404s to sentry.

---

foreman/data_refinery_foreman/surveyor/management/commands/survey_array_express.py
foreman/data_refinery_foreman/surveyor/management/commands/survey_geo.py
foreman/data_refinery_foreman/surveyor/management/commands/survey_sra.py
foreman/data_refinery_foreman/surveyor/management/commands/survey_transcriptome.py
workers/data_refinery_workers/downloaders/management/commands/run_downloader_job.py
workers/data_refinery_workers/processors/management/commands/run_processor_job.py

n/a
Fixes lots of:
```
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging Traceback (most recent call last):
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging   File "manage.py", line 23, in <module>
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging     execute_from_command_line(sys.argv)
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging     utility.execute()
data-refinery-log-group-circleci-staging log-stream-processor-docker-circleci-staging …
```

Replace Management Command Return Codes with Sys Exits

---

infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh

n/a
Graphite was eating up all of the storage space available on the lead server. This lowers the amount of retention to 1 day's worth and more generally makes this into a configurable value.

Lower Graphite Retention and Create Configurable Config File

---

.circleci/config.yml

https://sentry.io/greenelab/staging-refinebio/issues/612563649/
This is a short-term fix for `STAGING-REFINEBIO-17`, adding the `hgu133a` gene conversion matrix.
All of these files should be replaced with a dynamic loading from Zenodo, but this will make the `no_op` work for those thousand samples in the meantime.
Related: https://github.com/AlexsLemonade/identifier-refinery#methods

Adds hgu133a.tsv.gz

---

api/data_refinery_api/tests.py
api/data_refinery_api/urls.py
api/data_refinery_api/views.py
workers/run_tests.sh

https://github.com/AlexsLemonade/refinebio-frontend/issues/192
The Download page currently has a very costly stats table which requires fetching and tabulating statistics about a dataset. This adds an endpoint so those stats can be done on the server without fetching the whole set at once.
New test case added.

Add a Simple DatasetStats Endpoint

---

infrastructure/init_terraform.sh

N/A
In https://github.com/AlexsLemonade/refinebio/pull/462/files I changed the way we invoke `terraform init` to use a script, but forgot to include that script. This is that script.
I tested this as part of #462

Adds a file that was forgotten in a previous PR.

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py
foreman/data_refinery_foreman/surveyor/management/commands/survey_sra.py
workers/data_refinery_workers/processors/salmon.py

N/A
While running the crunch for Jackie yesterday, Rich and I noticed that a lot of jobs were getting queued multiple times. This addresses that, along with a couple minor things I bumped into along the way.
Additionally I realized that I wasn't mocking out nomad correctly. This was fine, since before all the tests were making sure that things weren't equal to the value returned, but the additional tests I added meant I needed to fix that so I did.
I queued up a couple salmon jobs but made it so they required more RAM than my laptop has. This meant that they sat in a pending state. This allowed me to actually keep the Nomad job in the 'pending' state long enough to see it get queued multiple times.

Fixes foreman requeuing jobs it shouldn't. Also a couple other minor bugs

---

common/data_refinery_common/job_lookup.py
common/data_refinery_common/message_queue.py
foreman/data_refinery_foreman/surveyor/geo.py
workers/data_refinery_workers/downloaders/geo.py
workers/data_refinery_workers/downloaders/utils.py

Discovered during: https://github.com/AlexsLemonade/refinebio/issues/466
Two issues were combining here to create superfluous `AFFY_TO_PCL` jobs being created for files that should have been `NO_OP`'d if they were to be processed at all, but shouldn't have been.
One fix is a really stupid one, the file type dispatcher wasn't using slices properly so it just wasn't working at all.
The second fix is a behavior change: we don't create OriginalFile:Sample associations if the sample is comes from a `_family` (processed) file if that Sample _also_ has raw data. Is that the correct behavior? I'm not sure, but it stops us from creating additional `NO_OP` jobs in the situation where we're already going to have an `AFFY_TO_PCL` anyway. 
We might end up with an extra file lying around though.
- …

Fixes Two Issues Which Caused Extra Jobs of the Wrong Type

---

infrastructure/deploy.sh

N/A
I noticed this issue while standing up a dev stack. The migrations were trying to log their AWS instance id, which they don't have because they aren't run from an AWS instance.
I've stood up a dev stack with these changes.

Don't let running the migrations try to talk to AWS.

---

workers/dockerfiles/Dockerfile.no_op

Found in Jackiecrunch.
The previous identifier refinery archive was missing two platforms, including `hthgu133pluspm`, which we needed. The upstream bug is fixed and the result published, this just uses the latest version.

Update No-Op Dockerfile to Use Latest Identifier Refinery Archive'

---

workers/data_refinery_workers/processors/gene_convert.R
workers/data_refinery_workers/processors/test_no_op.py

Jackiecrunch.
Some of the files output by the NO_OP processor were significantly larger than they should have been. This deduplicates those lines (although it doesn't adequately explain _why_ those were duplicated in the first place.)
Tested locally, and a new assertion is added to make sure that the file is the correct size.

De-duplicate Rows from NO_OP Processor

---

api/data_refinery_api/serializers.py
common/data_refinery_common/models/models.py
common/data_refinery_common/models/test_models.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/211
This PR adds a field to the ExperimentSerializer that gives all of the metadata fields that at least one associated Sample has. This is so that this can be displayed on the frontend.
I ran the API locally to make sure that the output was correct.

Add sample_metadata to experiments endpoint

---

infrastructure/init_terraform.sh

N/A
I realized our first deploy where we cutover from local to remote backends will fail because terraform will try to prompt us for input. This uses a flag to avoid that.
I haven't, this will work or I will manually have to get the cutover to work.
- x] Any dependent changes have been merged and published in downstream modules

Add force-copy argument to terraform init so it will switch backends.

---

.circleci/run_terraform.sh
.circleci/slackpost.sh
.circleci/update_docker_img.sh

N/A
This came up while trying to redeploy the staging server: https://circleci.com/gh/AlexsLemonade/refinebio/4696
I didn't realize that if grep fails to match, then it exits with error code 1. This uses a fix from https://unix.stackexchange.com/questions/330660/prevent-grep-from-exiting-in-case-of-nomatch to make this not crash the script.
I've tested this by running the new lines on a circleci box that I ssh'd onto, but I can't test it further than that really.

Kurtwheeler fix rebuilding docker imgs

---

common/data_refinery_common/test_utils.py
common/data_refinery_common/utils.py
foreman/data_refinery_foreman/surveyor/array_express.py

N/A, came up in Jackie Crunch
When I implemented the supported platforms lists, I missed the fact that A-GEOD-XXX and GPLXXX are the same platform and therefore are only specified once in the list. This addresses that by performing a conversion and including them in the list.
I added a unit test and I made sure that running the surveyor for E-GEOD-77094 populated the platform fields for the samples successfully.

Adds converted GPLs and A-GEODs to supported microarray list.

---

common.sh

N/A
The function `get_ip_address` in `common.sh` was returning two IP addresses in my computer. This PR ensures only one get's returned. Before it was:
```sh
$ source common.sh
$ HOST_IP=$(get_ip_address)
$ DB_HOST_IP=$(get_docker_db_ip_address)
$ echo $HOST_IP
192.168.150.86 169.254.111.170
```
And that was giving the following error when running `./api/serve.sh`
```sh
Unable to find image '169.254.111.170:latest' locally
docker: Error response from daemon: pull access denied for 169.254.111.170, repository does not exist or may require 'docker login'.
```
Thanks to @kurtwheeler for helping diagnose the error.
I ran `'./api/serve.sh` successfully.

Ensure get_ip_address returns a single IP

---

.circleci/config.yml

https://github.com/AlexsLemonade/refinebio/issues/490
We have the Docker Caching Layer feature enabled on our CircleCI account. This actually turns it on for our builds, however it may take a couple runs for the cache to be populated and used.
We have a two week trial with this feature, so we can see how it does when there's lots of builds on different branches and such, and also how it affects deployments (Which we'll probably need a couple of.)
https://circleci.com/gh/AlexsLemonade/refinebio/4893 ran in 24:54, 10 minutes of which were waiting for SSH sessions. This means the run time for that build went from ~1 hour to ~15 minutes.

Turn on docker caching layer in circleci.

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

Fixes #441
Since our desired filter behavior wasn't covered by the default filter, I had to implement a custom FilterSet using `ModelMultipleChoiceFilter`s where conceivably we would want to apply more than one filter.
I ran the API locally to make sure that the output was correct.

Allow multiple filters in same category

---

api/data_refinery_api/serializers.py
api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/192
The downloads page is currently really slow for large datasets, which has a lot to do with the amount of network requests we make and the size of the responses. This PR makes it so that all of the information for the page is returned at once if `?details=true` is added to the end of a dataset link, which cuts down on network latency issues associated with multiple requests. The serializers used when that parameter is added also make sure that only the relevant information is downloaded at that moment, saving on bandwidth and speeding up the download.
I ran the API and frontend locally.
_Put an `x` in the boxes that …

Make the downloads page faster

---

workers/data_refinery_workers/processors/no_op.py

N/A
There are hundreds of R issues in sentry. These get annotated by the R script and the file that failed, but not the error from R. This edit reports the R script and R error in the logger. 
This does change the behavior slightly: The specific file that was processed doesn't get put into the `job_context["job"].failure_reason`. Instead the R stderr does. It looks like the `job_context['input_file_path']` already gives us the file that was processed. This is the only potentially behavior-breaking change that I know of.
N/A
I tested running an R script in python via `subprocess.check_output` …

R error -> logger

---

prepare_image.sh

N/A came up because zenodo went down but it didn't make our tests fail when we couldn't build no_op
If we couldn't build an image prepare_image.sh would still exit with a status code of 0. This meant our tests continued with an old image causing problems. This exits with a status code of 1 if we cannot build an image after three attempts.
Tried to build a no_op image while zenodo was down, exit code was 1.

Make prepare_image.sh fail if it cannot prepare the image.

---

api/data_refinery_api/serializers.py
api/data_refinery_api/tests.py

This is a quick fix of the API during review of this PR:
https://github.com/AlexsLemonade/refinebio-docs/pull/23
Two modifications of the API:
- Add `id` field to ProcessorSerializer
- Add processor's full information (instead of `id` only) to `ComputationalResultSerializer`.
I also added a new test case for the change.

Quick fix of Processor's API

---

api/data_refinery_api/serializers.py
api/data_refinery_api/tests.py
common/data_refinery_common/models/models.py

n/a
Adds a field so that 'Add to Dataset' can only add the processed responses.
New assertion

Adds processed_samples to Search Response

---

.circleci/config.yml

N/A
DLC runs out of disk space when deploying, so don't use DLC.

Disables docker layer caching for deploys.

---

.circleci/config.yml
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

N/A came up during crunch
During the zebrafish crunch, many jobs failed due to 
```
Driver Failure  failed to start task "affy_to_pcl" for alloc "8882c9e9-6f1f-6270-dc0b-910de0f527e5": error creating rpc client for executor plugin: pipe2: too many open files
```
[Here,](https://github.com/hashicorp/nomad/issues/3686#issuecomment-372283062) someone describes an essential property we should set. I have done so in this PR.
N/A

Sets the ulimit option for files for nomad clients.

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

n/a
Docker ran out of internal IPv4 addresses. I think this fixes it but I haven't tested it yet. Submitting here for consideration.

Increase IPv4 address space of Docker bridge network - I Think

---

workers/data_refinery_workers/downloaders/geo.py
workers/data_refinery_workers/downloaders/sra.py

https://sentry.io/greenelab/staging-refinebio/issues/609745158/?query=is:unresolved
It seems like we're able to kill ENA's ability to Aspera pretty reliably now. Eventually the server comes back online for a little bit. We don't need to error log every time it happens, and we don't need to hang around for 300s every time.

Lowers ascp Warning Level and Reduce Retry Wait Period

---

README.md

N/A
The Surveyor section of the README made reference to types of Surveyor jobs that no longer exist (e.g., `survey_array_express`). This PR introduces an update to that section such that we only reference the `survey_all` Surveyor Job type. I believe that either _run_ accession codes or _project_ accession codes can be supplied for RNA-seq samples/experiments, and that's what I've written here, but please let me know if that is incorrect. 
N/A

Update README to only include `survey_all`

---

api/data_refinery_api/serializers.py

This is a quick fix based on:
https://github.com/AlexsLemonade/refinebio-frontend/issues/99#issuecomment-417074733
Add `assembly_name` to transcriptome index API.

Add assembly_name to OrganismIndex API

---

.circleci/update_docker_img.sh

N/A came up because https://circleci.com/gh/AlexsLemonade/refinebio/5850 failed
We don't want to overwrite existing docker images so we bail out of deploys if the images already exist. However building the docker images takes a long time and sometimes the step after that fails. Rather than waiting for another build time we could iterate on the same deploy quicker by just continuing with the deploy if the images exist.
We still won't overwrite the images, but this way our deploy times aren't as crippling.
I have not tested this yet because it is deploy code so I wanna test it in CI.

Allow deploys to continue if image tages already exist.

---

README.md

N/A, updates docs for https://github.com/AlexsLemonade/refinebio/pull/556
In https://github.com/AlexsLemonade/refinebio/pull/556 I removed all our source-specific surveyor commands since survey_all is capable of handling them all based on the pattern of the accession. I also added a dispatcher so that each survey job can just do one accession so we can queue work faster. The corresponding docs in the README did not get updated. This rectifies that.
- Documentation
N/A

Minor updates to readme due to survey dispatching changes.

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

N/A, deploys have consistently broken the https://api.staging.refine.bio link
My theory is that because the load balancer attachments cannot happen until after the API server comes back up, that it's running certbot before they exist so the certbot challenge cannot make a HTTP request to the server it is running on. I'm not sure, but it seems plausible.
I thought about trying to curl in a loop while waiting for the attachments come up, but I'm not sure what that would look like and the only way I can figure that out would be to break the attachments again. For now, waiting 3 minutes on our API seems like an acceptable stopgap.
N/A cause I can't test outside of staging.

Make sure certbot has HTTP access to the server it's running on

---

infrastructure/cluster_connect.sh
infrastructure/disk.tf
infrastructure/instances.tf
infrastructure/list_hosts.sh
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/variables.tf

Replaces two hardcoded `us-east-1- strings. Also adds `speedometer` as a client tool.

Tiny PR: Regionify Hardcoded Region Strings

---

workers/data_refinery_workers/processors/salmon.py

n/a
Does the math and changes --numThreads (-p) from 20 to 16 after private conversation with Dr. Salmon. 16 is best, and on the X1: (2 threads/core * 16 cores/socket * 64 vCPU) / (1TB/18GB) = ~17, so we're good.
Allows us to remove an XXX. 

Optimize Salmon core usage, Remove XXX

---

api/data_refinery_api/views.py
common/data_refinery_common/message_queue.py
common/data_refinery_common/test_utils.py
common/data_refinery_common/utils.py
format_nomad_with_env.sh
workers/nomad-job-specs/smasher.nomad.tpl

N/A Ariel was trying to test the new emails and could not trigger a smash job:
https://sentry.io/greenelab/staging-refinebio-api/issues/612495404/?query=is:unresolved
> Dispatching Nomad job of type ProcessorPipeline.SMASHER for job spec SMASHER_0_4096 to host 10.0.167.44 and port 4646 failed.
I fixed this in two ways:
* First I changed the default value of get_volume_index so that it returns an index that is actually used. We were returning 0 by default when the volume indices go from 1-10. The API doesn't have that set up, so it always chooses the default.
* However this means that if the system is at rest, i.e. no spot instances are spun up, then we have to spin up instances until one of them chooses to use the EBS volume with index 1. This means that for a single smash job we could …

Make the get_volume_index function return a default value that is valid.

---

workers/data_refinery_workers/processors/gene_convert.R
workers/data_refinery_workers/processors/test_no_op.py

N/A
`data.table::fread` can't read in gzipped files. Appending `zcat` to the path is what we had prior to #593.

Add zcat to gene conversion R script

---

workers/data_refinery_workers/processors/salmon.py

n/a
FastQC can be run in a multithreaded mode. Each thread takes 256 RAM, so this should still fit snugly in the Salmon image.

Run FastQC With Additional Threads

---

foreman/data_refinery_foreman/surveyor/array_express.py
foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/test_external_source.py
workers/data_refinery_workers/processors/salmon.py
workers/data_refinery_workers/processors/test_salmon.py
workers/run_tests.sh

N/A came up during crunch
I didn't realize that the tx indices would be nested within an `index` directory after extraction. I should have tested this better but it's so hard to test salmon jobs locally because of download speeds.
Testing in current crunch.

Fix a path-related issue for tx index extraction.

---

foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/test_sra.py

N/A Came up during crunch
Crunch had a bunch of:
```
2018-09-18 17:31:37,488 local data_refinery_foreman.surveyor.sra ERROR [accession: DRR51062]: Could not discover any metadata for run.
```
Turns out we were missing some zeroes. This fixes that.
Tested by running previously broken accession: DRP003977

Fixes SRA surveyor's read run generation range logic.

---

workers/data_refinery_workers/processors/transcriptome_index.py

In the TXI processor, `rsem-prepare-reference` and `salmon` both accept options to use higher numbers of threads that we haven't been using. Since they default to 1, this small PR may increase the speed of `rsem-prepare-reference` by up to a factor of 16.

Use --num-threads When Calling TXI Binaries

---

foreman/nomad-job-specs/surveyor.nomad.tpl
foreman/nomad-job-specs/surveyor_dispatcher.nomad.tpl
workers/nomad-job-specs/affymetrix.nomad.tpl
workers/nomad-job-specs/downloader.nomad.tpl
workers/nomad-job-specs/illumina.nomad.tpl
workers/nomad-job-specs/no_op.nomad.tpl
workers/nomad-job-specs/salmon.nomad.tpl
workers/nomad-job-specs/smasher.nomad.tpl
workers/nomad-job-specs/transcriptome.nomad.tpl

https://github.com/hashicorp/nomad/issues/4700
Dang 'ol Nomad trying to take our Foreman's jerb!!!
This was triggering this error: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/utils.py#L48 because we didn't think the same job should be started more than once, not realizing Nomad would try to do it for us if the jobs got interrupted for some reason.
I've run `sudo -E ./run_nomad.sh` locally and everything gets registered correctly. Actually crashing jobs is pretty difficult to trigger so further tests will probably have to wait until a big crunch.

Set Nomad reschedule stanza so that Nomad doesn't reschedule our jobs

---

api/data_refinery_api/views.py
api/uwsgi.ini
common/data_refinery_common/job_lookup.py
common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/test_sra.py
workers/data_refinery_workers/processors/illumina.R
workers/data_refinery_workers/processors/management/commands/create_qn_target.py
workers/data_refinery_workers/processors/test_qn_reference.py
workers/nomad-job-specs/downloader.nomad.tpl

Ariel thinks he can reliably crash the API server by sending it requests for gigantic querysets. This sets a hard limit on the request size with `max`, and makes the `uswgi` settings more likely to end requests which take too long.

Move to Hard Limited Pagination on Jobs, add Harakiri

---

format_nomad_with_env.sh
infrastructure/deploy.sh
infrastructure/variables.tf
workers/nomad-job-specs/downloader.nomad.tpl

N/A came up while deploying for crunch.
The AWS keys for the nomad clients were getting output by terraform and used by deploy.sh to try to run terraform, which it didn't have enough permissions for. This fixes it so the env var output by terraform won't overwrite the keys of the deployer's host.
I have run deploys with these changes.

Fixes AWS key conflicts in the midst of deploy.sh.

---

infrastructure/deploy.sh

N/A came up because the API didn't get deployed correctly.
We recently changed the API container to only be started by the deploy script via ssh, rather than only being restarted that way. However there was a command which was tripping that part of the script up by returning a non-zero exit code. This fixes that.
Ran a deploy after tainting the API server. It recreated it and then was able to start the container.

Fix part of deploy script dedicated to starting the API.

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_qn_reference.py
workers/data_refinery_workers/processors/test_smasher.py
workers/data_refinery_workers/processors/utils.py
workers/run_tests.sh

n/a
We can't rely on externally supplied `title` fields for smash column titles as they aren't guaranteed to be unique. Switches to use `accession_code`, which is. Also fixes an email bug case.
New test files and assertions added.

Add Support for Smashing `SRP051449`

---

.circleci/update_docker_img.sh

N/A: https://circleci.com/gh/AlexsLemonade/refinebio/7559 deployed staging instead of prod because it thought it was a dev branch.
This method of checking is less finicky.
Ran these commands on a circle server to make sure they did what we wanted.

Improve the way we check the git branch while deploying.

---

.circleci/config.yml
.circleci/verify_tag.sh

N/A came up during a discussion about our deploy process and it's security.
Our deploy process is triggered by pushing git tags. However anyone with access to our repo can push tags to it. This PR makes it so that tags must be signed by a trusted individual before they're pushed.
I ran this script on a tag that I didn't sign and it exited with status code 1.
I ran it on a tag I did sign and it exited with status code 0.

Lock down deploys by verifying git tags.

---

api/data_refinery_api/urls.py
api/data_refinery_api/views.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py
format_nomad_with_env.sh

https://github.com/AlexsLemonade/refinebio/issues/680
https://github.com/AlexsLemonade/refinebio/issues/681 (Hopefully)
https://github.com/AlexsLemonade/refinebio/issues/683 (Hopefully)
If a SALMON job gets retried, increase the amount of RAM if possible.
This PR also includes an API change necessary for https://github.com/AlexsLemonade/refinebio-frontend/issues/346
New test case.

Increase RAM Amount Upon Retrying Salmon Jobs

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/339
Uses the `filter_fields` to add support for `has_publication` filtering. However, I'm not entirely convinced that this will be consequence-free in other places, so we may want to reassess and add the filtering in manually, as we do for some other fields. Waiting for Ariel to check first.
New assertions.

Add `has_publication` to `filter_fields`

---

.circleci/cleanup_instance.sh
.circleci/config.yml
.circleci/run_terraform.sh

N/A I've been meaning to clean this up for a while, finally saw some error output about it and did it!
In https://github.com/AlexsLemonade/refinebio/pull/462 I switched us to using Terraform's built in remote-backend feature. However I wanted to migrate our old stacks into it so I left our manual state file management code around so it would pull down existing state to use as a starting point. Well I never went back and cleared it out once there was no infrastructure that was only tracked via our manual state files.
This finally addresses that.
N/A but this stuff hasn't affected anything for a while. It will be tested via a staging deploy.

Remove the manual implementation of the remote terraform backend.

---

api/data_refinery_api/serializers.py
api/data_refinery_api/tests.py
api/data_refinery_api/views.py
infrastructure/api-configuration/nginx_config.conf

https://github.com/AlexsLemonade/refinebio/issues/711
Changes us from using 700+ SQL calls per search down to 7. Overall API response is 10-100x faster.
Requires front end changes!
Turns out the calculations we making to avoid having to send the entire Sample objects were significantly slower than just sending everything. Sending everything is more useful in terms of API utility, but this change that frontend modifications will have to be made. We discussed this in person but Ariel will need to play with and review this PR before it can be merged. Deploys must also be done in conjunction with corresponding front-end changes. 
Tests updated to remove fields no longer being passed.

 Use prefetch_related on API search calls 

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

https://github.com/AlexsLemonade/refinebio/pull/738 wasn't a good enough fix
When I tested https://github.com/AlexsLemonade/refinebio/pull/738 I didn't want to wait a half hour so I changed the minutes to be every minute. Well that happened to be the only way this works since the loop send_janitor_jobs only runs every 10 minutes and send_janitor_jobs doesn't have a loop of its own.
Anyway I ended up going with the `do_forever` implementation because it was super easy, we know it works, and if that thread ever dies we'll know because there's a loop monitoring its health.
I pushed a foreman image up with these changes, pulled it onto the staging foreman instance, restarted the foreman, made sure it started all the threads, made sure it …

Makes the Foreman reliably dispatch Janitor jobs every half hour.

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
infrastructure/deploy.sh
infrastructure/instances.tf

https://github.com/AlexsLemonade/refinebio/issues/746
The API instance takes long enough to spin up that the deploy.sh script would try to launch the container on it before it was ready. This makes the initial container launch be handled by the instance startup script and subsequent updates to the API are managed remotely via deploy.sh.
This also removes the instance protection for the API instance because sometimes it needs to be cycled and not being able to delete it breaks the deploy.
No functional tests yet, going to test in staging deploy.

Fix deploys when API instance needs to be cycled.

---

workers/data_refinery_workers/downloaders/utils.py

N/A, failing CI: https://circleci.com/gh/AlexsLemonade/refinebio/8975
The CI box doesn't have enough RAM for our normal calculation of MAX_DOWNLOADER_JOBS_PER_NODE to work on it. Therefore made it so that value will never go below 5 so we still can run a few jobs at a time on dev and in tests.
This is all about CI.

Fix downloader tests by adding floor to MAX_DOWNLOADER_JOBS_PER_NODE

---

infrastructure/init_terraform.sh

N/A came up while running staging deploy using latest deploy box code
The `.terraform` directory contains a terraform.tfstate file containing backend configuration information like:
```
{
"version": 3,
"serial": 2,
"lineage": "c7e9df1f-5f53-6da7-57d1-331032e3a0b0",
"backend": {
"type": "s3",
"config": {
"bucket": "refinebio-tfstate-deploy-staging",
"key": "terraform-circleci.tfstate",
"region": "us-east-1"
},
"hash": 17430002091488791519
},
"modules": [
{
"path": [
"root"
],
"outputs": {},
"resources": {},
"depends_on": []
}
]
}
```
This means that after having run `terraform init` on a box, that subsequent inits will try to use the same lineage-id, fail to do so, and then decide to start over. Or something like that. I'm not 100% sure what terraform does under the hood, but the end …

Remove stack-aware terraform config.

---

.circleci/config.yml

N/A https://circleci.com/gh/AlexsLemonade/refinebio/9082 failed
We hit a:
> failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/R/site-library/pd.genomewidesnp.6/extdata/pd.genomewidesnp.6.sqlite: no space left on device
error in the above-mentioned build. This was something we had been seeing before turning Docker Layer Caching off because if the cache is warmed on the volume that gets used by CircleCI for docker, then there may not be enough space to fit all of our images. This manifests itself by us not having enough room to download the Affy image onto it.
The solution I've come up with is to just not use The docker layer caching feature for the Affy image. However whether to use that feature or not is job-specific setting so I had to break them …

Isolate affy image tests and make them not use DLC

---

foreman/data_refinery_foreman/foreman/main.py

N/A came up during staging test.
In https://github.com/AlexsLemonade/refinebio/pull/773 I added nomad_job_id to SurveyJobs, which means all existing SurveyJobs can't even make a request to nomad because there's no ID to format into the URL. This means that the Foreman would spin forever on them because it would never mark them as retried and instead just throw an exception on every job like that every time it loops. Very chatty.
I had some jobs sitting in my local database from #773 so I'm testing this on them.

Make Foreman support existing surveyor jobs

---

common/data_refinery_common/models/models.py

N/A but Ariel mentioned his hard drive got filled up while crunching some data locally.
I think we added this to `delete_local_file` for computed files because since we don't upload files while running locally, if you remove the computed file then after processing you end up with nothing. However I can't think of a good reason to have it on the original files, so I think we should remove it. However I may have forgotten the reason.
N/A very minor local-only change, unit tests should be sufficient.

Delete original files after processing locally.

---

api/data_refinery_api/views.py

Hopefully a fix for https://github.com/AlexsLemonade/refinebio/issues/785, disables rendering of the widget that wasn't performant. Running a scale test with Dilla now.

Prevent Filter Rendering With NoMarkupDjangoFilterBackend

---

infrastructure/networking.tf

HOTFIX
We got hit with some downtime because of this. All CF distributions will now have the `www.` alternate CNAME, but since only one will be connected in the DNS this will only impact prod, but will potentially allow us to do blue/green deployments in the future if we want to go that route.
This has been set manually for now so now immediate change is required, but this will prevent breakage in the future.

Always have a wwww.refine.bio alternate CNAME on the CF distribution

---

infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
infrastructure/nomad-configuration/server-instance-user-data.tpl.sh

https://github.com/hashicorp/nomad/issues/4864
Part 1 of hacks to get around Nomad being a pile of hot garbage.
Nomad will die some times. This makes sure that if it goes down, we make it come back up.
This isn't really a solution since the underlying problem is still there, but at least it'll come back up if it can - which it probably can't.
From the `monit` log, you can see it working:
```
[UTC Nov 13 20:40:10] info     : 'ip-10-0-122-116.ec2.internal' Monit 5.16 started
[UTC Nov 13 20:45:10] error    : 'nomad' '/bin/bash' failed with exit status (1) -- Error querying jobs: Get http://127.0.0.1:4646/v1/jobs: dial tcp 127.0.0.1:4646: getsockopt: connection refused
[UTC Nov 13 20:45:10] info     : 'nomad' trying to restart
[UTC Nov 13 20:45:10] info     : 'nomad' start: …
```

Start Nomad Servers with Monit

---

foreman/data_refinery_foreman/surveyor/array_express.py
foreman/data_refinery_foreman/surveyor/test_array_express.py

https://github.com/AlexsLemonade/refinebio/issues/761
https://github.com/AlexsLemonade/refinebio/issues/840
We found an edge case for AE's API. This handles that edge case.
This should behave the same for the common scenario where protocol_text is a string, but will be slightly sophisticated in cases where it's actually a list that includes a bit of garbage.
I am currently running a test where nomad is running locally and:
```
./foreman/run_surveyor.sh survey_all --accession E-MEXP-2381
```
generates a downloader job which makes a processor job. I'm going to make sure this completes all the way through successfully so there's no chance the metadata messes with anything.

Handle rare cases where protocol text is a list.

---

infrastructure/deploy.sh

https://github.com/AlexsLemonade/refinebio/issues/796
The old strategy for killing nomad jobs was to loop through them all with bash, kill each job in a background process, and then wait for all the processes to complete. However this ended up blowing out our RAM usage very heavily causing the issue reported in #796. (At least this what I think crashed it.)
This changes it so we only fire off 500 background processes at a time before waiting for them to complete so we won't have so many running at once.
Testing this was harder than implementing it, but what I did was:
* Modified `deploy.sh` so only the nomad killing part ran and that the Nomad address was set to my local instance of Nomad.
* Modified `run_nomad.sh` so it ran in server …

Kill nomad jobs in groups of 500 during deploys

---

.circleci/remote_deploy.sh
.circleci/update_docker_img.sh
common.sh
infrastructure/deploy.sh

https://github.com/AlexsLemonade/refinebio/issues/784
So I'm not entirely sure exactly what happened to cause this or how to prevent it. My best guess is that it's a network issue or something that Docker didn't handle properly so it failed to upload the image but still thought it was successful. Since:
* It's not clear how to reproduce this behavior
* It's not a sure thing that there's only one way it could happen
* And this has only happened once in many deploys
It seems the best way to prevent this is to just make sure the deploy fails so it can be retried. However I don't want to automate the retry in case there is something else going on. It could be really annoying to have this spin without failing for a while only to discover that something actually needed to be fixed.
- Bugfix …

Add additional check in case weird docker error happens.

---

common/data_refinery_common/message_queue.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py
foreman/data_refinery_foreman/surveyor/management/commands/surveyor_dispatcher.py
foreman/data_refinery_foreman/surveyor/test_end_to_end.py
workers/illumina_dependencies.R
workers/install_gene_convert.R

https://github.com/hashicorp/nomad/issues/4864
Nomad is garbage, part two.
We keep all of the job needs in the database, so we don't need to have all of the stuff dispatched to a queue anyway. This sets an arbitrary limit on the number of dispatched survey jobs at a time. It looks like our problems mostly started at >100,000 jobs, so the new limit of 1000 should be safer without limiting our throughput.
New test added. Currently running, might fail due to some unrelated R garbage.

Set Limit To Maximum Concurrent Survey Jobs

---

.circleci/remote_deploy.sh
.circleci/run_terraform.sh
infrastructure/networking.tf

#844 
The changes to infrastructure should make it so we don't trip up creating the staging cloudfront distribution so we can deploy. It also disables cloudfront for dev deploys since we don't need it.
I haven't been able to figure out why `remote_deploy.sh` doesn't die after `run_terraform.sh` fails, but this cleans up the way it is called a bit.
N/A cause this is all deploy related.

Fix the staging domain names and disable cloudfront for dev.

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

N/A a giant backlog of janitor jobs is holding up the staging test,
We don't need to retry janitor jobs since we only need 1 to actually run and they get queued every half hour.
We're gonna test in staging because at this point it'll be quicker to get things running.

Doesn't retry janitor jobs.

---

foreman/data_refinery_foreman/foreman/main.py
infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh

The foreman process died inexplicably (via a hang), and it was not able to automatically recover.
This adds a time-based health heartbeat and uses `monit` to monitor and restart the foreman process based on this health information. 
We already use `monit` elsewhere, this uses a similar pattern.
Testing now with a dev stack now..

Add Health Monitoring to Foreman Process with Monit

---

foreman/data_refinery_foreman/foreman/main.py

N/A came up during staging deploy
Local tests didn't help with this scenario because there was no way to have 'dead' nodes locally. This filters the nodes that we count as active to only those in the `ready` state.
N/A will be tested in staging

Make sure that we only count nodes as active if they are 'ready'

---

common/data_refinery_common/logging.py
common/data_refinery_common/utils.py
workers/data_refinery_workers/processors/transcriptome_index.py

N/A came up because we think we need to recreate a few transcriptome indices but don't want to lose the ones we have.
We don't want to lose data, but every time a transcriptome index is created it replaces the last one for its organism/length. This adds a timestamp so we don't overwrite S3 objects.
None yet, this is only applicable in the cloud so I either need to test it in a dev stack or in the staging stack.

Adds timestamps to the S3 keys for transcriptome indices.

---

api/data_refinery_api/middleware.py
api/data_refinery_api/settings.py
api/data_refinery_api/tests.py

#777 
We want to have the system version in the header of every response coming out of the API. This adds the `X-Source-Revision` header set to the system version on every response.
I hit the experiments endpoint and checked out the headers. Screenshot attached. (The version local1543270996 is correct, it gets generated for running things locally.)

Add system version to every API response as X-Source-Revision Header.

---

foreman/data_refinery_foreman/foreman/main.py
workers/data_refinery_workers/processors/no_op.py
workers/data_refinery_workers/processors/salmon.py

Foreman is polluting the prod logs.
Also includes an explicit death check for missing `'internal_accession'` in AFFY, a logger error message for zerobyte t-indexes and sets a missing `job_context["job"].failure_reason`

Hush Up the Foreman

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

N/A I opened this PR rather than opening an issue about it.
I think the job prioritization code is killing the Foreman thread that retries failed processor jobs. I watched the Foreman thread that retries failed downloader job take over two hours to run the one function. It seemed like that Foreman thread had died so before I left work last night I restarted the Foreman to get it going. Unfortunately it doesn't seem to have helped.
So now I'm temporarily disabling the prioritization code back out until I can optimize it to work at scale.
The unit tests should cover this fine.

Temporarily disable prioritization until it can be optimized to work at scale.

---

common/data_refinery_common/job_lookup.py
foreman/data_refinery_foreman/foreman/main.py

#886 
The foreman made way too many queries while prioritizing jobs. This should make it just a few queries per retry function. Hopefully this is efficient enough to work in prod, but it's hard to be sure without the full scale that prod has.
I tested this locally on ~6.5k downloader jobs using the `retry_failed_downloader_jobs` function. I used `cProfile` to check both the overall runtime and then the runtime for `prioritize_salmon_jops`. these were the results without the change:
For the full function:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
3/1    0.000    0.000  126.338  126.338 {built-in method builtins.exec}
1    0.000    0.000  126.338  126.338 …
```

Use prefetch_related to optimize job prioritization queries

---

foreman/data_refinery_foreman/surveyor/external_source.py
foreman/data_refinery_foreman/surveyor/test_external_source.py

N/A came up while I was considering what to queue next.
Turns out we haven't surveyed all the experiments we wanted to thus far, so we should requeue them, but this means we wanna make we don't requeue the work we've already done.
The other function that queues Downloader jobs was already making this check, but this one wasn't.
I think the unit test covers this well.

Prevent surveyor jobs from requeuing work we've already done.

---

foreman/nomad-job-specs/surveyor.nomad.tpl
format_nomad_with_env.sh
run_nomad.sh
workers/data_refinery_workers/downloaders/utils.py
workers/data_refinery_workers/processors/utils.py
workers/nomad-job-specs/affymetrix.nomad.tpl
workers/nomad-job-specs/downloader.nomad.tpl
workers/nomad-job-specs/illumina.nomad.tpl
workers/nomad-job-specs/janitor.nomad.tpl
workers/nomad-job-specs/no_op.nomad.tpl
workers/nomad-job-specs/salmon.nomad.tpl
workers/nomad-job-specs/smasher.nomad.tpl
workers/nomad-job-specs/transcriptome.nomad.tpl

N/A, just trying to make things better
Handles SIGINT as well as SIGTERM, sets kill_timeout to 30s, makes system_version configurable when running run_nomad.sh locally.
I noticed on a nomad-spawned docker container that the `StopTimeout` setting was only 5 seconds. I feel like I sometimes see our jobs die in a non-graceful fashion. It makes me sad so I decided to try and figure out if I could change the StopTimeout. I could and while I was at it I noticed that Nomad sends tasks SIGINT instead of SIGTERM. I'm not super sure what that ends up meaning for the containerized process, but why not handle both? It's easy!
WIP

Try to make jobs die more gracefully.

---

workers/data_refinery_workers/processors/janitor.py
workers/data_refinery_workers/processors/test_janitor.py

n/a
Many of the volumes were filling due to old .sra files from September, etc. This gives the Janitor the ability to purge them.
Please read this code thoroughly to make sure this all works as intended!
New assertions

Add Support for Purging Complete SRR/ERR/DRR Objects in JANITOR

---

README.md
format_nomad_with_env.sh
workers/nomad-job-specs/create_qn_target.nomad.tpl

n/a
It's a pain in the butt to copy the prod env to a client to create a prod QN target, so this creates a nomad job spec for creating QN targets.
It'd be great if you could test this locally since our Nomad job register setup doesn't work on OSX, so I haven't tested this yet.

Adds a Nomad Job Specification for Creating QN Targets

---

foreman/data_refinery_foreman/foreman/main.py

n/a
Some AFFY jobs are being OOM killed, then retried with the same RAM amount, so they get OOM killed again:
```
$ nomad status a15e2f73
ID                  = a15e2f73
Eval ID             = 4623fa6b
Name                = AFFY_TO_PCL_25_2048/dispatch-1544205942-f5fdcf90.jobs[0]
Node ID             = 313cf4bc
Job ID              = AFFY_TO_PCL_25_2048/dispatch-1544205942-f5fdcf90
Job Version         = 0
Client Status       = failed
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 5m54s ago
Modified            = 2m24s ago
Task "affy_to_pcl" is "dead"
Task Resources
CPU       Memory   Disk    IOPS  Addresses
1024 MHz  2.0 GiB  10 MiB  0     
Task Events:
Started At     = 2018-12-07T18:07:56Z
Finished At    = 2018-12-07T18:08:54Z
Total …
```

Increase RAM amounts when retrying failed AFFY jobs

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

#902 
So I'm not sure if this will actually prevent the bug that caused #902 or not, but I cannot reproduce the bug so I can't verify that I've fixed it. However https://stackoverflow.com/questions/8242837/django-multiprocessing-and-database-connections makes me think that Django database connections may have issues with multi-threading, and there's not really any good reason for the Foreman to use threads anyway, so I think this is a good change that may or may not fix the issue in #902.
I've also made sure the logging isn't too excessive when Nomad is down.
I've tested how the Foreman behaves when Nomad is down and I've seen it queue some downloader jobs but I should probably run a few more tests once I'm done testing #904

De-thread the foreman and otherwise cleanup/improve it.

---

workers/data_refinery_workers/processors/salmon.py

Makes `fasterq-dump` use all available cores and uses `timeout` in `subprocess.run` to avoid connection timeout nastiness sooner.

Make fasterq-dump Faster and More Robust

---

workers/data_refinery_workers/processors/salmon.py

`-e 64` makes it a lot faster if there is only one job at a time on a machine, but a lot slower if there are lots. This restores the default behavior with a comment about -e and raises the overall timeout. 

HOTFIX: Restore fasterq-dump to default behavior, raise timeout

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

#832 
Use `prefetch_related` to reduce the number of DB queries that are done when fetching detailed sample information.
Right now, in order to get detailed sample information we have to send the accession codes of all samples, this makes the urls very long and causes issues like https://github.com/AlexsLemonade/refinebio-frontend/issues/121#issuecomment-404906582. To address this, I added here a new parameter `experiment_accession_code` to request the samples associated with a given experiment.
For reference, here are the DB queries for `/samples/?experiment_accession_code=GSE16254&limit=10`.
```sql
(0.019) SELECT "experiments"."id" FROM "experiments" WHERE "experiments"."accession_code" = 'GSE16254'; args=('GSE16254',)
(0.035) SELECT COUNT(*) AS "__count" FROM "samples" INNER JOIN …
```

Optimizations for `/samples` endpoint

---

workers/nomad-job-specs/create_qn_target.nomad.tpl

n/a
QN Target job spec has a Smasher requirement, but even the prod smasher instance doesn't have the RAM needed to run the QN Target command. This removes the constraint.

Remove Smasher Constraint from QN Target Jobs

---

workers/nomad-job-specs/create_qn_target.nomad.tpl
workers/nomad-job-specs/smasher.nomad.tpl

https://github.com/AlexsLemonade/refinebio/issues/944
This is not a fantastic solution so far, a simply bump of the smasher job size.
It won't help with notifications after OOM, and it's not even that much more RAM - the t3 large only has 16GB total, so I don't think we'll be able to realistically allocate more than 12 or so without having to worry about the system baseline usage. If we need more, we'll need to increase the smasher instance size (and elasticity) or do a deep dive into how the smasher process uses RAM.

Increase Smasher RAM

---

infrastructure/variables.tf

Current Smasher instance type simply isn't large enough to Smash large experiments without OOMing.

Raise Smasher Instance Type

---

README.md
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py
workers/data_refinery_workers/processors/test_utils.py

https://api.refine.bio/dataset/3ce6efda-1116-446e-8613-d72e5fb0c49e/?format=json
A missing file causes total smash failure, which sucks. This errors and continues smashing rather than failing totally.

Skip Missing Smash Files Rather Than Failing Totally

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py
workers/run_tests.sh

https://github.com/AlexsLemonade/refinebio/issues/944
A single mislabeled sample can cause a whole Smasher to output nothing, as there are no overlapping identifiers.
This change makes it such that if smashing a frame causes the length to drop to zero, that frame is reverted and added to the unsmashable samples list.
New test

Prevent Mislabeled Samples From Causing Bad Smashing and QN Target Creation

---

api/data_refinery_api/views.py

N/A
@kurtwheeler realized that we were counting all samples in the `/stats` endpoint. This ensures that only processed samples are included.

Use processed objects in stats endpoint

---

api/data_refinery_api/views.py

N/A
Avoids counting duplicate samples on the search filters. The SQL query to calculate the technology filter group is as follows (the others are similar):
```sql
SELECT "experiments"."technology", COUNT(DISTINCT "experiment_sample_associations"."sample_id") AS "count" 
FROM "experiments" LEFT OUTER JOIN "experiment_sample_associations" ON ("experiments"."id" = "experiment_sample_associations"."experiment_id") LEFT OUTER JOIN "samples" ON ("experiment_sample_associations"."sample_id" = "samples"."id") 
WHERE ("experiments"."is_public" = true AND "samples"."is_processed" = true AND "samples"."is_public" = true) 
GROUP BY "experiments"."technology"; args=(True, True, True)
```
The key difference is the `COUNT(DISTINCT sample_id)` which counts the samples correctly, but impacts the …

Fixes filter count on search page

---

foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py

N/A tests are failing in dev
Either I'm crazy or C. elegans got put in a different Ensembl division overnight...
The whole reason I fixed #709 with #973 was because I wanted to add some tests to my tximport branch for the C. elegans organism so I needed to create a transcriptome index for it because it was in the EnsemblMetazoa division. So like, I'm pretty sure it was in there, especially because I ran that test yesterday before I committed it and it passed. So I guess they decided to move C. Elegans from EnsemblMetazoa to Ensembl, which broke the tests.
This just uses another organism that actually is in the EnsemblMetazoa division to test that the division works.
Tests pass

Fix transcriptome test that is failing in dev

---

infrastructure/instances.tf

AWS ES requires an extremely specific role with a specific name which can only be created once per account. We've already created it for our account and don't need it to be managed by prod/staging CI. So dumb.

Describe ES Service Role Issues

---

api/data_refinery_api/serializers.py
api/data_refinery_api/views.py
common/data_refinery_common/models/models.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/472
Right now, to render all the information in the downloads page we have to make two requests for information about a dataset:
- `/dataset/${dataset_id}`
- `/dataset/${dataset_id}/?details=true`
This PR changes it so that all information can be returned when making a single request to the second one. This urls avoids returning details for each samples and instead returns the accession codes of the samples grouped by organisms. This is needed for this section:
Also added some optimizations to the queries with `prefetch_related`
Api

Improve downloads API

---

infrastructure/networking.tf

N/A
Create a new redirection rule, that shows `/index.html` for 403 errors. Since all errors are handled in the frontend.
We should test this on staging.
The config that will be created:

Fix direct access on staging

---

common/data_refinery_common/models/documents.py

n/a
It was bothering me that we could only search for "medulloblastoma" but not for "medullo"
This adds ngram based indexing to the ES search results such that substrings between 4 and 12 characters will also hit.
Tested manually.

Use Ngrams for More Robust ES Search

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

I can't explain why, but this order of events is necessary else the application gets 400 errors from ESS. This fixes it. I think.

Nuke and Rebuild ES Index Upon API Deployment

---

api/data_refinery_api/serializers.py
api/data_refinery_api/tests.py

n/a
Investigating https://github.com/AlexsLemonade/refinebio/issues/1001 is hampered because then QN target endpoint isn't very helpful. This adds more information so that it is.

Make QN Target Endpoint Include Annotations

---

workers/data_refinery_workers/processors/management/commands/create_qn_target.py
workers/nomad-job-specs/create_compendia.nomad.tpl

We have support for creating all QN targets at once, although this isn't usable in production since the nomad job spec doesn't support it, and the templating we use couldn't handle it anyway. This is a hack to allow using `ALL` as an organism - we already use `ALL` elsewhere in the app, so at least that's consistent.

Allow supplying ALL as an organism to create_qn_target

---

api/data_refinery_api/views.py

This is a really cool ES feature.
The problem is we're currently ordering experiments by the total number of samples, including those unprocessed. This lets us affix `&num_processed_samples__gt=0` to our query string to filter those out.
FRIGGIN RAD

Add support for num_processed_samples__gt=0

---

infrastructure/deploy.sh
infrastructure/instances.tf

N/A came up during most recent deploy
I forgot to populate the Terraform Variable `var.elasticsearch_port` in my last PR that used it.
The script for restarting the API without cycling it's instance was missing a couple env vars as well.

[HOTFIX] Fixes a couple places where we aren't passing env vars correctly.

---

.circleci/update_docker_img.sh

N/A Came up during hotfix deploy
We added checks for hotfix tags, but missed one spot. This remedies that.

[HOTFIX] Updating docker images wasn't allowed for hotfixes -- fixed!

---

common.sh

N/A came up during hotfix for hotfix deploy
Our checks for when it's safe to deploy work well, but too well and were stopping hotfixes.

[HOTFIX] Fixes the check for whether or not a deploy to can run

---

foreman/data_refinery_foreman/foreman/management/commands/organism_shepherd.py
foreman/data_refinery_foreman/foreman/management/commands/test_organism_shepherd.py

#227 
I think the organism spun while failing to requeue a particular job for a while. I'm not sure why it couldn't queue it, so I've added some additional logging. I also removed the looping bug that made the shepherd get stuck on it.
Additionally I added some logging so I can see the prioritized list of experiments that the organism is going to queue.
Also, for the time being we only care about finishing RNA-SEQ experiments so I've added an RNA-SEQ filter that I should have had before.
I ran the command locally and saw it requeue only the expected jobs successfully.

Increase visibility for organism shepherd

---

infrastructure/variables.tf

Since we keep manipulating this value as needed via the web console, let's get rid of this expensive default value.

Zero Default Target Capacity

---

.circleci/config.yml

N/A came up because I saw a deploy happen twice for one tag.
We made the hotfix deploy job run for tags that match /v.*-hotfix/, but we didn't stop it from running for tags that match /v.*/, which includes all the tags that would match /v.*-hotfix/. This makes it so the normal deploy ignores hotfix tags.
N/A this needs a hotfix tag to be tested.

Prevent hotfix deploys from running the deploy step twice.

---

.circleci/config.yml

#1048 
I misspelled this word, so it broke the config and made all jobs not run.
Look they're actually running: https://circleci.com/workflow-run/5205632b-2b17-44ca-8502-327b0e09423d

Fix typo that broke all of circleci.

---

workers/data_refinery_workers/downloaders/geo.py
workers/data_refinery_workers/processors/utils.py

#227 
SRA downloader jobs were finishing instantly because they thought the file wasn't downloaded.

Reset the is_downloaded field to false if we detect that a file isn't downloaded

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/management/commands/create_compendia.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_compendia.py
workers/data_refinery_workers/processors/test_smasher.py
workers/nomad-job-specs/create_compendia.nomad.tpl

Two bugfixes in here: 
- explicitly out an experiment's samples that are of the wrong organism type,
- Properly handle unicode metadata, guard against against TSV writing fail

Filter Wrong Organism Samples from Compendia // Guard Against Unicode Metadata

---

workers/data_refinery_workers/processors/utils.py

Set the value of an enum on the downloader jobs rather than the enum object itself.

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/nomad-configuration/client.tpl.hcl

#227 
I've observed 5 concurrent SALMON jobs as being enough to make fasterq-dump timeout. Therefore this uses Nomad's RAM reservation to make it so that 4 SALMON jobs will fit on a single instance, but not 5.
This can be undone once Nomad releases its tmpfs feature.
From one of our client instances:
```
ubuntu@ip-10-0-81-222:~$ TARGET_RAM=141072
ubuntu@ip-10-0-81-222:~$ TOTAL_RAM=$(free -m | grep Mem | tr -s ' ' | cut -d\  -f2)
ubuntu@ip-10-0-81-222:~$ RESERVED_RAM=$((TOTAL_RAM - TARGET_RAM))
ubuntu@ip-10-0-81-222:~$ echo $RESERVED_RAM
350733
ubuntu@ip-10-0-81-222:~$ echo $TOTAL_RAM
491805
```
I also tested the `sed` command by running it against client.tpl.hcl and making sure it replaced `CHANGE_ME` properly.

Reserve RAM on client instances so not more than 4 SALMON jobs can run at once.

---

infrastructure/instances.tf
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
workers/data_refinery_workers/processors/salmon.py

#227 
I want to run 3 of the smallest instance type, so if we get a bigger one it throws that off, so therefore I've temporarily disabled them.
Also fasterq-dump is still failing ~80% of the time. I'm trying to address this two ways:
1. Decreaase the number of concurrent Salmon jobs from 4 to 3
2. Increase the fasterq-dump timeout to allow it to complete.
I think 2 is justifiable based on the average file sizes for successful Salmon jobs
```
data_refinery=> select AVG(size_in_bytes) from original_files where id in (select original_file_id from processorjob_originalfile_associations where processor_job_id in (select id from processor_jobs where pipeline_applied='SALMON' and success ='t' order by last_modified desc limit 20));
avg         
---------------------
4902683849.50000000
```
vs. …

Hacks/optimizations to try to get fasterq-dump to actually succeed for Zebrafish

---

workers/data_refinery_workers/processors/management/commands/create_qn_target.py

I'm not sure how much of a huge effect this will actually have, but there is a lot of active filtering that happens during QN target creation.

Explicit organism filtering on QN target creation

---

common/data_refinery_common/models/documents.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/525
`whitespace` tokenizer doesn't break on `-` like the default one does.

Dont Break on - for Technology Field in ES

---

api/data_refinery_api/serializers.py

#1071 
Remove `files` from the response of the API, on the detailed samples endpoint (`/samples`).

Remove `files` from the sample details serializer

---

infrastructure/networking.tf

I enabled it manually on aws. But adding it here so that it gets activated on the next deploy.
https://github.com/AlexsLemonade/refinebio-frontend/issues/543

Enable cloudfront compression by default

---

foreman/data_refinery_foreman/surveyor/test_end_to_end.py
workers/data_refinery_workers/processors/utils.py

#1068 
This is a bandaid for #1068 because:
* We've processed the microarray data that we want to for now so we don't need to recreate these jobs at the moment.
* We want to get RNA-Seq data back up and processing, we don't process RNA-Seq data from GEO anyway.
* A proper fix for #1068 might be a bit tricky to get right because GEO metadata is so inconsistent.
This is straightforward, should be testable in our staging test today.

Prevent samples from GEO from having their downloader jobs recreated.

---

infrastructure/deploy.sh

N/A came up during staging test because nomad never got started.
Seems like EC2 instances take longer to initialize now, so a 5 minute timeout for a nomad server coming up and getting Nomad running on it no longer is enough.
N/A infra related

Bump timeout for Nomad and fail deploys if Nomad never comes up.

---

infrastructure/deploy.sh

N/A came up while trying to run a staging deploy for #932 
Trivial

If then, while do. Why do we even need the second words?

---

common/dockerfiles/Dockerfile.common_tests
workers/dockerfiles/Dockerfile.affymetrix
workers/dockerfiles/Dockerfile.compendia
workers/dockerfiles/Dockerfile.downloaders
workers/dockerfiles/Dockerfile.smasher

N/A Github alerted about vulnerable dependencies.
Just bumped django versions. Also fixed requirements.txt files that had been manually modified instead of just adding the deps to requirements.in.
Making these changes somehow made pip3 want bump the version of rpy2 to something that needed an additional apt-package. Rather than figure out why it wouldn't install I just pinned rpy2's version.

Pin ryp2 in all dockerfiles that install it.

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

#1093 
`organism__name` isn't a field on organism indices, so we gotta actually look up the organism object first.
Unit tests.

Fix transcriptome-indices endpoint.

---

README.md
install_nomad.sh

Nomad 0.9.0-beta3 is a dud: https://github.com/hashicorp/nomad/issues/5367
Reverts back to last known "good" version.
Also removes a documentation example that doesn't work anymore.

Revert Nomad from 0.9.0-beta3 to 0.8.3 

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py
common/data_refinery_common/models/models.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/453
close https://github.com/AlexsLemonade/refinebio/issues/938
Adds the required data for the executive dashboard, specifically:
- processing speed (number of samples processed in the last hour)
- breakdown of samples by organism and technology
Also includes several optimizations for the db queries in the `/stats` endpoint. Before we were making at least 112 queries (ref #938) and now it's only **20**. Biggest improvement was being able to calculate data for each line graph (samples created over time, jobs over time etc) in a single query.
Tested locally
Example result 
```json
{
"survey_jobs": {
"total": 57167,
"pending": 27595, …
```

Dashboard stats endpoint

---

infrastructure/instances.tf

N/A came up during deploy.
We had 
```
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/home/user/data_refinery_foreman/settings.py", line 168, in <module>
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     'hosts': get_env_variable('ELASTICSEARCH_HOST') + ":" + get_env_variable('ELASTICSEARCH_PORT')
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/utils.py", line 32, in get_env_variable
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     raise ImproperlyConfigured(error_msg)
```
Happen during a prod deploy. Seems like the foreman's userdata script was formatted before ES came up enough to have a hostname for it.
- Bugfix …

Make the foreman depend on the ES server so it can use its hostname.

---

common/data_refinery_common/models/models.py
workers/data_refinery_workers/processors/management/commands/correct_affy_samples.py

https://github.com/AlexsLemonade/refinebio/issues/968
https://github.com/AlexsLemonade/refinebio/issues/963#issuecomment-451249805
https://github.com/AlexsLemonade/refinebio/issues/967
This is related to #1091 which corrects the way we survey GEO. That PR prevents us from mislabelling more Microarray data as RNA-Seq. This PR corrects the data that was already mislabelled.
- Data migration
I surveyed GSE69111 to get all of its samples mislabelled as RNA-Seq. I then ran this command and it corrected ONLY the microarray samples back to microarray.
I've retested this since fixing the platform detection stuff:
```
10 | GSM1692995     | postnatal day 1 (p1), biological rep3                    | GEO             |                    |                 |                           | t       | …
```

Correct Affy samples mislabelled as RNA-Seq

---

api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/548
close https://github.com/AlexsLemonade/refinebio/issues/768
Adds stats about how the datasets are aggregated for the dashboard and also volume of data processed over time.
Test endpoint 
```json
"dataset": {
"total": 164,
"aggregated_by_experiment": 147,
"aggregated_by_species": 0,
"scale_by_none": 155,
"scale_by_minmax": 2,
"scale_by_standard": 7,
"scale_by_robust": 0,
"timeline": [
{
"start": "2018-10-01T00:00:00Z",
"total": 11,
"total_size": 0
},
{
"start": "2018-12-01T00:00:00Z",
"total": 1,
"total_size": 0
},
{
"start": "2018-09-01T00:00:00Z",
"total": 13,
"total_size": 0
},
{
"start": "2018-11-01T00:00:00Z",
"total": 29,
"total_size": 0
}
]
},
```

Add dataset stats

---

workers/data_refinery_workers/processors/requirements.txt
workers/data_refinery_workers/processors/salmon.py

Using `fasterq-dump` at scale causes disk thrashing that kills our overall throughput. We tried solving this using ramdisks so that `fasterq-dump` just uses RAM rather than disk, but Nomad isn't ready for that as ramdisks aren't supported in `0.8.0` and don't work properly in `0.9.0-beta3`.
This solution uses named pipes created with `mkfifo` to pass the output from `fastq-dump -Z` from the `stdout` directly into Salmon. This doesn't use any disk IO as long as there is enough RAM available so that no paging is necessary.
I think this is probably a short-term fix but I think it'll get the job done. 
Because we don't have direct access to FASTQ files directly any more, we can't use `fastqc`, so that step gets skipped entirely. Similarly, we can't use our old technique for calculating the …

Replace `fasterq-dump` With `fastq-dump -Z` and Named Pipes

---

infrastructure/instances.tf

Welp, this one is terrifying.
For some reason, all of of our PG servers are at 9.6.11. Our terraform value sets it to 9.6.6. 
It has been 9.6.6 for a year:
And yet the prod instances are now at 9.6.11:
So updating a stack with TF now causes a downgrade error:
This updates the TF stack, but doesn't explain what the heck actually happened.
My guess is that AWS upgraded us and didn't tell us? I have no idea how that's possible. That seems like dangerous behavior.
- Spooky ghosts (ghosts have made changes that can't be explaiend)

Set PG engine version in TF to match engine version in production

---

foreman/nomad-job-specs/surveyor.nomad.tpl
foreman/nomad-job-specs/surveyor_dispatcher.nomad.tpl

From IRL discussion during testing.
This allows us to start downloading and processing sooner without having to wait for long running surveyors to continue. Surveyors will be added when there is nothing important left to do.

Makes Surveyors Lower Priority Than Downloaders

---

api/data_refinery_api/serializers.py
api/data_refinery_api/tests.py
api/data_refinery_api/views.py
common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/foreman/main.py

#731 
In order to be able to lock down our S3 buckets we need to provide a mechanism by which people can still get the data that they're supposed to. The mechanism this adds is that ComputedFile resources will have a `download_url` field if the request included an `API_KEY` header (or if the key was present in the POST-data for datasets). This `download_url` is a temporary presigned URL from AWS which allows access to the resource using that URL for a few hours.
In addition to the unit tests, I also tested this by making requests against the API using curl/the browser.

Provide access to resources that should still be accessible even once we lock down our buckets

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

close #1111 
The regex won't match jobs like:
`TXIMPORT`
`CREATE_COMPENDIA`
`CREATE_QN_TARGET`
But at least it won't fail for those. Should we report these in the stats?
Tested locally with dummy data for the nomad jobs.

Use a regular expression when parsing job type and volume id

---

workers/data_refinery_workers/downloaders/test_sra.py

This is a test for a feature we no longer support that's blocking deployments. This PR simply comments it out in case we do want to re-enable this feature later, but it seems like ENA Aspera is down right now and it's causing a blockage.

RM ena-sra Test

---

common/data_refinery_common/migrations/0017_auto_20190312_2011.py

We are too big to use `Sample.objects.all()`. This uses a paginator instead.

Use Paginator During Migration 0017

---

infrastructure/instances.tf

Current behavior requires an undocumented manual process to our otherwise automatic deployment system. This removes that requirement.

Disable Termination Protection

---

README.md
workers/data_refinery_workers/processors/salmon.py

Sometimes files downloaded have a '.sra' extension, but apparently they don't.
This uses the source url rather than the file extension.

Detect SRA based on source, not file extention

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py

https://github.com/AlexsLemonade/refinebio/issues/1137
The KS test required at least two inputs. Now we skip the KS test and warn if the input only has a single sample.

Allow QN Normalizing Single-Sample Datasets

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh

https://github.com/AlexsLemonade/refinebio/issues/1103
Uses the same `monit` technique as the servers on the clients.

Run nomad on agents and smasher with Monit

---

workers/nomad-job-specs/downloader.nomad.tpl

4096 seems way more than needed for a single downloader.

Lower downloader RAM requirement

---

workers/data_refinery_workers/downloaders/test_array_express.py
workers/data_refinery_workers/downloaders/utils.py

N/A  came up during prod tuning
We're hitting different NCBI servers than we were before. This changes the number of downloader jobs that we'll run in parallel to reflect the speed and of those servers and the size of our cluster.
This also reenables harakari for downloader jobs so that these limits actually do something.
Unit tests cover it.

Changes our calculations for max number of downloader jobs

---

foreman/data_refinery_foreman/surveyor/geo.py
foreman/data_refinery_foreman/surveyor/test_geo.py

https://github.com/AlexsLemonade/refinebio/issues/1102
`channe1_protcol` often had conflicting brands, if we use the pretty_platform instead, it actually works out fine in most cases with the exception of the NextSeq500, so we just have a special case for that.
New test added.

Use pretty_platform as MFG source with NextSeq exception, Test

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

https://github.com/AlexsLemonade/refinebio/issues/1155
The Foreman got OOM-killed because it was pulling too many objects from the DB at once. This uses pagination so we only pull 200 at a time.
The unit tests do a good job of testing this because functionally nothing should have changed other than our memory usage. I'll make sure this actually does well on staging before pushing to prod though.

Make foreman use pagination, remove some outdated comments from tests.

---

workers/data_refinery_workers/processors/smasher.py

I failed a large smash because of just barely failing a Kolmogorov Smirnov test, it'd be a much better experience to at least give users something rather than a self-imposed error message and no data. Moves the test result into the metadata rather than a job failure. We can revert this but I kind of need it for debugging anyway.

Move KS failure to KS warning

---

api/data_refinery_api/settings.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/560
Adds `API-KEY` to the list of `Access-Control-Allow-Headers`, otherwise we'll get a CORS error:
```
Access to fetch at 'https://api.refine.bio/dataset/b5331a10-aa12-4f3f-b056-c11a28ce120d/' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field api-key is not allowed by Access-Control-Allow-Headers in preflight response.
```
Not sure how to test this.

Allow API-KEY header

---

workers/data_refinery_workers/processors/salmon.py
workers/data_refinery_workers/processors/test_salmon.py

https://github.com/AlexsLemonade/refinebio/issues/1163
Makes `sra-stat` parsing way more robust, and also sets a low-resolution default so if we're just totally unable to parse the output we can still process the sample.

More Robust sra-stat Parsing

---

workers/data_refinery_workers/processors/salmon.py

https://github.com/AlexsLemonade/refinebio/issues/1167
There is a bug in our version of Salmon. It's already fixed in later versions. This guards against catastrophe in that failure case, since Postgres' JSONField won't accept invalid JSON.

Guard against invalid Salmon JSON output

---

foreman/data_refinery_foreman/foreman/performant_pagination/pagination.py

The imported project was not fully P3 compatible, this should update it enough to be usable.
Pushing this out now, but it'd be good to develop a new test that spans multiple pages so that we would have caught this sooner.

Fixes P2-P3 Error in Imported Project

---

foreman/data_refinery_foreman/surveyor/harmony.py

https://github.com/AlexsLemonade/refinebio/issues/1174
https://www.ebi.ac.uk/arrayexpress/files/accession/E-GEOD-7753.sdrf.txt
now says:
> The resource located at /arrayexpress/files/accession/E-GEOD-7753.sdrf.txt may have been removed, had its name changed, or has restricted access. If you have been granted access, please log in to proceed.
I'm not sure why this disappeared, but it seems like a thing we should be able to handle gracefully and now we can!
The unit tests now pass quietly instead of with a massive amount of logging about how parsing these non-files is broken.

Gracefully handles the case where an array express SDRF file returns a 404.

---

foreman/data_refinery_foreman/foreman/main.py

#1179 
Having the foreman limit how many downloader jobs are in the queue seems to be fixing our database woes because there's a lot less harakiri going on. However 200 is too low because some instances get greedy and take more than their fair share leaving others without any.

Bump num of max downloader jobs.

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py
workers/data_refinery_workers/processors/salmon.py

https://github.com/AlexsLemonade/refinebio/issues/1184
Replaces a hardcoded value with a value based on the number of nodes in the cluster. For 10 nodes, sets a theoretical 10GiB/s max, though I don't think we'll ever get close to this.
Also includes a guard against a semi-rare `sra-stat` failure.

Dynamically Calculate Max Downloader Jobs Limit Based On Nomad Cluster Size

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

#1179
The foreman can pull a lot of pages of jobs to requeue. There can be way more jobs to iterate through than we want to actually queue, so this makes it so that once we hit the queue capacity for each job type we stop looping over the pages of jobs.
They're hard to do for this without the volume of data we have in the cloud.

Break out of foreman pagination early.

---

foreman/data_refinery_foreman/foreman/main.py
workers/data_refinery_workers/downloaders/sra.py

I don't think this will have a huge impact (if anything, it'll have a slight negative impact), but it's possible that adding `-Q -450m` to our ascp calls will make them less likely to knock out the servers.

Make SRA `ascp` settings match `prefetch`

---

common/data_refinery_common/models/models.py
common/data_refinery_common/utils.py
foreman/data_refinery_foreman/foreman/main.py
workers/data_refinery_workers/downloaders/test_array_express.py
workers/data_refinery_workers/downloaders/utils.py
workers/data_refinery_workers/processors/utils.py

N/A some tweaks based off of prod performance.
I don't think the python nomad API was being used correctly. I'm not actually sure what our max downloader jobs limit was, but it seems like it somehow ended up being 1000 based off of how many jobs there were before any nodes came up, which was an issue caused by this bug.
This also makes it so that we start checking downloader jobs immediately rather than waiting two minutes.
This also decreases our main Foreman MIN_LOOP_TIME to 15 seconds from 2 minutes so we don't have downtime in between the foreman queuing work.
This also stops jobs operating on original_files that have been processed.
The unit tests cover this fairly well, I also looked at the actual data getting returned by the Nomad …

Improves the way we count how many nodes are active. 

---

workers/data_refinery_workers/downloaders/utils.py

N/A Found it while looking into #1068 
Before this change:
When a downloader job finishes and tries to queue a processor job, if Nomad is down then the processor job will still be created but the downloader job will fail, causing it to be retried and thereby creating another processor job for the same data.
This fixes that, if Nomad is unreachable then downloader jobs now let the foreman worry about queuing the Nomad job for them.
N/A, this is pretty obvious (although I've tested that nothing obvious breaks)

Don't fail downloader jobs for being unable to queue nomad jobs

---

infrastructure/instances.tf

N/A Came up during a staging test when our Nomad lead server volume filled up.
https://www.nomadproject.io/guides/operations/requirements.html has changed to specify that it takes snapshots so we need more disk space.
N/A hardware

Set Nomad volumes to be appropriate for the NEW requirements.

---

infrastructure/deploy.sh

We failed to have Nomad start up in production in ~12 minutes.
We thought we were giving Nomad up to 15 minutes, but it turns out our time comparison code was buggy. This fixes that.
```
diff=0
(dr_env) kurt@kurtputer:~/Development/refinebio-collab$ start_time=$(date +%s)
(dr_env) kurt@kurtputer:~/Development/refinebio-collab$ while [ "$diff" -lt "15" -a $nomad_status != "200" ]; do sleep 1; let "diff = $(date +%s) - $start_time"; echo $diff; done
5
6
7
8
9
10
11
12
13
14
15
```

Our string comparison was broken :(

---

foreman/data_refinery_foreman/foreman/main.py

N/A we took down NCBI in prod
We took down NCBI because we had too many downloader jobs, probably. This makes it so we'll have fewer downloader jos. Hopefully NCBI can survive the onslaught of 750 downloader jobs.
- Tuning
N/A it's just a tuning parameter.

Bumps our downloader job cap down from 1000 to 750.

---

workers/data_refinery_workers/processors/salmon.py

https://github.com/AlexsLemonade/refinebio/issues/1202
If sra-stat totally screws up, we can at least try to check the metadata for the library strategy to determine the number of reads.

Attempt to read annotations for library strategy if sra-stat fails

---

workers/data_refinery_workers/processors/requirements.in
workers/data_refinery_workers/processors/requirements.txt

This is a great example of why I do not like our requirements.in/requirements.txt pattern - simplejson was used by multiqc, so it tagged that in the requirements.txt file. When multiqc was removed from the requirements.in, it also removed it from the .txt, even thoug we use it elsewhere in the project. This is a bad pattern.
Also why didn't the smasher tests detect this sooner?

Simple JSON import missing

---

common/data_refinery_common/models/documents.py

https://github.com/AlexsLemonade/refinebio/issues/1022
Prevents experiments with completely unsupported platforms from entering the search results. We can use this method to purge data in the future if we want to, but I've never been a fan of that, so this just removes it from the search results.

Apply platform `contained_by` filtering when creating ES index

---

infrastructure/variables.tf
workers/nomad-job-specs/smasher.nomad.tpl

https://github.com/AlexsLemonade/refinebio/issues/944
@cansav09 got a smasher OOM yesterday, 944 wasn't fully resolved for very large datasets.
I'm not sure how it happened (must have been during compendia processing time), but the smasher instance was way way too powerful, this lowers it down to something more sane but raises the RAM usage of each individual job.

Lower Smasher Instance Class, Raise Smasher RAM Usage

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio/issues/1224
I don't know how it was communicated that this worked already, but this was never implemented. Requires that 'organism' is supplied. Tests updated.

Adds ?organism filter to qn_targets API endpoint

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

The organism_id being stored in the result annotations is the object ID, not the taxonomy ID.

Make Those QN Tests Match Reality

---

foreman/data_refinery_foreman/foreman/main.py
foreman/requirements.txt

Suppresses some sporadic nastiness for the requeueing original files without associated samples - but why do we have those? This will help us diagnose.

Better handle og_files without associated samples 

---

infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh

N/A
Our startup script has a 2 minute sleep, so let's have monit wait 4 minutes.
N/A it's monit

Give monit a 4 minute timeout

---

foreman/data_refinery_foreman/foreman/main.py

We're hitting a lot of dbGaPs recently. This makes sure we don't try to download those.

Don't Enqueue dbGaP'ed Samples

---

foreman/data_refinery_foreman/foreman/main.py

#1233 
Reverts #1233.
Chris from SRA said:
> I’m looking for the server policy, but I think connections will be refused if more than 4 simultaneous requests come from the same IP. But I thought that would give a ‘connection refused…’ message
This may have been a new change so reverting this might not help stuff, but in the past we were able to get a lot more throughput with higher job caps, so I'm curious to see if we still can or not. Otherwise we're going to be stuck at a crawl.
- Tuning

Bumps the max downloader jobs back up

---

workers/README_COMPENDIUM.md
workers/data_refinery_workers/processors/create_compendia.py

#983 
We want to include a README that is specific to species compendia downloads. This PR covers the Markdown file that we would include. Backend changes to include this file, rather than `README_DATASET.md`, in a download are still needed.
I've tailored the **Contents** section to be more specific to compendia and I've also added a **Notes and observations** that points users to the analyses that support our processing choices and our series of exploratory data analyses.
N/A

Add compendium-specific README

---

.circleci/config.yml

These tests are not helping us test anything relevant to our current development, but do fail intermittently due to forces outside of our control. Let's prevent bad builds and broken deploys from them.

Temporarily Disable Illumina Tests on CI'

---

infrastructure/users.tf

CI triggered an error for an overweight client policy. This splits it into multiple policies on a per service basis.

Split Large User Client Policy Into Service Parts

---

infrastructure/users.tf

I didn't catch this in time before that last merge. May or may not break functionality during deploy if those previous names conflict.

Correctly Label New Policies

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/permissions.tf
infrastructure/users.tf

The IAM role policy limit is not any individual policy, but the _total_ bytes. Annoying!
The limit is higher for attached policies, so let's try it that way.

No more direct policy attachments

---

api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio/issues/1181
Send the platform accession codes in the search filters instead of the platform names. The FE can query the `/platforms` endpoint to get each platform's formatted name.
I wasn't able to test this locally.

Search filters return platform accession codes instead of platform name

---

api/data_refinery_api/serializers.py
api/data_refinery_api/views.py

fixes https://github.com/AlexsLemonade/refinebio-frontend/issues/611
fixes https://github.com/AlexsLemonade/refinebio-frontend/issues/610
fixes https://github.com/AlexsLemonade/refinebio-frontend/issues/600
https://github.com/AlexsLemonade/refinebio/pull/1109 added a new serializer for the datasets that included the `download_url` when an `API-KEY` header was provided. However also changed how the serializers were initialized, the one we had required information about the request params in order to decide what fields to return.
This PR goes back to using a single serializer, and moves all the logic that decides which fields to return to it's constructor.
The bugs mentioned before were caused because the FE got fields that wasn't expecting when getting details for the dataset.
- Bugfix …

Use a single serializer for the dataset endpoint

---

infrastructure/users.tf

Not only are these now obsolete, they actually silently block the attachment of the same policies to the groups, which required them to be manually attached. AFAIK there's no reason for this other than Terraform being bad.

Nuke Direct Policy Attachments

---

foreman/data_refinery_foreman/foreman/main.py

N/A prod tuning
Prod's going, but we aren't running enough downloader jobs at a time to take advantage of our capacity because our caps are based on SRA's limits.
- Tuning
N/a just tuning

[HOTFIX] Kurtwheeler/bump downloader job cap

---

workers/data_refinery_workers/processors/smasher.py

The Smashed gene column should always be labeled "Gene".

Normalize Smashed Header Format

---

common/data_refinery_common/job_lookup.py
workers/data_refinery_workers/processors/management/commands/run_processor_job.py

Dispatched jobs were failing an early check because this wasn't enumerated. Also improves accompanying logging.

Adds RUN_QN_JOB to Pipeline Enum

---

foreman/data_refinery_foreman/foreman/main.py

N/A Discovered in prod
We were seeing a lot of downloader jobs getting queued... way past our cap. I think this is why and this should fix that!

Fixes the retry_lost_downloader_jobs function so it can't queue too many

---

foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py

#1287 
These tests failed when we were deploying.
```
======================================================================
ERROR: test_correct_index_location_metazoa (data_refinery_foreman.surveyor.test_transcriptome_index.SurveyTestCase)
Tests that the files returned actually exist.
----------------------------------------------------------------------
File "/home/user/data_refinery_foreman/surveyor/test_transcriptome_index.py", line 88, in test_correct_index_location_metazoa
files = surveyor.discover_species()[0]
File "/home/user/data_refinery_foreman/surveyor/transcriptome_index.py", line 284, in discover_species
specieses = r.json()
File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 897, in json
return …
```

Skip more tests

---

infrastructure/cluster_connect.sh
infrastructure/list_hosts.sh

N/A I wanted teh POWAH
This makes lists_hosts.sh and cluster_connect.sh work on both linux and mac.
I've tested these scripts on linux. I had Rich test an early version of the script to make sure the branching worked, but it'd be good to run the full thing and make sure it works.

Make cluster connect work for both linux and mac.

---

workers/data_refinery_workers/processors/illumina.yml
workers/data_refinery_workers/processors/no_op.yml
workers/illumina_dependencies.R
workers/install_gene_convert.R

N/A it broke CI today :(
The theory is that tidyverse doesn't pin any dependencies, so it was updating dplyr despite tidyverse itself being pinned. This installs everything from tidyverse and their dependencies that we need so the image will build successfully and so we won't have issues in the future with this.
The image built successfully locally, here's hoping it's good in CI too!

Fix install_gene_convert.R to not have any version issues ever again?

---

workers/dockerfiles/Dockerfile.transcriptome

#1287 
We changed the version of salmon that the salmon image uses but we forgot to change the version in the transcriptome index too.

Bump salmon version for tx index image.

---

workers/data_refinery_workers/processors/transcriptome_index.py
workers/data_refinery_workers/processors/utils.py

#1302 
I noticed the new organism indices I generated didn't have a salmon version, this is why.
Testing locally (well really on Jackie's computer)

Newest salmon version outputs version number to stdout instead of stderr

---

foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
foreman/data_refinery_foreman/surveyor/transcriptome_index.py

close #1301
Remove usages of the ensembl endpoint that was obsolete (https://rest.ensemblgenomes.org). A few fields were also deprecated like `species["dbname"]`, I removed those usages as well.
The branch [arielsvn/1301-ensembl-use-single-ftp](https://github.com/AlexsLemonade/refinebio/blob/arielsvn/1301-ensembl-use-single-ftp/foreman/data_refinery_foreman/surveyor/transcriptome_index.py) contains changes to use a single ftp server as well, but that is not yet correct. Leaving a reference here in case it's helpful in the future.
Ran tests locally.

Use rest.ensembl.org api endpoint

---

api/data_refinery_api/serializers.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/629
Exposes the field `quantile_normalize` in the dataset endpoint.
Adds small optimizations on the dataset serializers to use cached experiment fields.

Exposes the field `quantile_normalize` in the dataset endpoint.

---

run_nomad.sh

#1261 
These  variables were supposed to not be in double quotes so they disappear if they aren't set.
I couldn't run nomad locally before this change, now I can!

Fix the run nomad script which got broken by the double quote branch.

---

workers/README_DATASET.md

Related to: https://github.com/AlexsLemonade/refinebio/pull/1303 and https://github.com/AlexsLemonade/refinebio-docs/issues/95
Adds information about the `quantile_normalized` field in `aggregated_metadata.json` in the README.md included in a dataset download.

Note `quantile_normalized` field in JSON

---

infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh

N/A came up while recreating the zebrafish compendium
I don't know why we were sending these to /dev/null, but that made it very difficult to debug why Nomad won't start my compendium job.
N/A

[HOTFIX] For whatever reason we were throwing away the logs from the docker daemon

---

workers/data_refinery_workers/processors/qn_reference.py
workers/data_refinery_workers/processors/utils.py

#1257 
I noticed that after deploying #1115 and created a QN target that the QN target got uploaded to the wrong bucket. This fixes that.
N/A. Creating a QN target is a lot so I'm gonna test this in staging again.

Upload QN targets to the correct bucket.

---

infrastructure/deploy.sh
infrastructure/init_terraform.sh

#461 
There's a couple things about this which aren't obvious. The first is the dynamodb table. Since this is being used by terraform to manage our infrastructure's state, I am not managing this with terraform. This is similar to what we did for the S3 buckets which store the state files.
The second thing is that it seems enabling state locking on a terraform stack that already exists causes the following error:
```
Error refreshing state: state data in S3 does not have the expected content.
This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in …
```

Use dynamodb for terraform state locking.

---

common/data_refinery_common/utils.py
workers/data_refinery_workers/downloaders/sra.py
workers/data_refinery_workers/downloaders/test_sra.py
workers/data_refinery_workers/downloaders/utils.py

N/A came out of a discussion with SRA Chris
This is likely to not pass tests because I haven't touched the tests yet :(
However this does in fact use HTTP to download from SRA instead of Aspera. This is because Chris said that they had to tweak their aspera servers a lot to get the uploads to Google Cloud and AWS and so those servers are not currently working.
I downloaded some data with this switch.
- [] Lint and unit tests pass locally with my changes

[WIP] Switch the SRA downloader over to use HTTPS instead of aspera.

---

workers/data_refinery_workers/processors/qn_reference.py
workers/data_refinery_workers/processors/utils.py

#1325 
In #1325 I made a variable that I forgot to use, this actually uses it. This will make it so that QN targets actually go to the a different bucket so they can be publicly available.
I can't really functionally test this without standing up a dev stack and it doesn't really seem worth the time or money for something so easily testable and so low priority.

Fix which bucket we upload QN targets to again

---

workers/data_refinery_workers/processors/salmon.py

#1321 
We're back up and running, but we haven't cracked the --split-3/unmated reads nut yet. So these jobs are going to hang forever. Therefore we need a timeout. Here it is!
I think I did some back when I wrote this but I forget.

Add the code to enforce a timeout on salmon

---

foreman/data_refinery_foreman/foreman/management/commands/organism_shepherd.py
foreman/data_refinery_foreman/foreman/management/commands/test_organism_shepherd.py
workers/data_refinery_workers/processors/salmon.py
workers/data_refinery_workers/processors/utils.py

#1321 
Unmated reads are still causing salmon to hang. Until we can address this, we can't process these and we can't even detect them until we hang for an hour.
This changes the organism shepherd so that it will only requeue samples for whom we've processed at least one other sample in the experiment.
These are small tweaks and there's existing tests.

Refocus the organism shepherd

---

foreman/data_refinery_foreman/foreman/main.py

#1220 
The SRA blacklist has been lifted! We don't need this any more!
Unfortunately since we used the blacklist config file in a migration we cannot remove it, or running migrations against a fresh DB would fail.
N/A it's just taking out code.

Remove blacklisting code

---

.gitignore
foreman/data_refinery_foreman/surveyor/transcriptome_index.py

close #1314 
Initially introduced in https://github.com/AlexsLemonade/refinebio/pull/1308, this un-hardcodes ensembl api version and makes a request to the API endpoint.
Tested that [api endpoint](https://rest.ensembl.org/info/eg_version?content-type=application/json) worked

Use api to get ensembl version

---

foreman/data_refinery_foreman/foreman/main.py

N/A I found this while trying 10 experiments.
We wanted to make sure that we didn't scale up harakiri killed jobs, but our conditional statement also prevented us from scaling up jobs that don't have a failure reason, which includes all jobs that get OOM-killed because when they get OOM-killed the job is killed before we can even record why.
This meant that the jobs that actually would actually benefit from scaling never got scaled. This fixes that.
I tested the logic to make sure it would work as expected now and have no chance of error.

[HOTFIX] Scale OOM-killed downloader jobs

---

workers/data_refinery_workers/processors/smasher.py

This looks like a status message. It also swamps our Sentry interface when folks download large datasets because each message is subtly different. I don't have strong feelings between `info` and `debug` but I do have strong feelings that it shouldn't be `warning` or above.
N/A
Makes our logging less chatty
N/A
None

warning -> debug in smasher

---

README.md

N/A
I added this last year because it fixed some issue I was having, but this recommendation actually breaks `create_virtualenv.sh` for me and I can't figure out what issue it was trying to prevent.
I ran the installation without the `pip.conf` and it worked.

Removed pip.conf recommendation from README

---

workers/nomad-job-specs/create_compendia.nomad.tpl

Closes #1385 
Don't run the compendia generation on the smasher. The compendia job specification requires more ram than is available on smasher instances, so the jobs hang indefinitely.
- Tuning
- Bugfix
N/A

Don't run the compendia generation on the smasher instance

---

api/data_refinery_api/views.py

#1378
For the samples endpoint, we were calling `distinct()` on the queryset. This made the query take much longer to execute. We think we initially added it to prevent duplication with `prefetch_related`, but I could not find any references online to people having problems with duplication and `prefetch_related`. The Django docs also didn't say that you had to use `distinct()` with prefetch_related`, so it looks like this might be an unnecessary strain on our database.
I ran the API locally and verified that this made the `/samples` endpoint faster without duplicating samples.

Dramatically improve /samples/ load times

---

foreman/data_refinery_foreman/surveyor/test_sra.py
workers/data_refinery_workers/processors/test_salmon.py

Fixes #1390
Manually create Organisms in our database in all our tests so that we don't have to call the Esearch API for taxon ids.
I ran the tests locally to make sure that my changes didn't break the tests, then these tests will run on CircleCI which will verify that we don't have any Esearch errors.

Removed Eutils API calls from tests

---

common/data_refinery_common/models/jobs.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

Closes #1380 
I put a method on the ProcessorJob model that will delete all the local copies of its original files, which is then called by the foreman after a job fails for the maximum number of times.
I modified one of the unit tests to make sure that the file deletion was attempted after the maximum number of tries for a processor job.

Delete failed processor data

---

workers/affymetrix_dependencies.R
workers/illumina_dependencies.R
workers/install_affy_only.R
workers/install_downloader_R_only.R
workers/install_gene_convert.R
workers/install_tximport.R
workers/qn_dependencies.R

#1403
In #1403 we changed the way we specified repos from `options(repos=structure(c(CRAN="https://cran.revolutionanalytics.com")))` to `options(repos="https://cran.microsoft.com/snapshot/2019-07-03")`. I think that despite the docs saying:
> character vector, the base URL(s) of the repositories to use, e.g., the URL of a CRAN mirror such as "https://cloud.r-project.org"
that it does indeed need to have the special data structure to be used by devtools. I dunno why, but I built it on my local machine and it worked.
I built the image on my local machine and got a nice:
```
Successfully built 308e96f1abd8
Successfully tagged dr_affymetrix:test
```

Try setting the repos using a data structure instead of what the docs say

---

workers/affymetrix_dependencies.R
workers/install_affy_only.R

Builds are still failing because of R stuff
This installs GEOQuery and it's two dependencies: tidyr and dplyr.
I was able to get past these dependencies and it said SCAN.UPC was successfully installed, also I didn't see any errors in the logs like `ERROR: dependency 'dplyr' is not available for package 'tidyr'` which is what has failed most recently.

Fix R by iinstalling geoquery

---

.circleci/config.yml
README.md
scripts/install_all.sh
scripts/rebuild_es_index.sh
scripts/run_manage.sh

Closes #1356 
When testing the compendia import error fix, I had to manually edit `run_manage.sh` to run the compendia management command locally. I changed `run_manage.sh` to instead specify the requested Dockerfile as arguments. This fix also includes a new script: `./scripts/rebuild_es_index.sh`, which wraps the elasticsearch management command.
I ran the scripts locally to verify the error handling and to verify that they work.

Made run_manage.sh take dockerfile as arguments

---

common/data_refinery_common/models/jobs.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

Reverts AlexsLemonade/refinebio#1387
I just realized this isn't the right way to do this because the foreman cannot delete data off of a worker instance's EBS. This should instead be done by the jobs themselves (which would require them to know what the job limit was) or by the janitor jobs (probably the better option).

Revert "Delete failed processor data"

---

foreman/data_refinery_foreman/foreman/management/commands/create_missing_downloader_jobs.py

N/A, I need it for testing tximport.
Add an option to the management command that creates missing downloader jobs which only creates samples made after a certain datetime, so that we can queue up only the jobs we're interested in retrying.
I created a sample management command locally to make sure that the `datetime` was parsed correctly.

Added an option to create missing downloader jobs created after date

---

foreman/data_refinery_foreman/foreman/main.py
scripts/format_nomad_with_env.sh

N/A, detected while investigating downloader failure reasons for files on staging.
It looks like we have ~18,000 downloader jobs that have failed when their RAM amount was 8192 megs for being out of memory.
Example log output:
```
ERROR [downloader_job: 4624979]: Exception caught while downloading file.
File "/home/user/data_refinery_workers/downloaders/sra.py", line 92, in _download_file_http
shutil.copyfileobj(request, target_file, CHUNK_SIZE)
File "/usr/lib/python3.5/shutil.py", line 76, in copyfileobj
fdst.write(buf)
OSError: [Errno 12] Cannot allocate memory
```
_Put …

Up RAM amounts on downloader jobs that have failed two times

---

foreman/data_refinery_foreman/surveyor/external_source.py

#1378 
We were loading the whole query just to count the number of results.
This should remove queries like this one:
```sql
SELECT "downloaderjob_originalfile_associations"."id", "downloaderjob_originalfile_associations"."downloader_job_id", "downloaderjob_originalfile_associations"."original_file_id" FROM "downloaderjob_originalfile_associations" INNER JOIN "original_files" ON ("downloaderjob_originalfile_associations"."original_file_id" = "original_files"."id") WHERE "original_files"."source_url" IN ('dbtest@sra-download.ncbi.nlm.nih.gov:data/sracloud/traces/sra76/SRR/008287/SRR8486235')
```
ref https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.count
- Breaking change (fix or feature that would cause existing functionality to not work as …

Use count instead of len when calculating number of elements in a query

---

common/data_refinery_common/models/models.py
workers/data_refinery_workers/processors/salmon.py

#1074 
Also try to prevent no_retry jobs from being recreated by checking for them in the `needs_processing` method of OriginalFile.
Salmon quant computational results have multiple annotations. Tximport was assuming there was  only one. This fixes that.
N/A tests cover this well and we're testing these things on staging ATM.

Fix an issue with tximport getting the index length 

---

workers/data_refinery_workers/processors/utils.py

N/A came up while testing the tximport management command
Tximport jobs fail because their original files were already processed. They should have been processed already by Salmon, so it doesn't make sense to fail for that reason.

Add a check for if a processor job is a tximport job before failing

---

common/data_refinery_common/migrations/0023_fix_platform_names_spaces.py

close #1249 
Adds a new migration to fix Sample platform names.
Logs
```
Updating platform name from 'IlluminaGenomeAnalyzerII' to 'Illumina Genome Analyzer II' page
Updating platform name from 'IlluminaGenomeAnalyzerIIx' to 'Illumina Genome Analyzer IIx' page
Updating platform name from 'IlluminaHiScanSQ' to 'Illumina HiScanSQ' page
Updating platform name from 'IlluminaHiSeq1000' to 'Illumina HiSeq 1000' page
Updating platform name from 'IlluminaHiSeq1500' to 'Illumina HiSeq 1500' page
Updating platform name from 'IlluminaHiSeq2000' to 'Illumina HiSeq 2000' page
Updating platform name from 'IlluminaHiSeq2500' to 'Illumina HiSeq 2500' page
Updating platform name from 'IlluminaHiSeq3000' to 'Illumina HiSeq 3000' page …
```

Add migration to update sample platform names

---

foreman/data_refinery_foreman/foreman/management/commands/create_missing_downloader_jobs.py

N/A 
This job takes a really long time to run because of this sleep and I wanna finish all the work it'll queue up

Remove the sleep from the create_missing_downloader_jobs command.

---

README.md
infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

Reverts https://github.com/AlexsLemonade/refinebio/pull/1386
It's best to run compendia jobs on the smasher instance because it won't get cycled by AWS and we don't have to worry about enough capacity being available to run the job. It does mean we have to scale our smasher instance up and then back down to run compendia, but it's better than running these jobs on spot instances.

Run compendia jobs on the smasher instance

---

api/data_refinery_api/views.py
common/data_refinery_common/models/documents.py

close https://github.com/alexslemonade/refinebio-frontend/issues/705
We had a discussion on close https://github.com/alexslemonade/refinebio-frontend/issues/705 and decided to remove the sample additional metadata from the search fields. 
This will only affect people trying to filter on the `/samples` endpoint

Avoid searching in sample metadata

---

api/data_refinery_api/views.py

Closes #1461
We should not be grouping based off of `created_at` for job statistics, because we want to see when jobs succeeded/failed. If we instead group based on `last_modified`, we will see jobs on the graph when they were last modified, either because they were created or because they succeeded or failed.
```
data_refinery=> select count(id) from downloader_jobs where success = True and date_trunc('hour', created_at) = timestamp '2019-08-08T09:00:00Z';
count
-------
7
(1 row)
data_refinery=> select count(id) from downloader_jobs where success = True and date_trunc('hour', last_modified) = timestamp '2019-08-08T09:00:00Z';
count
-------
1281
(1 row)
```
I ran SQL queries to make sure …

Fix incorrect dashboard statistics

---

api/data_refinery_api/views.py

#1388 
We've only got one prod instance up and we're almost overloading the database. I think that it's a lot related to the fact that we're now running our heaviest query every 5 minutes. There may be more, but I think we need to disable this ASAP.

Disable the background stats cache updater.

---

api/data_refinery_api/views.py
common/data_refinery_common/migrations/0026_fix_typo_in_sample_manufacturer.py

Our database isn't doing so well, big spikes every 5 minutes and we're seeing:
```
2019-08-08 20:00:17 UTC:10.0.73.172(40800):drpostgresuser@data_refinery:[13249]:LOG:  duration: 6306.040 ms  statement: SELECT COUNT("downloader_jobs"."id") AS "total", COUNT("downloader_jobs"."id") FILTER (WHERE "downloader_jobs"."success" = true) AS "successful", COUNT("downloader_jobs"."id") FILTER (WHERE "downloader_jobs"."success" = false) AS "failed", COUNT("downloader_jobs"."id") FILTER (WHERE ("downloader_jobs"."start_time" IS NULL AND "downloader_jobs"."success" IS NULL)) AS "pending", COUNT("downloader_jobs"."id") FILTER (WHERE ("downloader_jobs"."start_time" IS NOT NULL AND "downloader_jobs"."success" IS NULL)) AS "open" FROM "downloader_jobs"
```
We gotta disable this ASAP

[HOTFIX] Disable stats background scheduler

---

foreman/data_refinery_foreman/settings.py
infrastructure/deploy.sh

Came up during deploy
Call the `createcachetable` management command during deploys

Call createcachetable during a deploy

---

api/data_refinery_api/views.py
infrastructure/deploy.sh

#1468 
I changed it so that a background job refreshes the stat cache rather than a scheduler instance in the views, since it seemed that Django replicated those schedulers. Also, only cache None and 'day' for range parameters, since those are the default and that should reduce the load on our database.
I ran the new management command inside one container and the API inside another and tested the cache using `time curl` and debugging print statements.

Fix API stats refresh scheduler

---

foreman/data_refinery_foreman/foreman/main.py

N/A came up during my dev stack test, and seems to be causing issues for prod as well.
We were only looking at the nomad queue to determine which volumes we needed to queue work for. This means that if a volume index didn't have any jobs in the nomad queue it would never get any put in it. It also means that if a volume index did have jobs in the nomad queue it would continue to get more queued up even if it wasn't mounted.
Also clears out downloader jobs for unmounted volumes.
I'm testing this in my dev stack.

Fix the foreman to queue up the correct jobs

---

common/data_refinery_common/models/models.py

#1378 
Calculate the number of processed/downloadable samples for experiments in a single query. This was one of the queries that impacted the surveyor negatively.

Calculate number of samples per experiment in a single query

---

foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/surveyor.py

#1491 
We got bit by get!
`a.get("x", "y")` can return `None` if `a["x"] == None`, which I think is what was happening. That's why we were violating our database constraint.
This also set failure reasons for surveyor jobs.
I ran a surveyor job for DRP003656 and it failed without these changes. With these changes it worked!

Fix at least some of the surveyor jobs.

---

.circleci/config.yml
foreman/data_refinery_foreman/surveyor/management/commands/surveyor_dispatcher.py
foreman/data_refinery_foreman/surveyor/test_end_to_end.py
foreman/nomad-job-specs/surveyor.nomad.tpl

N/A came up while opsing
I'm having trouble getting enough surveyor jobs to run to keep the system fed. The surveyor jobs are stuck behind other jobs. This will make them run on the smasher. It also adds a sleep to the dispatcher so that they won't all start at the exact same time. This way I can queue up a file with 50 accessions and it will take 25 minutes to queue them all!
Also disable failing salmon test until it can be fixed... maybe. Also only run salmon end-to-end tests once.
The failing salmon test may just stay disabled. It completed successfully on my machine, but it takes a long time to run, and is especially susceptible to intermittent failures caused by external services. When I was running it locally it failed once because one of its 4 downloader jobs failed. When I reran …

[HOTFIX] Make surveyor run on smasher instance and spread them out more

---

foreman/data_refinery_foreman/foreman/management/commands/retry_timed_out_jobs.py
workers/data_refinery_workers/processors/salmon.py

#1494 
It looks like we can finally process samples with unmated reads. Now we have to go back and process all the samples that timed out because of that issue or just because they needed more running time.
I haven't functionally tested this. I think I just want to do so on staging.

Add management command to retry jobs that timed out

---

foreman/data_refinery_foreman/foreman/main.py

N/A I've been thinking this has been an issue
Also use a global variable correctly so it gets updated in between checks.
Basically the graph of instance CPU utilization makes it seem like only the instance with the least utilization gets assigned downloader jobs, and then it gets so many that it ends up being high utilization for a long time. However I'd like the foreman to distribute jobs between all the instances better so that we get more even and consistent CPU utilization.
I have not tested this, but these are minor tweaks that I'm not worried about.

Make the foreman check nomad more often

---

foreman/data_refinery_foreman/foreman/main.py

#1405
We aren't keeping all our instances busy well because we aren't queuing downloader jobs well.
Because we've been failing to update `DOWNLOADER_JOBS_IN_QUEUE` as we queue downloader jobs and only refresh that every two minutes, that means that as soon as we drop below 750 downloader jobs we queue downloader jobs for 2 minutes straight before we realize we're past 750. This causes lots of downloaders jobs to get queued so we can't queue more for a long time, at which point one or more instances runs out and starts idling to some degree.
I haven't tested this. It's a hard one to test when not running at scale.

Fix the way we queue downloader jobs.

---

foreman/data_refinery_foreman/foreman/test_main.py

Caused by https://github.com/AlexsLemonade/refinebio/pull/1508
In #1508 I fixed the fact that we weren't keeping track of downloader job counts properly. However once I fixed this limit it started being imposed on this test, which made the test unable to queue as many jobs as it was expecting.
N/A this is a unit test fix

Fix foreman test that broke because I fixed the download job cap.

---

api/data_refinery_api/views.py

Front End Issue:
[##714](https://github.com/AlexsLemonade/refinebio-frontend/issues/714)
This is addresses a front end issue where the dashboard dataset downloads appears to be too high, so we are trying to filter out more known emails for the statistics on downloaded datasets.
Ran locally fine but without data to verify this will bring the current numbers to within ideal range.
- [ x ] Lint and unit tests pass locally with my changes

extend excluded list and add ALSF email addrs

---

api/data_refinery_api/management/commands/update_es_index.py
infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

Hmm, I don't know that we ever actually made an issue for it
We have about a 5-10% database spike every minute from rebuilding all the indices for elasticsearch. For whatever reason, it starts over and reindexes every model rather than just the ones that changed. It's honestly probably because it's hard to know what field to use for the cutoff. Fortunately all of our models have a `last_modified` field so we can just use that!
I ran the command with a bunch of old experiments and saw:
```
Indexing 0 'Experiment' objects
```
I then updated one of the experiments' last_modified field and ran it again and saw:
```
Indexing 1 'Experiment' objects
```

Update ES incrementally instead of rebuilding indices from scratch every time

---

common/data_refinery_common/job_management.py
common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/foreman/management/commands/rerun_salmon_old_samples.py
foreman/data_refinery_foreman/foreman/management/commands/test_rerun_salmon_old_samples.py

#1513 
When we deployed #1513 we didn't remove the check where we wouldn't start a job if there was already a good computed file. This fixes that.
This also sets the volume index for created jobs because they were defaulting to "-1" and I was having to update that manually.
I ran this locally but I didn't have mixed-version experiment to trigger it, but the tests cover it well and I made sure that the volume index got set properly.

Fix salmon rerun command

---

common/data_refinery_common/models/models.py

https://github.com/AlexsLemonade/refinebio/pull/1523
This typo was causing a bug.
I ran this in a shell against my local database and it gave the expected error. However after this branch it does not and works correctly.

Fix a typo found by @jaclyn-taroni!

---

foreman/data_refinery_foreman/foreman/management/commands/run_tximport.py
workers/data_refinery_workers/processors/salmon.py

#1074 
It looks like the foreman ran out of RAM while running the run_tximport command this morning. I guess we finally have enough experiments for this to be a problem so that's exciting.
Also make it so tximport won't seem to succeed when running on experiment with mixed salmon versions.
The unit tests cover this.

Paginate the run_tximport command

---

foreman/data_refinery_foreman/foreman/management/commands/rerun_salmon_old_samples.py
infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh

#1523 
I've seen 3 errors from the salmon rerun jobs like:
```
2019-08-28 14:25:10,276 i-03c3479626488d617 [volume: -1] data_refinery_common.job_management WARNING [original_downloader_job: DownloaderJob 5307576: SRA] [undownloaded_files: [<OriginalFile: OriginalFile: SRR534304.sra>]]: Downloader job has already been recreated once, not doing it again.
```
Not too bad considering we've already created 21k jobs with it. Still should be fixed so we get all of salmon on the same version.
Also fix typo in foreman startup script.

Force salmon rerun jobs to get created. 

---

foreman/data_refinery_foreman/foreman/management/commands/run_tximport.py

#1544 
I put this in the wrong place. It doesn't affect anything, but the counter is always 0 or 1.

Fix creation counter for the run_tximport command.

---

api/data_refinery_api/views.py
common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/management/commands/feed_the_beast.py
workers/data_refinery_workers/processors/salmon.py

N/A 3 small changes that we realized were necessary.
This makes the dashboard job stats use the same cutoff date as the Foreman.
This also fixes the logic in needs_downloading that caused the salmon rerun jobs to not get queued.
Finally, this bumps the downloader job max up to 1000 since the external sources seem to be able to handle the volume we're running at and we've been having trouble keeping a queue populated on all 11 instances.
I tested the stats endpoint and I made sure that the conditional I changed gave the expected result when run on prod data (I execed onto the foreman docker container and ran it against a sample that didn't get run for this reason).

Small improvements to be able to queue up lots of work

---

infrastructure/variables.tf

#1547 
These were missed before, easy enough to fix.

Remove mailchimp from terraform output variables.

---

api/data_refinery_api/views.py

#1548 
I fixed the query for pending downloader jobs, but not for the open ones. This addresses that.

Set the job cutoff date for open DL jobs as well.

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

#1555 
Only incrementally reindex elastic search for new experiments created after deploy. On deploy we should index all of the existing experiments.
api/run_test.sh appears to be satisfied.

populate es index on deploy

---

foreman/data_refinery_foreman/foreman/main.py

N/A I've noticed one volume getting too many jobs and starving the other instances
I don't like `global`. I shouldn't have approved the first PR that made use of it, but now switching away from it would be a bigger refactor than I want to tackle right now.
This should fix our usage of a global variable and actually increment it so that when we requeue lost downloader jobs we don't just put them all on whichever instance had the lowest job count at some point.
The unit tests cover this code.

Count lost jobs that get requeued towards the Volume depth

---

foreman/data_refinery_foreman/foreman/management/commands/correct_affy_cdfs.py
foreman/data_refinery_foreman/foreman/management/commands/test_correct_affy_cdfs.py

#1276 
It's rather impossible to tell by only looking at the database which samples are wrong and which are not since GEO has mixed-platform experiments. So the only way I could think to figure out which samples had the incorrect platform was to check GEO.
As #1276 mentions, some of these mis-labeled samples were successfully processed so in order to retrigger processing and the correction of metadata, I decided to just unsurvey the whole experiment and resurvey it. This may result in a decent number of reprocessing of samples that aren't incorrect, but these are all microarray samples so they'll go quick and I think this will be a cleaner solution than trying to both correct the metadata and then convincing the system to allow these samples to be reprocessed.
- New feature (non-breaking …

Adds management command to correct GEO samples with bad metadata

---

.circleci/run_terraform.sh
scripts/install_nomad.sh

#1352
Nomad v0.8.3 sometimes displays negative job counts for summaries. We use these summaries in the Foreman to determine how many jobs to queue on which volumes so this messes us up. This bug has been "fixed" poorly in v0.8.7 so upgrading should make this better for us.

Bump Nomad up to v0.8.7

---

api/data_refinery_api/views.py

@kurtwheeler noticed that after deploy the downloader jobs stats were missing the values for jobs in a pending state. This remedies that by including queried jobs whose start_time is null.
Adds Q(start_time__isnull=True) to jobs query filter.
API/stats

Dashboard - Adds pending jobs back to job stats

---

workers/nomad-job-specs/salmon.nomad.tpl
workers/tester.sh

#1574 
We upgraded Nomad and now the tmpfs config we had lying around in the Salmon job spec is actually being used and is thus causing problems.

Remove the tmpfs config for Nomad 

---

.circleci/run_terraform.sh
scripts/install_nomad.sh

#1574 
Nomad jobs are failing with: `Exit Code: 137, Exit Message: "Docker container exited with non-zero exit code: 137"`
We've seen this on 0.8.7 and 0.9.0 I think. Maybe it's been fixed in 0.9.5
I'm running a test locally now

Try bumping Nomad up to 0.9.5

---

common/data_refinery_common/migrations/0017_auto_20190312_2011.py
common/data_refinery_common/migrations/0019_sample_is_blacklisted.py

N/A
Running django unit tests would throw this warning when it created the testing DB
``` Pagination may yield inconsistent results with an unordered object_list:```
```Running tests with the following command:
coverage run --source="." manage.py test --no-input --tag=smasher data_refinery_workers.processors.test_smasher.SmasherTestCase.test_smasher; exit_code=$?; coverage report -m; exit $exit_code
Creating test database for alias 'default'... 
/usr/local/lib/python3.5/dist-packages/data_refinery_common/migrations/0017_auto_20190312_2011.py:28: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class '__fake__.Sample'> QuerySet. …
```

fix pagination ordering warning

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_compendia.py
workers/run_tests.sh

#1537 
Removes code that appends each frame and instead assigns it to the list with an incremented index.
This is the initial part of the improving compendia speed. 
Smasher and compendia tests run locally

preallocate the all_frames list

---

README.md
workers/data_refinery_workers/processors/management/commands/create_compendia.py
workers/nomad-job-specs/create_compendia.nomad.tpl

#1485 
Makes create_compendia dispatch jobs if requested to create more than one. This also makes create_compendia accept a list of comma separated organism names and dispatch jobs for each of them.
I've passed a list of organisms to a compendia job through nomad.

Parallelize recreating compendia for all organisms

---

infrastructure/variables.tf

#1514 
The bot is still broken despite updating the webhook urls etc.
From the logs:
```Invalid URL '${{ENGAGEMENTBOT_WEBHOOK}}': No schema supplied. Perhaps you meant http://${{ENGAGEMENTBOT_WEBHOOK}}?```
Hopefully this will cause it to be parsed.
Infrastructure edit... adds the tfvar to the environment variables for engagment bot webhook
Didn't test locally yet.

adds tfvar for slack engagementbot webhook

---

workers/README_COMPENDIUM.md
workers/README_DATASET.md

Related to #703 
Adding a `Citing refine.bio` section to the READMEs included with dataset and compendia downloads. This mirrors the changes in https://github.com/AlexsLemonade/refinebio-docs/pull/111.

Add citation info to download READMEs

---

infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

N/A noticed that there's some smasher jobs stuck on pending cause a compendia job is running.
This should make it so that one compendia job and one smasher job can both fit on the smasher instance at the same time. If we end up needing more RAM for compendia jobs then we can up that and up the instance size, but we should still leave 30GB so smasher jobs can get in there.
- Infrastructure
N/A infra only

Reduce the size of compendia jobs so a smasher job can run alongside them.

---

api/data_refinery_api/views.py

N/A
We are having some issues with the caching of the stats endpoint in prod. I tested the dashboard on staging and the caching seems to be working.
I think what happens in prod is that calculating the stats takes a longer time, and multiple threads are invalidating the cache at the same time, so all of them also calculate the stats. Which makes it take longer for all the others.
This method of caching seems to take this into account and only calculates the response once.
Didn't tested.

Use `cache_page` decorator to cache the whole stats request

---

common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py
workers/data_refinery_workers/processors/test_array_express.py
workers/data_refinery_workers/processors/utils.py
workers/dockerfiles/Dockerfile.affymetrix_local
workers/nomad-job-specs/run_qn_job.nomad.tpl

#1572 
The foreman wasn't retrying QN jobs because they didn't have a volume index. This fixes that by letting the foreman retry jobs without volume indices. To avoid this suddenly retrying lots of jobs that were previously filtered out I've moved the job_cutoff date up.
Also set the QN s3 env var in the other QN job. Yes we should have two because one gets dispatched to with a processor job already created and the other will just go for any supplied organism.
The unit tests cover this rather well I think.

Make the foreman retry QN jobs

---

foreman/data_refinery_foreman/foreman/management/commands/retry_samples.py

#1630 
The query was too big so it timed out. This breaks it up into smaller chucks and does the distinct samples in python's memory.
I ran the command and it completed without errors, but I don't have data it would affect.

Break up retry_samples query into smaller queries

---

infrastructure/permissions.tf

#1572 
Now the QN jobs are uploading to the right buckets, but they didn't have the right permissions! This fixes that.

Grant instances access to QN bucket.

---

foreman/data_refinery_foreman/foreman/management/commands/retry_samples.py

#1627 
Current version is timing out. This one uses the `ComputedFiles` to calculate the samples, instead of the other way around.
Tested queries on staging and ran the sql in prod to ensure they don't time out.

Change the query to calculate the samples with computed files that were not uploaded to S3

---

common/data_refinery_common/models/models.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py

#1602 
Seems that we don't associate `ComputedFiles` with `quant.sf` results with the samples, instead this changes the code to fetch them through the `ComputationalResults` relations.
Tested locally

Access quant files through computational results

---

infrastructure/instances.tf

#1587 
Describe the big picture of your changes.
One of the jobs to generate the quantcompendia failed with 50k human samples because it ran out of space.
The total size of the quantfiles that we have is `5000GB`. This increases the smasher to `3000GB` to be prepared for when we generate the datasets in parallel. 
```sql
data_refinery=> select sum(size_in_bytes) from computed_files where filename='quant.sf';
sum      
---------------
5603241992755
(1 row)
```
None

Increase smasher size

---

common/data_refinery_common/models/models.py
common/data_refinery_common/rna_seq.py
infrastructure/users.tf
workers/data_refinery_workers/downloaders/sra.py
workers/data_refinery_workers/processors/salmon.py
workers/data_refinery_workers/processors/test_salmon.py

N/A came up while running #1630 
QN jobs were still failing because of bucket permissions. This should address that.
Additionally we had problems because `needs_processing` and `get_quant_results_for_experiment` weren't disregarding computed files that hadn't been uploaded. This makes those functions filter out computed files that weren't uploaded so we either can reprocess them or realize that we aren't ready for tximport.
The unit tests are actually really good for this, especially since I don't have the test data for it.

Filter un-uploaded quant files from tximport. Fix QN bucket perms.

---

foreman/data_refinery_foreman/foreman/management/commands/correct_affy_cdfs.py

#1276 
The job was failing for what I think was a GEOParse error. We'll just move on and see how we do.
I ran it but I don't have much test data for it.

Log exceptions rather than letting them interrupt the correct affy cdfs command.

---

infrastructure/instances.tf
workers/data_refinery_workers/processors/management/commands/correct_affy_samples.py

#1276 
Ran out of disk space again. I think I didn't indent my previous "fix" enough. This should keep the disk space usage low for that command.
I ran it locally but I don't have much data to correct.

Clean up disk space better in correct_affy_cdfs

---

workers/README_NORMALIZED.md
workers/README_QUANT.md
workers/data_refinery_workers/processors/create_compendia.py

#1661 - this currently addresses the first two points there. This is where the change needs to be made to address the third point: 
https://github.com/AlexsLemonade/refinebio/blob/c20389265b38dedba0bc31c302582167ca9f293f/workers/data_refinery_workers/processors/create_compendia.py#L329
I was going to make the change myself but because there are now two files to choose from based on the _type_ of compendium being created, this turns out to be more logic than I am comfortable writing right this moment.
- Changes the file that was formally `README_COMPENDIUM.md` to be named `README_NORMALIZED.md` and changes the text contained within to reflect our new terminology for this offering: `normalized compendium`.
- Adds a new file `README_QUANT.md` that is written to be included with quantpendia. …

Create separate README files for types of compendia

---

common/data_refinery_common/message_queue.py

#1258 
We still can't dispatch multiple compendia jobs with a single command. This isn't urgent at all cause I can do them one by one in prod until we're ready for another deploy.

Add CREATE_COMPENDIA to job switch.

---

common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/foreman/management/commands/check_computed_files.py

#1696 
This adds a command that iterates over all computed files to check if they are in S3. If they aren't it clears their `s3_bucket` and `s3_key` fields.
I used [iterator()](https://docs.djangoproject.com/en/dev/ref/models/querysets/#iterator) to iterate over all computed objects, seems like this will do something similar to the `Paginator` we have used.
None, should we test this on staging?

Add command to check if computed files are in S3

---

common/data_refinery_common/job_lookup.py
workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/management/commands/create_compendia.py
workers/data_refinery_workers/processors/test_compendia.py
workers/data_refinery_workers/processors/utils.py

#1258 
We have a lot of compendia jobs with failure reason like `Caught either a SIGTERM or SIGINT signal.` and none of these or the rest of the failures got retried. This should make it so that compendia jobs are actually retried.
I'm thinking about how to functionally test this...

Follows best practices around Enums to fix retrying CREATE_COMPENDIA jobs

---

common/data_refinery_common/utils.py
workers/data_refinery_workers/processors/management/commands/create_compendia.py

close #1679 
We were running the compendia jobs directly for a single organism, so `send_job` was not being called, and the `nomad_job_id` was not being set on those rows.
None

use `send_job` on compendia jobs

---

common/data_refinery_common/job_lookup.py
common/data_refinery_common/message_queue.py
foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/management/commands/retry_samples.py
foreman/data_refinery_foreman/foreman/test_main.py

N/A came up while trying to get a compendia job running this morning and/or I noticed it in the Foreman logs
A very small number of processor jobs didn't have volume_id set. This made the Foreman endlessly fail to requeue them.
We also didn't properly handle CREATE_COMPENDIA jobs in the same way we did for QN_REFERENCE and SMASHER jobs.
Finally this adds a `--last-modified` option to retry_samples for two of it's subcommands.
I don't have data locally for this but I ran it successfully regardless:
```
./foreman/run_surveyor.sh retry_samples --computed-files-not-uploaded --last-modified='2019-10-01'
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField ComputedFile.last_modified …
```

Fix requeuing for some edge cases and add --last-modified to retry_samples

---

foreman/data_refinery_foreman/foreman/management/commands/check_computed_files.py

#1696 
`filename` was a reserver argument for `logger.info` and got this error when running it:
```
File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "/home/user/data_refinery_foreman/foreman/management/commands/check_computed_files.py", line 29, in check_item
logger.info('Computed file not found on S3 - will remove S3 fields.', computed_file=computed_file, filename=computed_file.filename)
File "/usr/lib/python3.5/logging/__init__.py", line 1602, in info
self.log(INFO, msg, *args, **kwargs)
File "/usr/lib/python3.5/logging/__init__.py", line 1640, in log
self.logger._log(level, msg, args, **kwargs) …
```

Filename was reserved when logging

---

common/data_refinery_common/job_management.py
common/data_refinery_common/test_utils.py
common/data_refinery_common/utils.py
foreman/data_refinery_foreman/foreman/main.py

#1703 
We broke the queryset iterator so dispatching lots of compendia jobs fails.
For some reason the Foreman is also very broken. I saw some of it yesterday and tried to fix it with #1707 but that clearly didn't work. I tried to fix the issue in the downloader job utils but I don't think this'll fix the Foreman for jobs that already don't have volume index. However all it's telling me is that it couldn't queue the job so I've improved the logging there to get more visibility.
The unit tests cover this fairly well.

Fix queryset iterator and setting of volume index

---

common/data_refinery_common/message_queue.py

This was a dumb mistake. My guess is tests didn't catch it because we always mock send_job.
I didn't import my new constant. I'll look into getting a test that'll cover this but I wanna get this out ASAP.

Fix bad import that breaks foreman requeuing

---

README.md
workers/data_refinery_workers/processors/management/commands/run_processor_job.py

#1716 
```
2019-10-02 19:03:29,517 i-0d3d003bcf758f6b8 [volume: -1] data_refinery_workers.processors.management.commands.run_processor_job ERROR: A valid job name was specified for job CREATE_COMPENDIA with id 239373 but no processor function is known to run it.
```
We were missing this job type in the switch statement.
Also fix typo in README.

Add CREATE_COMPENDIA to job type switch in run_processor_job.

---

infrastructure/variables.tf
workers/data_refinery_workers/processors/create_compendia.py

#1721 
We ran a lot of compendia and now we just need to drill down on a few of them. While we do that we don't need such an expensive instance.
This also fixes failure_reasons on compendia a little.

Scale the smasher down to a more ecnomical size.

---

foreman/data_refinery_foreman/foreman/main.py

N/A
This is quick fix that prevents the foreman from killing compendia jobs. #1725 adds other improvements that we'll merge later.

Quick fix for the foreman killing compendia jobs

---

workers/data_refinery_workers/downloaders/utils.py
workers/data_refinery_workers/processors/utils.py

N/A
When jobs get's a sigkill signal we were clearing their `start_time`, this removes this part and sets `end_time`.
None

Set endtime when job gets sigkill signal

---

infrastructure/instances.tf
infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

#1258 
Also resize the smasher disk to the largest size we can use without addressing https://github.com/AlexsLemonade/refinebio/issues/1733
N/A infra

Make smasher instance 2x as big, make compendia jobs 4x as big

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/test_smasher.py

#1258 
Trying to figure out where our human smasher job is dying. It might be in process frames, cause I think that was the last log messages that came from the compendia rather than the quantpendia. However looking the logs is currently a bit tricky cause the annotation function logs about 4-6 times a millisecond, it's really hard to tell what log is coming from what job, and the process frames wasn't logging cpu/ram so if that is where it died we can't see the RAM usage growing to the point of OOM-killing.
- Tuning
The unit tests are outputting logs like:
```
2019-10-04 15:36:00,324 local [volume: 0] data_refinery_workers.processors.smasher DEBUG [job_id: 1] [total_cpu: 0.0] [process_ram: 2.8238258361816406]: starting scaler
```
and
```
2019-10-04 15:39:01,399 local [volume: 0] …
```

Tune smasher logging

---

workers/data_refinery_workers/processors/create_compendia.py

1537
This is a continuation of the effort to improve RAM consumption. This deletes copies and references to data structures that are non-trivial in size and no longer needed downstream.
This makes some small changes to the ```_perform_imputation``` method of the ```create_compendia.py``` command. 
This shouldn't have any scientific implications. 
None at the moment

delete unused compendia frames

---

workers/data_refinery_workers/processors/janitor.py

N/A I just noticed how spammy the janitor was while watching logs
The janitor was logging too much at info. This changes those calls to debug.

Move spammy janitor logs to debug.

---

workers/data_refinery_workers/processors/smashing_utils.py

N/A Came up while running human/rat compendia.
Prevent pickling error caused by large size of data.

Set maxtasksperchild on the worker pool for multiprocessing to 

---

workers/data_refinery_workers/processors/smashing_utils.py

#1762 
We had another job that died because of a data-too-big-for-pickle-in-multiprocessing issue, despite setting maxtasksperchild. Now we're hoping that if we call map more times with fewer items, it will wrap up and send data back more times so it doesn't have to send so much each time.

Call map many times in hopes

---

infrastructure/variables.tf
workers/data_refinery_workers/processors/smashing_utils.py

#1766 
For some reason we skipped most of the frames the last time we ran rat. I can't figure out what we have wrong but it skipped tons of frames. This rips out multiprocessing because we know without it it'll work just slowly.

Don't use multiprocessing for compendia because it skipped so many frames.

---

infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

#1258 
Human died with 1TB RAM. This doubles us up to 2.

We gotta go bigger for human, hopefully this is big enough.

---

workers/data_refinery_workers/processors/smashing_utils.py
workers/data_refinery_workers/processors/test_smasher.py

#1537
#1773 
#1773 seemed pretty complex to me, I think because it's doing things with generators and using some deep cuts from the itertools discography. I was curious if it'd be simpler without generators so I re-implemented it and it looks like it was to me.
I think the only downside this has over the implementation in #1773 is that it is stores a full chunk size of inputs for process_frame, but that should be rather small as it doesn't contain any actual data in it.
Unit tests?

paginate multiprocessing pool maps -- REDUX

---

workers/data_refinery_workers/processors/smashing_utils.py

#1537 
There were a few problems with the previous iteration of parallelizing the process_frame method in smasher.py. One of which was the amount of data being passed between threads was too large and this caused the smasher to crasher. This implements a nested generator which allows for the chunking of frames to be processed while keeping overhead at a minimum.
```process_frames_for_key``` in ```smasher.py```
```./workers/run_tests.py -t smasher```
and 
```./workers/run_tests.py -t compendia```
are passing
also tested compendia with various ```MULTIPROCESS_CHUNK_SIZE``` which good results

paginate multiprocessing pool maps

---

workers/data_refinery_workers/processors/smashing_utils.py

#1777 
Our human jobs died last night with errors like:
```
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2019-10-15 03:57:19,497 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.create_compendia ERROR [processor_job_id: 29205738] [dataset_id: 37626c56-1f6a-4b31-bf89-30b756c9c4b6] [num_input_files: 1]: Could not prepare frames for compendia.
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/create_compendia.py", line 86, in _prepare_frames
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     job_context = …
```

Multiprocessing.pool dislikes floats.

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/smashing_utils.py

#1774 
Someone thought that the dataset's failure_reason was a better indication if the job had succeeded or not than job.success.
Narrator: it wasn't
Once a dataset failed once, subsequent retries saw that failure_reason and gave up, badly too. This removes any checks against failure_reason and replaces them with checks against job.success. I also went through and made sure there's no where we set failure_reason without also setting job.success.

Use job.success as success flag instead of dataset.failure_reason in smasher

---

workers/data_refinery_workers/downloaders/utils.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/utils.py

https://github.com/AlexsLemonade/refinebio/pull/1728
#1728 started setting end_time on jobs that got sig_killed. Well the issue with that is that the foreman only retries jobs with `end_time != NULL` if `success == False`, so we also gotta set success to false so these get retried.
-  Bugfix (non-breaking change which fixes an issue)

Make signal handlers set job.success to False so they get restarted.

---

common/data_refinery_common/models/models.py

N/A
Came up while running a big dataset with quantfiles. We were trying to download files where their s3_key was empty.

Ensure quant.sf are in s3 when returning them

---

infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

#1258 
Double up the smasher instance to ~4TB of RAM.

It looks like we can do the human compendium if we go this big.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smashing_utils.py

#1258 
I thought this human compendia job was gonna pass, I really did. Cause rat finished without any crazy ram spikes, unless I missed them (I was watching htop for hours, but I wasn't staring at it 100% of the time).
I don't know why the human compendia failed or even where in `_perform_imputation`. That's a big function and we do a lot of things. Now we log inbetween each of them so we can see what's going wrong better, or at the bare minimum where.
I think my game plan is to run another rat job to see if the additional logging tells us more about RAM usage patterns, then kick off human to run overnight to see what actually happens with it.
- Debugging
I'm mostly just adding logs so the unit tests will cover this well.

Log in between every sub-step of _perform_imputation.

---

workers/data_refinery_workers/processors/create_compendia.py

#1790 
We're getting logs from the rat job that's finishing:
```
[process_ram: 43.360443115234375] [total_cpu: 0.0] [job_id: 29205842]: start microarray conc
[process_ram: 96.11630630493164] [total_cpu: 0.8] [job_id: 29205842]: end microarray concate
[job_id: 29205842]: Duration: 437.846248626709
[process_ram: 96.11630630493164] [total_cpu: 1.8] [job_id: 29205842]: start rnaseq concatena
[process_ram: 96.11557388305664] [total_cpu: 0.8] [job_id: 29205842]: end rnaseq concatenati
[job_id: 29205842]: Duration: 12.71019196510315
```
Looks like we're doubling up our RAM usage here. Makes sense looking at the code. This should make it so we no longer store references to these lists of data frames once we concat them into a pandas matrix, so  there shouldn't be a second copy.

Pop microarray_frames and rnaseq_frames off job_context to save RAM.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/test_compendia.py

#1258 
We're thinking that we're allocating more memory before the garbage collector was able to run and clean up the old reference.
:ram: :ram: :ram:

Try to use less rams.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/smashing_utils.py
workers/data_refinery_workers/processors/test_smasher.py

#1797  
I realized we were keeping `input_files` around longer than we needed to. It's probably not too much but it's something.
The main focus of this PR is to merge the data for smasher/compendia in chunks of 2k instead of all at once once we've read them all in. The RAM patterns look pretty good I think:
```
2019-10-17 17:24:20,803 local [volume: 0] data_refinery_workers.processors.smashing_utils DEBUG [total_cpu: 96.9] [process_ram: 0.7738990783691406] [job_id: 1]: set frames for key DANIO_RERIO
2019-10-17 17:24:20,803 local [volume: 0] data_refinery_workers.processors.smashing_utils DEBUG [job_id: 1]: Duration: 103.00166034698486
2019-10-17 17:24:20,812 local [volume: 0] data_refinery_workers.processors.create_compendia DEBUG [total_cpu: 25.0] [process_ram: 0.7702369689941406] …
```

Merge compendia/smasher frames in chunks to save rams

---

common/data_refinery_common/job_lookup.py

#1744 
`hta20` needs a lot of RAM. This will cause all jobs for samples from that platform to have 32GB of RAM!

Bump ram for hta20 platform.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/smashing_utils.py

#1258 
This PR makes us call merge repeatedly as we read in each chunk of frames. This means that we don't have to call `concat` on all the chunks at once so we won't increase our RAM so much. This also means that as soon as we add a chunk to the matrix we can delete it.

Iteratively merge both of the tech's matrices as we read their data.

---

workers/data_refinery_workers/processors/smashing_utils.py

N/A
Looks like we were counting number of genes in the merged microarray_matrix and rnaseq_matrix in smashing utils but calling them samples. This PR is a quick fix for that.
`process_frames_for_key`
`./workers/run_tests.sh -t smasher`

count samples not genes

---

workers/data_refinery_workers/processors/smashing_utils.py

#1537 
The idea here is to prevent either a MemoryError or OOM kill from docker as we try to merge substantially large dataframes into a compendium dataframe. This is happening before imputation as we prepare and merge the files. 
`smashing_utils.py:_process_frame_for_key`
Keeps the pandas.concat for each chunk as this seems to fit into memory just fine. However the first concatenated frames are merged into a `dask.DataFrame` instead and we merge each chunk iteration into that. After we are done with all chunks we call `dask.DataFrame.compute` on the microarray_matrix dataframe and rnaseq_matrix dataframe to convert it back to pandas and place it in memory.
ran `./workers/run_tests.sh -t compendia` test cases and also set the …

compendia merge with dask

---

workers/nomad-job-specs/create_quantpendia.nomad.tpl

#1823
Add more ram for the next time we try the quantpendias. Also, ensure it runs on the smasher since the job will be running for a couple of hours and we don't want it to be interrupted.
- Parameter change
None

Increase ram for quantpendia and smasher constraint

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/smashing_utils.py

#1258 
So it turns out that maxtasksperchild doesn't work like we thought it did. At least within the context of that parameter-name, `task` means one chunk of work, so really that parameter is specifying how many chunks each Process will do instead of tasks. Turns out that's about `2k/num_cores`....
Anyway this is causing multiprocessing to blow up our RAM usage. I'm looking into ways to use it without having it quintuple our RAM usage, but since we're no longer redownloading samples doing this sequentially should finish in a reasonable amount of time.
I also used the first pass over the data to count how many microarray and rnaseq samples would be found, so that I could actually preallocate the full matrix. This seems to make the `process_frames_for_key` function take a rather flat …

Remove multiprocessing, preallocate entire matrix.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smashing_utils.py

#1258 
Our human compendia job died 2.7k frames into the second pass. We don't want to have to keep spending a day on the first pass to be able to debug the second pass. Therefore this caches the data collected in the first pass so that subsequent jobs don't have to repeat that step.
Oh yeah, I also found the bug that caused our last job to crash. We were using both `frame` and `processed_frame` in the second pass, when the variable was only declared as `processed_frame`, which mean that `frame` was left over from the first pass. I've now renamed everything that was `processed_frame` to just be `frame` that way it's definitely using a variable from within that loop.
- Caching for iteration speed increase.
I ran the danio compendia tests twice. The second time we skipped the first pass …

Cache the data collected on the first pass of the compendia. Also fix compendia!

---

workers/data_refinery_workers/processors/create_quantpendia.py
workers/data_refinery_workers/processors/utils.py
workers/nomad-job-specs/create_quantpendia.nomad.tpl

#1823
The human quantpendia got stuck again, using all the ram that had available. This duplicates it to 32gb.
None

Increase the ram for the quantpendia 2x

---

foreman/data_refinery_foreman/foreman/management/commands/test_create_compendia.py

#1770 
We can't run the quantpendia job in the tests, this checks that a Processor job get's created with the correct dataset.
Ran test locally

Don't run quantpendia job

---

workers/data_refinery_workers/processors/create_quantpendia.py
workers/data_refinery_workers/processors/test_create_quantpendia.py

#1823 
close #1836
Quantpendia tests are failing because they check the existence of some files that we remove in prod.
None

Don't remove quantpendia files when running tests

---

workers/data_refinery_workers/processors/smashing_utils.py

#1258 
We got OOM-killed during the merge step of the two technology specific matrices. It makes sense, because pandas' `merge` function creates a new matrix the size of the other two combined, which is a full 2x. Since we were using more than half the RAM already, it makes sense that doubling up OOM-killed us.
This should drop our RAM usage by almost half across the board, because each value will take half as much data.
I printed out the `dtypes` attribute of the `combined_matrix` while running unit tests and it was all:
```
2xudu7weg98dz8j19my00peh_GSM1058035_1gluc1b.PCL                        float32
...   
xefr1rp4v17issz35pzae3cw_ERR015566_output_gene_lengthScaledTPM.tsv     float32
````
Which is what we were looking for!

Change the float size for the matrices to reduce RAM requirements.

---

workers/data_refinery_workers/processors/test_qn_reference.py

This doesn't seem to be a problem except for the tests:
```
$ cat new_target.tsv 
-8.138526439666748
-6.639985466003418
-4.754036998748779
-3.7660924911499025
-2.8230273962020873
-1.9792798280715942
-1.0959607787430286
-0.4379488527774811
-0.06401171181350947
0.4456931948661804
1.170599815249443
1.5125472962856292
2.2975677371025087
2.53656268119812
2.876345491409302
3.3962830543518066
3.6771607875823973
3.9307557582855224
4.445283889770508
5.0390016555786135
5.239974117279052
5.6812744140625
6.0960267066955565
6.847065544128418
7.732806205749512
7.983387565612793
8.204330921173096
9.358708572387695
10.39781436920166
13.927158546447753
$ cat old_target.tsv
-8.1385265774612
-6.639985434153478
-4.754037057782033
-3.766092553538422
-2.823027394861482 …
```

For some reason the file changed slightly, 

---

api/data_refinery_api/views.py

N/A
Adds a new parameter `sample_accession_code` to the downloader/processor jobs endpoints. To filter them by the sample accession code.
`/v1/jobs/processor/?sample_accession_code=GSM1933008`
Tested locally

Add sample accession code param to jobs endpoints

---

workers/data_refinery_workers/processors/smashing_utils.py

#1860 
QN normalization verification was crashing because we were creating a lot (read every possible pair) before shuffling and selecting 100 of them. We can improve this by just shuffling the list and creating 200 pairs from that list.
Quantile normalization verification.
`./workers/run_tests.sh -t qn`

dont create  all possible sample combos eagerly for qn verification

---

workers/data_refinery_workers/processors/smashing_utils.py

#1823 
The quantpendia jobs were OOM-killed because they ran out of memory when creating new processes. This uses Threads instead to download that data.
None

Use threadpool when downloading quant.sf files

---

workers/data_refinery_workers/processors/utils.py

#1833 
When the job failed, `utils.end_job` cleaned up the `work_dir`. This caused the cache and all downloaded files to get blown away. By adding this explicit check we make sure that the compendia jobs will not lose their work dirs in any circumstances.
I added `raise MemoryError("woaaaaaaaahhhh")` into the compendia code right before we call the merge. When I then ran the test without this change the work dir got blown away. With this change it stuck around past when the job failed and got wrapped up.

Keep the cache from the compendia's first pass even if the job fails.

---

workers/data_refinery_workers/processors/utils.py

N/A
Got this idea to refactor how we handle errors on the processor jobs, instead of using the `job_context['failure_reason']` this uses an exception that is handled in a single place.
What do you think @kurtwheeler?
None

Add `ProcessorJobError` to be used when processor jobs fail

---

foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py
foreman/data_refinery_foreman/foreman/management/commands/create_quantpendia.py
foreman/data_refinery_foreman/foreman/management/commands/test_create_compendia.py
foreman/data_refinery_foreman/foreman/management/commands/test_create_quantpendia.py
workers/data_refinery_workers/processors/create_quantpendia.py

#1823 
https://github.com/AlexsLemonade/refinebio/issues/1823#issuecomment-549988470 the quantpendia job failed while it was generating the metadata, after downloading all `quant.sf` files. Upon further investigation, it looks like `json.dump` takes a lot of memory when writing large objects to a file.
I noticed, we were sending all `364334` human experiments to the job, while we only have `6316` with QN-Targets.
This creates a new quantpendia command, to generate a dataset that only includes experiments and samples with `quant.sf` files. This will make the metadata object considerably smaller.
Added tests

Add new command to generate the quantpendia

---

common/data_refinery_common/models/jobs.py
foreman/data_refinery_foreman/foreman/main.py

N/A
Adds several managers to the Jobs objects to get the ones that are failed, hung or lost.
none

Refactor foreman and use managers to get failed/hung/lost jobs

---

infrastructure/instances.tf
infrastructure/variables.tf

Temp measure until:
https://github.com/AlexsLemonade/refinebio/issues/1882
is addressed and we fix the current issues affecting QN.
Bumps us down to m5.2xlarge for the smasher instance. It also takes the smasher's disk down to 200 GB from 2TB.

This cruise boat is nice and roomy but too expensive.

---

infrastructure/permissions.tf

#1879 
Looks like the policy has changed names or something? Let's try this since the deploy isn't working anyway.

Try AmazonEC2SpotFleetTaggingRole instead of AmazonEC2SpotFleetRole.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smashing_utils.py

https://github.com/AlexsLemonade/refinebio/issues/1882
This implements the second solution suggested in #1882:
> Another idea (probably more flexible/preferable) -> Since we're now doing two passes over the data, in the first pass don't create a set of all identifiers. Instead, create a dictionary. The keys would be the identifiers. The values would be number of samples in which that key was observed. We'd also store the number of samples processed.
> Then, after the first pass we'd only retain those identifiers that are in >= 50% of the samples. This should leave somewhat more identifiers than we remove here:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L230
because it both filters to a lower threshold and also because …

Only use gene identifiers that are present in >50% of the samples.

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smashing_utils.py

https://github.com/AlexsLemonade/refinebio/pull/1861
We don't know why #1861 failed. Rather than iterating on that problem in prod, this PR disables the QN test so we can just get it done. I'll run the QN tests on the compendia manually, and in the process of doing so I should also be able to figure out what's breaking it and come up with a solution that doesn't take so much RAM.

Disable the QN test until we can figure out why it OOM-kills the human compendia job.

---

workers/nomad-job-specs/create_compendia.nomad.tpl

350 GB should be enough, I was just gonna use as much as they said they were going to give us.

AWS lied to us about the size of the instance they sold us.

---

workers/data_refinery_workers/processors/smashing_utils.py

#1258 
We got OOM-killed in the `quantile_normalize` function. Not entirely sure why, but this should make things a lot more performant both by performing QN in chunks and also by making less copies of the data as we do so.
Specifically, after we QN each chunk we reassign the normalized values right back onto the original matrix so we don't have to make additional copies.
It was originally @jaclyn-taroni's suggestion to do this in chunks so I think she'll be a fan of the changes.
- Optimization
The compendia unit tests pass!

Quantile normalize the compendia matrix in chunks to avoid OOM.

---

workers/nomad-job-specs/create_quantpendia.nomad.tpl

N/A
- Let quantpendia run on smasher
- Increase quantpendia RAM to 64gb
None

Let quantpendia run on the smasher instance

---

infrastructure/variables.tf

#1258 
We're only going to run quantpendia tonight, so we only need half as much RAM.

Take smasher from 512 GB to 256.

---

foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py

N/A
Quick pr to avoid including unprocessed samples in the compendia dataset

Only include processed samples when building compendia dataset

---

api/data_refinery_api/views.py

#1849 
Adds `latest_version` which you set to `True` instead of ~compendium_version=latest~
Also fixes missing deps.

fix compendium latest version

---

workers/data_refinery_workers/processors/smashing_utils.py

https://github.com/AlexsLemonade/refinebio/pull/1916
I broke the smasher because I referenced a compendia only job_context key in smashing_utils.py. This should fix it up!

Don't reference organism_name in job_context for smasher jobs.

---

api/data_refinery_api/views.py
common/data_refinery_common/migrations/0046_compendium_version_number.py
common/data_refinery_common/models/models.py

#1829 
This PR adds a migration that takes all `compendia_results` that are normalized comependia (quant_sf_only=False) and assigns a `compendium_version` based on its row number when grouped by `primary_organism` and sorted by its `computational_result`'s `created_at` date.
This PR also: (sorry)
- prevents compendia from not showing up when `/compendia?latest_version=True`
- fixes the reverse alphabetical order of the `/compendia` endpoint
- removes the check on compendium_resuls.get_computed_file for is_compendia since it is no longer being set!
None / API / Model / Common Migration
I've run the query on production and the migration locally.

correct compenium version based on computational result created at date

---

workers/data_refinery_workers/processors/qn_reference.py

Our human QN target is mostly NULL values. This makes a lot of things bad.
This will prevent QN targets from being made like this in the future, because any samples that have any NULL values will not be used for the QN target.
These methods were discussed in advance with @jaclyn-taroni and @cgreene 
We probably should get some better unit tests for this, but for now let's get this out so we can fix this big bug.

Don't use samples with NULL values in QN targets.

---

api/data_refinery_api/views.py

N/A
The `/jobs` endpoint has a parameter `?nomad` to return the jobs that are currently running. 
This adds a check to ensure the jobs are actually running.
None

Filter running nomad jobs on endpoints

---

common/data_refinery_common/migrations/0047_clean_compendia_files.py

#1849 
We are moving away from using the attribute `is_compendia` on a `computed_file` so part of moving away from that is to stop saving the other files generated during the `create_compendia` process.. We were saving a tsv and an annotations file to the DB but not persisting to S3. 
This PR includes a migration that selects all normalized compendia where there are more than 1 associated computed files and deletes the files where `is_compendia=False`
None.
Not really breaking though.
I ran the migration locally but also want to try it on staging first!

create migration to remove extra computed_files

---

api/data_refinery_api/settings.py

#1562 
This PR disables the api server side cursors. I just want to see if this will fix issue 1562, I was able to run API locally with this setting off.

disable api server side cursors

---

foreman/data_refinery_foreman/foreman/management/commands/test_create_quantpendia.py

N/A
Fixes the compendia test that is failing in `dev`
```
======================================================================
FAIL: test_compendia_command (data_refinery_foreman.foreman.management.commands.test_create_compendia.CompendiaCommandTestCase)
----------------------------------------------------------------------
File "/home/user/data_refinery_foreman/foreman/management/commands/test_create_compendia.py", line 36, in test_compendia_command
self.assertEquals(processor_job.datasets.first().data, {'GSE51088': ['GSM1237818']})
AssertionError: {'GSE51088': []} != {'GSE51088': ['GSM1237818']}
- {'GSE51088': []}
+ {'GSE51088': ['GSM1237818']}
```
Ran test locally

Fix compendia test, we were filtering out unprocessed samples

---

workers/data_refinery_workers/processors/create_compendia.py

#1962 
This adds back the 2 lines that send the csv to the output directory before zipping the `output_dir`
```create_compendia.py```
None.

fix compendia output file

---

workers/data_refinery_workers/processors/smashing_utils.py

https://github.com/AlexsLemonade/refinebio/pull/1952
We refactored _process_frame to sometimes return None and we didn't check its output everywhere we used it. This broke the compendia jobs.
Unit tests should have caught this before :thinking:

Fix checking the return value of process_frames.

---

common/data_refinery_common/job_lookup.py
config/readable_affymetrix_names.csv
foreman/data_refinery_foreman/foreman/main.py

#1831 
Whole lotta failures with:
```
2019-12-06 14:27:35,482 i-056f1616d982e5f85 [volume: 0] data_refinery_workers.processors.utils ERROR [no_retry: False] [processor_job: 29481557]: Unhandled exception caught while running processor function _run_scan_upc in pipeline:
File "/home/user/data_refinery_workers/processors/utils.py", line 369, in run_pipeline
last_result = processor(last_result)
File "/home/user/data_refinery_workers/processors/array_express.py", line 149, in _run_scan_upc
platform_name = get_readable_affymetrix_names()[platform_accession_code]
KeyError: 'huex10st'
```
We added a new platform but not a readable name for it. This fixes that. This also gives Affy a higher RAM tier it can go to since we expect this platform to be big enough …

Give affy jobs a higher tier and add a readable name for huex.

---

common/data_refinery_common/migrations/0048_processorjob_abort.py
common/data_refinery_common/models/jobs.py
common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/surveyor/test_end_to_end.py
workers/data_refinery_workers/processors/utils.py

Reverts AlexsLemonade/refinebio#1989
Originally failed with the error:
```
Running migrations:
Applying data_refinery_common.0048_processorjob_abort...Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.IntegrityError: column "abort" contains null values
The above exception was the direct cause of the following exception:
File "manage.py", line 23, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in …
```

Bring back "Possible solution to avoid removing jobs from db"

---

common/data_refinery_common/migrations/0048_processorjob_abort.py
common/data_refinery_common/migrations/0049_processorjob_abort_alter.py
common/data_refinery_common/models/jobs.py
common/data_refinery_common/models/models.py
foreman/data_refinery_foreman/surveyor/test_end_to_end.py
workers/data_refinery_workers/processors/utils.py

N/A
The last deploy failed while executing the migration `0049`:
```
Running migrations:
Applying data_refinery_common.0048_processorjob_abort... OK
Applying data_refinery_common.0049_processorjob_abort_alter...Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.extensions.QueryCanceledError: canceling statement due to statement timeout
```
Looks like the `batch_update` from migration `0048` left 1.5mm rows with NULL values (not sure why). The next migration timed out when setting them to their default value `False`.
I updated those rows on the DB with:
```
data_refinery=> UPDATE processor_jobs SET abort='f' WHERE abort IS NULL;
UPDATE 1452029
```
Now, `0049` …

Revert "Revert adding a migration with new fields on processor jobs"

---

api/data_refinery_api/middleware.py
api/data_refinery_api/settings.py
api/data_refinery_api/urls.py
api/data_refinery_api/views.py

#1795 
This PR ensures that the response type for 404 and 500 errors will be JSON. 
If a 404 error will be returned it will check to see if the request began with `r"^/v[1-9]"` and if so it will respond with a message mentioning that the api is versioned.
Also, the 404 errors will return a link to the docs.
`data_refinery_api/urls.py`
Tested with debug = False

Unversioned API response

---

api/data_refinery_api/views.py

#2005 
The requests to the stats page with a range param was broken? 
It looks like this was just because the start time was erroring out.
This PR should include the correct start time with no error.

fix starttime for ranged stats requests

---

api/requirements.in
api/requirements.txt
common/requirements.in
common/requirements.txt
foreman/requirements.in
foreman/requirements.txt
workers/data_refinery_workers/downloaders/requirements.in
workers/data_refinery_workers/downloaders/requirements.txt
workers/data_refinery_workers/processors/requirements.in
workers/data_refinery_workers/processors/requirements.txt

This replaces some of the auto-PRs that got generated.
Django released some security updates. This lets us take advantage of them.
We can't go up to Django 3.0.1 until https://github.com/sabricot/django-elasticsearch-dsl/pull/233 is released.
- Version Increase
I've run the API and hit it to make sure all the versions work  together.

Bump django versions

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/create_quantpendia.py
workers/data_refinery_workers/processors/smashing_utils.py
workers/data_refinery_workers/processors/test_compendia.py
workers/data_refinery_workers/processors/test_smasher.py

close #1838 
This adds `job_context['filtered_samples']` to keep track of the samples that are dropped at each step during the smashing pipeline. Then creates the file `filtered_samples_metadata.json` with the samples that were filtered and the reasons why - as described by https://github.com/alexslemonade/refinebio/issues/1838#issuecomment-559143625
Added tests for a compendium where we skip one sample.

Keep track of which samples are filtered in the compendia

---

api/data_refinery_api/serializers.py

#1993 
fixes small bug where the organism name wasn't appearing in the results for 
`/v1/transcriptome_indices/1`

add source for organism name

---

api/data_refinery_api/views.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/settings.py

#1944
Include additional information in slack notifications when new datasets are submitted or they fail processing.
Tested sending notifications to #robots

Improve slack notifications when datasets are submitted

---

workers/data_refinery_workers/processors/smasher.py

close #1944 
Ensure `SMASHER` jobs are not retried after we send a notification to users. These jobs will still be retried multiple times until the notification is sent.
None

Send a single email on smasher jobs

---

api/data_refinery_api/serializers.py

#1692
LGTM noticed that this wasn't a static method but that it was being used as such. It does look like it was intended to be a static method:
http://ses4j.github.io/2015/11/23/optimizing-slow-django-rest-framework-performance/
This may be dead code though. Unless there's some magic where this gets called (the blog post suggests one must intentionally call it if I'm reading it correctly) the code does not appear to get used in our project.
N/A

make static method static

---

workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/smashing_utils.py
workers/data_refinery_workers/processors/test_smasher.py
workers/data_refinery_workers/processors/utils.py

close #1923 
Datasets failure reason is now set on `end_job`, for jobs associated with a dataset.
Also reduced the scope of several `try...except` since all exceptions are handled on `run_pipeline`.
None

Ensure datasets are marked with errors when processing fails

---

.circleci/config.yml
README.md

#2033 
In #2033 we reformatted all our code using `black`. However we didn't add any check to make sure that all contributions pass `black`'s lint. This replaces our previous syntax check which used flake8 with `black . --line-length=100 --check --quiet`. This command will output nothing and exit with status code 0 if everything is okay, otherwise it will complain so the check fails.
I made sure that a syntax issue would make black complain. Other than that this should be covered by unit tests.

Change the circleci syntax check to make sure that black runs

---

README.md

n/a 
fixes a typo that was preventing markdown from creating a hyperlink with custom text

Fix markdown syntax issue in README.md

---

api/data_refinery_api/serializers.py

https://github.com/AlexsLemonade/refinebio-frontend/pull/825
We tend to interchangeably use `organisms` and `organism_names`
This PR intends on making the use of `organism_name` or `organism_names` when the attribute does not contain a serialized model but instead contains only a string of the name. ie `HOMO_SAPIENS`
Loading experiments locally

use _names suffix when only returning organisms' name

---

api/data_refinery_api/views.py
workers/data_refinery_workers/processors/smasher.py

https://github.com/AlexsLemonade/refinebio/pull/2014
Deepa noticed her datasets failed this morning.
We were deleting the dataset before calculating its size. This switches it so we calculate the size of the dataset before deleting it.
This has affected datasets since the 4th of January. I will rerun those jobs once this change is deployed.
This stuff won't even happen locally, which is probably why it never came up before. We should probably improve these tests more but right now I wanna get this bug fixed.

Fixes the order in which we run parts of the smasher pipeline 

---

workers/data_refinery_workers/processors/salmon.py

#2054
We were associating all samples in an experiment with the `ComputationalResult` that `tximport` generated. This removes that code.
We still associate the samples with the computational result below, but we ensure the samples are present in the actual tximport output.
In addition to these changes, we'll need to find a way to fix the inaccurate data from prod.
None

Don't associate all samples with tximport result

---

workers/nomad-job-specs/smasher.nomad.tpl

close #2030 
The env variable `ENGAGEMENTBOT_WEBHOOK` was not declared for the smasher instance, this ensures it get's set.
None

Add slack web hook to the smasher env variables

---

common/data_refinery_common/migrations/0052_remove_invalid_tximport_associations.py

close #2054 
Removes associations between tximport computational results and samples that are not processed.
Ran migrations locally

Add migration to remove invalid tximport associations

---

infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
infrastructure/instances.tf
infrastructure/variables.tf

#2072
I got an error in terraform when deploying:
```
Error: resource 'data.template_file.foreman_server_script_smusher' config: unknown variable referenced: 'aws_secret_access_key_client'; define it with a 'variable' block
Error: resource 'data.template_file.foreman_server_script_smusher' config: unknown variable referenced: 'aws_access_key_id_client'; define it with a 'variable' block
```
This adds the two variable blocks. Also saw this comment:
> Annoyingly, TF can't have computed variables (${env.USER})
> as default values for variables. So `TF_VAR_user=rjones tf plan`, etc.

Seems like variables need to be declared in terraform

---

common/data_refinery_common/models/models.py
workers/data_refinery_workers/downloaders/array_express.py

#2031 
It was impossible to retry samples where a potential fix was created. This PR adresses that.
`OriginalFile::has_blocking_jobs`
When checking if an original file has blocking jobs we first check if there are processor jobs where `no_retry=True` and  exclude where `abort=True`
However if we think that the error in processing that sample/original file has been resolved this prevents us from being able to queue up that file again. So this PR adds checking against the current version (same as `processor_job_instance.worker_version`) so the job will not be retried unless their has been a new deploy.
None.

Only prevent retry of jobs if no_retry job was current version.

---

infrastructure/disk.tf

#2043 
Metrics for compendia downloads. This is the terraform code to enable request level logs for the compendia bucket (staging and prod when deployed) this allows us to use CloudWatch Metrics to get the number of `GetRequests` that were made on Objects (compendia archives) in the bucket.
`infrastructure/disk.tf`
None.

Enable Compendia Bucket Request Level Metrics

---

foreman/data_refinery_foreman/surveyor/transcriptome_index.py

#2035 
`taxonomy_id` of for Candida Albicans refers to https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1094983, `species_taxonomy_id` refers to https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=info&id=5476, which is what we want. Therefore we'll now check for this key and use it if it's present.
The tests actually pass now!

More special handling for Ensembl's APIs.

---

common/data_refinery_common/models/organism.py
common/data_refinery_common/models/test_organisms.py
workers/data_refinery_workers/processors/transcriptome_index.py

#2096 
We were trying to ask NCBI for taxonomy ids for names like Candida_albicans_sc5314_gca_000784635. This didn't work but the lookup code returned a taxonomy id of 0 for some dumb reason. (Almost certainly my fault from a long time ago.)
This meant that when I tested one locally it would go into the DB with a taxonomy_id of 0, which worked once but the second one would violate a DB constraint and fail the job.
I've created a transcriptome index for E. coli and am currently running processing SRP242240 locally to test it.

Fix transcriptome indices for microbes.

---

foreman/data_refinery_foreman/surveyor/test_end_to_end.py
test_volume/cassettes/surveyor.test_end_to_end.transcriptome_redownloading.yaml

#2110 
It's kinda frustrating that this happened now, but it wasn't really my fault!! Ensembl released a new version and this broke our tests. I think this is more or less what we wanted to happen.
Unit tests are working again!

Fix the cached test data that got broken by an Ensembl release

---

api/data_refinery_api/middleware.py

https://github.com/AlexsLemonade/refinebio-docs/pull/122 We need to show refinebio's version on the docs
In order to be able to get this header in a request from the docs, we need to expose it with another header.
None

Expose X-Source-Revision header in CORS requests

---

api/data_refinery_api/views.py
workers/data_refinery_workers/processors/smasher.py

N/A
Remove the channel when posting a new download on the engagement bot, so that messages are posted to the default hook channel. This will make it easier to change this with the slack configuration.

Post engagement bot to default hook channel

---

foreman/data_refinery_foreman/surveyor/test_end_to_end.py
test_volume/cassettes/surveyor.test_end_to_end.transcriptome_redownloading.yaml

Noticed it was breaking tests for #2130
Ensembl released a new version. This means that our VCR requests got out of date. I guess we'll just have to update these every now and then :man_shrugging: 
This is a test fix so the tests test my fix for the tests.

Fix transcriptome tests by updating VCR requests with new Ensembl version.

---

foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py
workers/data_refinery_workers/processors/create_compendia.py

#2114 
Remove Submitter Processed Data from compendium datasets. 
In the management command we loop through all of the samples to make sure they are processed. This adds an extra clause to that to exclude any samples where the result's process name is `Submittter-processed`. Which is as far as I can tell the best way to check for this sort of thing.
Was unable to run nomad locally.. something about unable to bind to port... so running tests here and will request review after I am able to run them locally.

Compendia without submitter processed data

---

common/data_refinery_common/models/original_file.py
workers/data_refinery_workers/processors/utils.py

Not sure, but this started breaking intermittently yesterday.
Our transcriptome index jobs weren't handling a missing file quite correctly. This adds an additional check to `needs_downloading` to make sure they only recreate downloader jobs if they're the last processor job for the file.
The tests pass reliably!!!

Add an extra check to needs_downloading for transcriptome index jobs.

---

workers/data_refinery_workers/processors/smasher.py

N/A just saw some smasher jobs failing.
The query doesn't time out unless we order it. Order isnt important here, so dont.
I've tested that the query won't time out if we just take the first result rather than the `first()` result.

Fix smasher job database timeout for large datasets

---

.circleci/filter_tests.sh

close #2145 
This ensures that `filter_tests.sh` exits on failure. 
None

Ensure `filter_tests.sh` fails if the tests fail

---

infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

https://github.com/AlexsLemonade/refinebio/issues/1838
https://github.com/AlexsLemonade/refinebio/issues/2114
We want to recreate compandia so they have the changes from the two issues above.
This makes the smasher instance huge and makes the nomad job spec for compenida able to use most of its RAM.
- Devops

Give compendia jobs enough RAM to recreate the large ones.

---

foreman/data_refinery_foreman/foreman/management/commands/get_quant_sf_size.py

#2191 
This script spits out a CSV file like:
```
sample_accession_code,experiment_accession_code,organism,size_in_bytes
SRR8140707,SRP166447,HOMO_SAPIENS,9138640
```
For every sample with a quant.sf file. This is to identify what samples may need reprocessing.
I ran it on my local DB and it generated the output that I pasted above.

Add script to get data on quant.sf file sizes.

---

infrastructure/instances.tf
infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl

https://github.com/AlexsLemonade/refinebio/pull/2200
Time to scale back down. I'm keeping the smasher twice as big standard though so we can run smasher and compendia jobs at the same time.

Scale smasher back now that big compendia are done.

---

common/data_refinery_common/models/original_file.py
workers/data_refinery_workers/downloaders/sra.py

#2006
We found another corner case for the method `original_file.needs_downloading()`. If a downloader job gets OOM-Killed and it's not able to download the file fully, then on further retries we assume that the file is successfully downloaded.
This fixes it by adding an additional check to ensure that the SHA1 of the downloaded file matches what we have in the database. Files that we have never downloaded will get re-downloaded again since we don't have a way to check if it's complete.
@kurtwheeler We also need to increase the memory for the SRA jobs, it seems 1Gb isn't enough for these. Or do we re-try them with higher memory?
None

Allow downloader jobs to run if file is partially downloaded

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

#2006 
We had a 2T volume available for the instances but it was not being mounted correctly. This fixes that. I'm not sure if this would be acceptable since this line depends on the variable `volume_size_in_gb`, every time that this variable is changed we would have to change this line as well. I saw [some PR](https://github.com/AlexsLemonade/refinebio/pull/551/files#diff-903d68d2a6b999a095378b7c4e142d07R41) that did this modification.
At some point, we used to have:
```
ATTACHED_AS=`lsblk -n | grep T | cut -d' ' -f1`
```
However, the result of `lsblk -n` is:
```
ubuntu@ip-10-0-91-161:/var/ebs$ lsblk -n
xvda    202:0    0  100G  0 disk 
└─xvda1 202:1    0  100G  0 part /
xvdb    202:16   0  1.8T  0 disk 
xvdf    202:80   0    2T  0 disk /var/ebs
```
So that doesn't suffice to select the …

Mount correct volume in instance

---

common/data_refinery_common/utils.py
workers/data_refinery_workers/downloaders/sra.py

#2006
I'm running out of theories for this, [reading online](https://stackoverflow.com/a/17473795/763705) I saw that there might be multiple reasons why these `OSError Cannot allocate memory` are raised and that for some of them there isn't much to do from the python script.
This will be capturing the exception, waiting a few secs and retrying the download 3 times before failing the job.
None

Add helper to download url and retry 3 times on error

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

N/A
After the last deploy, the volume wasn't mounted on the spot instance. I tested the commands and they worked afterward.
So I assume the `sleep` before selecting the disk wasn't big enough? @kurtwheeler what do you think?

Increase timeout before mounting volume

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

Slack Posts weren't firing on mondays. This should fix them not being scheduled at all.

Slack downloads cron remove */ before 0 12 * * MON

---

infrastructure/instances.tf
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

#2237
EBS volumes seem to be giving problems when processing because they are going `Read-Only`. This changes the instance type to `c5d.9xlarge` which should come with it's own storage.
This PR should be reverted once the tests pass.
None

Use instance c5d.9xlarge for spot fleet with 900gb disk

---

infrastructure/instances.tf
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

#2237
This should be reverted once we finish processing samples in #2237, since it uses the instance SSD hard drive instead of EBS.
We also want to confirm that this disk doesn't go RO when we are downloading samples.
Tested on dev stack, to ensure that `/var/ebs` was on the drive with `900gb`
```
ubuntu@ip-10-0-67-73:/var/ebs$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            481G     0  481G   0% /dev
tmpfs            97G  8.9M   97G   1% /run
/dev/xvda1      873G  1.6G  871G   1% /
tmpfs           481G     0  481G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           481G     0  481G   0% /sys/fs/cgroup
/dev/loop0       94M   94M     0 100% …
```

Use instances SSD disk instead of EBS

---

infrastructure/variables.tf
workers/nomad-job-specs/create_quantpendia.nomad.tpl

#2246 
We will need to re-process some rna-seq compendias. However, right now they can't run because the smasher uses an `m5.4xlarge` instance with 64GB of RAM and that's the exact amount of RAM required for the job.
This PR reduces the amount of ram required by the RNA-seq compendia so that it can run on the smasher instance.
None

Reduce the RAM requirements for the quantpendia

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh

#2006
Let all instances default to volume `0` for now.

Set correct index for EBS volume

---

common/data_refinery_common/utils.py

#2237
Increase downloads buffer size to 4mb to see if that prevents the disk from going read-only

Increase downloads buffer size to 4mb

---

scripts/run_all_tests.sh
scripts/update_my_docker_images.sh
workers/data_refinery_workers/processors/utils.py

N/A
Stop using `pip freeze` to detect the installed package versions. It looks like their output syntax changed slightly and broke our code. Now, if a package is installed from a local file `pip freeze` outputs e.g.
```
data-refinery-common @ file:///home/user/common/data-refinery-common-1.0.0.tar.gz
```
instead of
```
data-refinery-common==1.0.0
```
Instead, there is a new `pip list` command that does what we want, and we can set it to output json instead for easier parsing.
All of the tests now pass again.

Switch from pip freeze to pip list in get_pip_pkgs

---

.circleci/config.yml
.circleci/fix_ca_certs.sh

Temporary relief for #2285
Apparently some root certificate expired on the 30th of May which was the cause of our problems. I adapted the instructions from https://stackoverflow.com/questions/62107565/wget-and-curl-stopped-working-with-https-wrongly-complain-about-an-expired-cert, but for some reason we have to update ca-certificates before removing the line from the config file to get it to work.
The tests successfully download Nomad now!

Fix the tests by updating CA certificates

---

scripts/install_nomad.sh

#2300 
This same CA issue seemed to be affecting the Nomad lead server. This should fix it anywhere Nomad is installed.

The same CA certs were broken on the nomad server!!!

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio/issues/2301#issuecomment-644144431
https://api.refine.bio/v1/samples?accession_codes=123,789 already works, but we don't have a way to do similar filtering with experiments. This is because we moved the advanced filtering to the `/search` interface, and then didn't add a field for accession codes. This PR addresses that, adding the additional field for accession codes and testing that filtering works for both endpoints.
The unit tests work after the change, but not before.

Allow experiments to be filtered by multiple accessions.

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh

#2237 
I read in a comment [here](https://kig.re/2018/05/15/aws-ebs-c5-read-only-file-system.html) that filesystems switching to read-only could be related to an issue that was patched in linux `4.4.0-1067` but our servers are still running `4.4.0-1050-aws`.
Original comment:
```
We ran into a similar problem today. This was not the first time we ran into this issue. AWS team suggested us to upgrade kernel to 4.4.0-1067 which according to the support guy had a patched this issue. Why was the fs corrupted has not been answered though. fsck was done to fix the filesystem and kernel was upgraded and AWS support guy insisted us to increase value for nvme io_timeout. I did some digging and found this http://changelogs.ubuntu.com/changelogs/pool/main/l/linux-aws/linux-aws_4.4.0-1067.77/changelog …
```

Upgrade the kernel version when setting up new instances

---

api/data_refinery_api/serializers.py
api/data_refinery_api/tests.py

Fixes #2329
Add more validation to the `validate_dataset` method to disallow more ways to create an invalid dataset.
Any pull request with a methods section requires scientific …

Do not allow non-downloadable samples to be added to a dataset

---

infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh

None
Since we now restart after upgrading the kernel, with the current `monitrc` restarting nomad fails so the instances never actually have nomad start. For some reason `monit` does not like starting scripts without them being prepended by `/bin/bash`.
It may also be appropriate to include a description of …

Fix monitrc for the client instances

---

api/data_refinery_api/serializers.py

Related to [#871](https://github.com/AlexsLemonade/refinebio-frontend/issues/871) for the frontend
The [Experiment Detail](https://api.refine.bio/v1/experiments/GSE23616/) endpoint seems to be missing the `alternate_accession_code` field unlike [Experiment List](https://api.refine.bio/v1/experiments/).
Looks like it was just missing in the serializer for a specific experiment, so I added it there.
The field shows up when the API is hosted locally

Added alternate_accession_code field for Experiment Detail

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py
common/data_refinery_common/models/documents.py

#2322
Back-end fixes for #2187 
Allow filtering by accession_code. I also changed accession_code and alternate_accession_code to keyword fields so that filtering by them in the search works better so that we can do #2187. I think the dashes in `E-GEOD-*` was messing with Elasticsearch when they were text fields so `/search/?search=alternate_accession_code:E-GEOD-44094` was not filtering properly.
I added a test for `alternate_accession_code`, and I ran the API locally to make sure.

Fix accession code filtering, allow searching by alternate_accession_code

---

api/data_refinery_api/tests.py
api/data_refinery_api/views.py

https://github.com/AlexsLemonade/refinebio/issues/1799
I am not sure if we want to call #1799 fixed, but this is at least a good first step since it treats all of the organism names as one term for the facets.
Change the `organism_names` facet to use `organism_names.raw`, since we want to filter based on the organism names themselves instead of the Elasticsearch terms generated.
I modified the ES tests to check that it works as expected. Before the change, the `organism_names` facet was `{'12': 1, 'coli': 1, 'escherichia': 1, 'k[36 chars]': 1}`, and now it is `{'Escherichia coli str. k-12 substr. mg1655': 1}`.
Please attach any screenshots that …

Tweak organism facet

---

infrastructure/instances.tf

N/A
It turns out that the disk on the x1e.4xlarge is too small, so it causes jobs to fail.
Any pull request with a methods section requires scientific review in addition to code …

Remove the x1e.4xlarge because its disk is too small

---

foreman/data_refinery_foreman/foreman/management/commands/test_update_experiment_metadata.py
foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/test_sra.py

Closes https://github.com/AlexsLemonade/refinebio/issues/2186
I modified the SRA surveyor to get the GEO alternate accession from the ENA XML data. I also made sure that the `update_experiment_metadata` management command also works for alternate accessions
I added tests for both the initial survey and the management command that updates the metadata.

Link SRA experiments to their GEO alternate accessions

---

workers/data_refinery_workers/processors/smashing_utils.py

#2211
It looks like an indexing issue was preventing us from copying over any more than the first 100 quant files for each experiment in the smasher. Since the range's third parameter is `page_size`, on the second iteration `i` is `page_size`, so we effectively take `samples[page_size ** 2 : page_size * 2]` which will be empty.
Please attach or link to example input and …

Fix smasher failing to include all samples in large studies

---

workers/data_refinery_workers/processors/create_quantpendia.py
workers/data_refinery_workers/processors/smasher.py
workers/data_refinery_workers/processors/smashing_utils.py
workers/data_refinery_workers/processors/test_create_quantpendia.py

#2289
Mark samples without quant.sf files as filtered so that they are not included in the metadata.
It looks like what was happening was that samples without quant.sf files were not being filtered out properly, so they would still be included in the metadata as samples in the compendia.
I modified the quantpendia unit test, and checked that my fix made it pass.

Fix metadata issues with quant sf files

---

api/data_refinery_api/tests.py
api/data_refinery_api/views/dataset.py

Fixes #2378
Made changes to the dataset validation errors so that users of the API do not have to parse the strings of our error messages to get the non-downloadable accessions out.
I fixed the unit tests to check for the new error style.

Better error messages for the dataset validator

---

workers/data_refinery_workers/processors/salmon.py

Salmon continued to not work on prod.
I looked into why, and it turns out that we were detecting that the sample had two reads when it really only had one. I dug into why and found out that srastats was returning that `sra_num_reads` should be 2, but we interpret that as having more than one read. Instead, let's trust the library strategy first because that should hopefully be more accurate.
Include sufficient detail for reviewers or users that are not expert developers to evaluate the validity …

srastats sometimes lies about the number of reads

---

infrastructure/instances.tf

#2237 
From https://github.com/AlexsLemonade/refinebio/issues/2237#issuecomment-656157201, it looks like there is a kernel bug that is causing the ext4 driver to hit an OOM condition. Looking at issues on the docker GitHub page it looks like people are having issues with 3.x and 4.x kernels, so let's try upgrading to 18.04 which has linux 5.3.

Upgrade to 18.04

---

api/data_refinery_api/tests.py
api/data_refinery_api/views/dataset.py

Came up while fixing https://github.com/AlexsLemonade/refinebio-frontend/issues/909
We were missing some imports in the `dataset.py` file, but these didn't error because they were inside a try-catch block. We also missed this in our tests because it was actually the code that sends the nomad jobs. I made the catch block log the error instead of just passing, and I modified the tests so we check that branch too.
Downloading a dataset with my local instance and using the patched frontend works now!

Fix dataset endpoint

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
infrastructure/nomad-configuration/pg-bouncer-instance-user-data.tpl.sh

N/A deploy problems
Terraform failed trying to expand `${name}`, which was used inside comments.

Whoops, terraform expands template variables inside comments

---

infrastructure/deploy.sh

Fixes https://github.com/AlexsLemonade/refinebio/issues/2401
Our deploy script sometimes fails while confirming the nomad cluster with exit code 7, which is the `curl` error code for a host not being up. Since we're waiting for the host to come up anyway, let's just ignore `curl` errors.

Ignore curl errors while deploying

---

infrastructure/instances.tf
infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
infrastructure/nomad-configuration/nomad-client.service

None, doing work on prod
Nomad seems way more reliable after I stopped monit from running. Since we only need monit to restart the nomad client when it goes down, let's just use a systemd service instead.
None, we should probably test this on staging first, just spin up a spot instance and make sure that nomad is running.

Use systemd instead of monit for the nomad client

---

infrastructure/instances.tf
infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
infrastructure/nomad-configuration/nomad-server.service

This should fix #2205
In https://github.com/AlexsLemonade/refinebio/pull/2422 we started using systemd to handle starting and restarting the nomad client instead of monit. This PR makes the same change for our other instances that run nomad.
None so far, I should spin up a dev stack to test this first.

Stop using monit to monitor nomad

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

https://github.com/AlexsLemonade/refinebio/issues/2424
The disk is filling up on our instances because we keep queuing downloader jobs to run even though we have a large backlog of processor jobs. Since we already have logic that stops us from queuing too many downloader jobs at once, let's just also include open processor jobs in our calculations of a volume's work depth.
We may have to fiddle with the `DESIRED_WORK_DEPTH` again, I dropped it down to 200 because I was worried 500 might be too much. We have ~800GB of useable space (a bit more than that but just to be safe), so how much space does a worst-case job take up in terms of downloaded raw data and processor output? 
I am running it …

Use the volume work depth to keep track of processor jobs

---

infrastructure/deploy.sh

None, things I noticed while spinning up a dev stack.
Two changes:
- Use the same perl snippet as all of our other scripts that have to be run in a certain directory. I didn't actually run into this, but it seems safer than a comment at the end of the help message.
- Check if `nomad-job-specs` exists before removing it. My first devstack deploy failed because this directory didn't exist but we were trying to remove it.
I tested the parts of the deploy script that I changed.

Fixes to the deploy script

---

foreman/data_refinery_foreman/foreman/main.py
foreman/data_refinery_foreman/foreman/test_main.py

#2424 
Lower the desired work depth to 100, since our disk was still just about filling up. It looks like those salmon jobs took >4gb on average. Our small instances run less than 100 salmon jobs at a time, so we are still not throttling ourselves too much.
N/A

Lower desired work depth

---

foreman/data_refinery_foreman/surveyor/array_express.py
foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/test_array_express.py
foreman/data_refinery_foreman/surveyor/test_sra.py

https://github.com/AlexsLemonade/refinebio/issues/2438
Turns out we haven't been parsing ENA metadata correctly. `parse_datetime` returns None if the string is only a date. This fixes it and verifies it with tests.
Unit tests cover it well.

Parse dates correctly in sra surveyor.

---

workers/data_refinery_workers/downloaders/sra.py

None
We were failing to catch `ftplib.error_perm: 550 Failed to change directory.` because I forgot to import `ftplib` to catch `ftplib.all_errors`.
None

Add missing ftplib import

---

api/data_refinery_api/settings.py

#2459
[This](https://stackoverflow.com/questions/62216837/django-view-causes-psycopg2-cursor-does-does-not-exist-error) StackOverflow post suggests disabling cursors if you are running with pgbouncer. We'll see if it works. This would also explain why it works locally but not in the cloud.
The API still works locally.

Try disabling cursors

---

foreman/data_refinery_foreman/foreman/management/commands/update_experiment_metadata.py
foreman/data_refinery_foreman/foreman/management/commands/update_sample_metadata.py

I think this is what was causing https://github.com/AlexsLemonade/refinebio/issues/2462
Some of our experiments have an invalid library type, which causes an exception to be thrown in the surveyor. We should catch exceptions so it doesn't kill our management command every time we run into a bad experiment.
None

Catch exceptions raised while refreshing metadata

---

workers/dockerfiles/Dockerfile.downloaders

Fixes https://github.com/AlexsLemonade/refinebio/issues/2479
Apparently HCC (Holland Computing Center) [has Aspera on their conda repo](https://anaconda.org/HCC/aspera-cli/files), so let's install Aspera from there instead.
I can't find another good way to install Aspera, because it looks like downloads.asperasoft.com was taken down, but I can't navigate the new IBM downloads page without an IBM account. And even if I made an account, it's not clear how we could then download the aspera cli in our docker images that don't have access to our credentials.
All of the tests still pass locally, and they fail if Aspera isn't installed.

Install aspera from HCC's conda repo instead

---

foreman/data_refinery_foreman/surveyor/sra.py
foreman/data_refinery_foreman/surveyor/test_sra.py
test_volume/cassettes/surveyor.sra.survey_nonexistant.yaml

None, I was digging into an error message I saw while running the management command to refresh experiment metadata.
Before, the actual exception you would see when you try to survey an SRA accession that doesn't exist would be a `KeyError`, but now you will only see the message that no experiment was found.
I looked at the error messages before and after using the `test_survey.sh` script.

Better error message for missing SRA experiment

---

.github/scripts/git_decrypt.sh

#2501's deploy failed
A raw `cd` seemed to work in `install_git_decrypt.sh`, so maybe doing it like that is better in github actions? If not I plan on learning where things happen in actions.
Can't really without a deploy. I want to test this on staging.

Try to fix and/or debug why the git_decrypt.sh script broke.

---

.github/scripts/git_decrypt.sh
.github/scripts/remote_deploy.sh

The path was breaking cause we hardcoded what we shouldn't have. I think this is everywhere that's not run on the deploy box, which doesn't need a new root.

Use github workspace env var correct paths.

---

.github/scripts/git_decrypt.sh
.github/scripts/remote_deploy.sh
.github/workflows/config.yml

#2506 
`$GITHUB_WORKSPACE` was supposed to have the path, instead it just had `refinebio`. This should work based off of some debugging I did a few PRs ago.

Use a hardcoded path because github actions docs seem off

---

.github/scripts/remote_deploy.sh

#2511 
We got further along! Ran into another path that was broken for github actions. Hopefully the last one (should be for cd and source, not sure what other paths there might be).

I got all the paths for `cd`, now I got them for `source` as well

---

infrastructure/deploy_box_instance_data.sh

#2517 
AWS's cli wasn't available for the deploy. I already installed it on the deploybox, but that should be added here as well.

Install aws cli on deploy box startup.

---

infrastructure/instances.tf

Smasher ran out of disk space and stopped smashing.
Raise disk size so we don't interrupt processing.

Raise smasher disk size for quantpendia processing.

---

api/data_refinery_api/urls.py

#2535 
Adds a url for swagger to determine the supported schemes
I would also recommend basing this off of the env down the road but this will make the local, stage, and prod all create requests against prod.

swagger https on prod always

---

infrastructure/deploy.sh
infrastructure/nomad-configuration/prepare-client-instance-user-data.sh

N/A, I was trying to run some stuff and tracked this down
The node instance startup script wasn't really running because it was `mv`ing the base script instead of `cp`ing it. I checked the instance's user data script and its first line was `exit 0`.
- Devops

Fix the way the user instance data script was prepared for the nomad nodes.

---

README.md
infrastructure/disk.tf
infrastructure/instances.tf
infrastructure/nomad-configuration/client-smasher-instance-user-data.tpl.sh
infrastructure/permissions.tf
infrastructure/variables.tf
workers/nomad-job-specs/create_compendia.nomad.tpl
workers/nomad-job-specs/create_quantpendia.nomad.tpl

https://github.com/AlexsLemonade/refinebio/issues/1733
Also relevant:
* https://github.com/AlexsLemonade/refinebio/issues/2121 (because at this point, the client instances can run without EBS volumes, and only the smasher needs it, so we don't need to make a number of EBS volumes anymore.)
* https://github.com/AlexsLemonade/refinebio/issues/2363 (still true)
* https://github.com/AlexsLemonade/refinebio/issues/2234
This PR mounts a large EBS volume onto the smasher instance and fixes the needed permissions.
It also tweaks the sizes of things for some processing I want to do.
- Devops

Larger smasher volumes

---

ami/instance-user-data.tpl.sh

N/A API went incommunicado again Friday
Apparently this happens if you don't have the setting. See https://medium.com/spaceapetech/what-the-arp-is-going-on-b4bc0e73e4d4
I don't know why that isn't set by default...
I can't really, although I can confirm it doesn't fail if I change the setting the other way the tool recommended.

Change setting to disable ARP for our instances.

---

api/data_refinery_api/views/original_file.py

#2351  Issue Number
#2573 worked!!
Now that we know what was breaking the original_files endpoint, we don't need this shot in the dark! I'd rather leave it as it was in case it messes with any of the job reporting stuff Ariel did.

Readd jobs to original file endpoint since we know what the actual issue was now.

---

infrastructure/variables.tf

#2552 
This gets overwritten in staging, but needed to be changed for prod as well.

500 GB is the smallest for ST1s.

---

workers/R_dependencies/affymetrix/versions.tsv
workers/affymetrix_dependencies.R
workers/install_affy_only.R

https://github.com/AlexsLemonade/refinebio/pull/2588
Affy didn't fail until we tried to deploy to staging because we don't build it for tests since it's so huge. This fixes that image, which should fix our deploys.
I built the image locally!! It took a while though.

Fix version of GEOquery for affy image.

---

.github/workflows/config.yml

#2595 
I think the affy image should be able to build, but it did take like 10 hours or something on my local machine. This should be more than enough. I can lower it once we have a better idea of a good upper bound.
- CD options.

Bump up the github actions timeout for deploys to 24 hours.

---

workers/affymetrix_dependencies.R
workers/illumina_dependencies.R
workers/install_affy_only.R
workers/install_downloader_R_only.R
workers/install_gene_convert.R
workers/qn_dependencies.R

#2612 
SCAN.UPC failed to install, but we didn't know because no error was raised. This fixes the `install_with_url` function to fail if any of the packages it is installing fail to install.
I put an invalid version and it failed to install it.

Make install_with_url fail if any of its packages fail to install.

---

.github/workflows/config.yml

#2615 
This got deprecated: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
I think this should do the same thing: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
The deploys are only tested on deploys.

Fix Github Actions set-env change that broke our deploys

---

.github/scripts/pull_docker_images.sh
foreman/data_refinery_foreman/surveyor/geo.py
foreman/data_refinery_foreman/surveyor/test_end_to_end.py
test_volume/cassettes/surveyor.test_end_to_end.geo_celgz_redownloading.yaml

#2631 
There's one affy test that's failing, and it turns out it's because it started getting OOM killed. My guess is that a new version of the mouse probe mappings had more probes which required more RAM than used to.
This experiment had a couple `.CHP` files in it that were getting downloader jobs so I expanded our filter to take them out.
I don't really think this changes too much scientifically other than that we're now testing zebrafish instead of mice.
Unit tests pass locally!

Switch to a zebrafish experiment because the mouse one was getting OOM killed.

---

.github/scripts/pull_docker_images.sh
.github/scripts/push_docker_images.sh
.github/workflows/config.yml
scripts/prepare_image.sh

N/A our tests started breaking
We were getting an `unknown blob` error while pushing docker images to `docker.pkg.github.com`. Apparently `ghcr.io` is a new service that does the same thing, and using causes those errors to stop.
I had to add a personal github token to the repo for this because it's still in Beta, so they normal github token didn't cut it.
Tests are now passing in CI.

Switch to Github Container Repository

---

.github/workflows/config.yml
workers/nomad-job-specs/create_compendia.nomad.tpl
workers/nomad-job-specs/create_quantpendia.nomad.tpl

N/A tests started failing
I'm not sure why, but for some reason pulling the docker cache only filled up the disk without actually making the docker builds faster. There may be a better fix that doesn't, but I want to get tests working and they may change a bit with the Batch cutover anyway.
They pass!

Fix tests failing in Github Actions due to space constraints

---

common/data_refinery_common/models/sample.py
workers/data_refinery_workers/processors/smashing_utils.py
workers/data_refinery_workers/processors/utils.py

#2646
Include columns for datasets, compendia, and quantpendia that specify what processor type, processor ID, and processor version was used for each sample so that the user has access to this information.
New feature (non-breaking change which adds functionality)
I ran the compendia unit tests to make sure none got broken from this change.
I'm making this a draft PR because I'm not totally sure if I'm adding the correct stuff to the metadata.
Right now, I'm getting the processor information through the results objects that are associated with each Sample object.
The processor id and name seem correct to me, but I'm not so sure about the version.
It seems like the version I'm adding right now is actually a refine.bio version instead of the …

Add processor information to sample metadata

---

common/data_refinery_common/job_management.py

https://github.com/AlexsLemonade/refinebio-examples/issues/455
We found an experiment GSE99039 that has raw data but was processed using NO_OP. This is my best guess at what the issue is, but I have neither reproduced this yet nor tested this fix.
Right now we just use the first original file passed to this function. This instead only uses that if there's no original file with raw data.
TBD

[WIP] Make jobs prioritize processing raw data

---

foreman/nomad-job-specs/surveyor.nomad.tpl

#2697 
I wanted to test #2697 but when I went to queue up the surveyor job for it it wouldn't get queued because we require surveyor jobs to run on the smasher instance, and we don't have a smasher instance for the staging stack unless we deploy a full stack.
This used to make sense when we were running at scale but right now it's just getting in the way of testing things on the staging stack and we won't be running at scale again until the Batch cutover happens, at which point this won't even be relevant any more.
This is just operational, and I haven't tested it yet. I will test on staging.

Don't force surveyor jobs to be run on smasher instances.

---

infrastructure/instances.tf

https://github.com/AlexsLemonade/refinebio/pull/2669
https://github.com/AlexsLemonade/refinebio/issues/2663
https://github.com/AlexsLemonade/refinebio/issues/2663 only rate limited individual users of our API, but multiple users could hit us simultaneously and cause us to hit our ES rate limit. This bumps up the size of the ES instance so that it can handle more requests. I'm going to see how this change affects our 500 rate once it lands.
- Scaling
I haven't, this should be a simple change.

Bigger ES instance because we were hitting rate limits.

---

api/data_refinery_api/settings.py

N/A I fixed it rather than open an issue
These overly restrictive limits were an attempt to reduce load on ES, but that was the wrong way to do it because there's nothing stopping multiple users from making requests simultaneously. 
N/A just a config change.

Our throttle limits were so low we throttled our own frontend.

---

.github/workflows/config.yml

N/A Jay pointed out the weekly digests have stopped
We don't use one of these for staging, so it doesn't need to be namespaced for the env, just set blank during staging.
N/A only testable via deploys

Pass through the engagement webhook correctly.

---

api/data_refinery_api/test_imports.py
common/data_refinery_common/test_imports.py
foreman/data_refinery_foreman/test_imports.py
workers/data_refinery_workers/downloaders/test_imports.py
workers/data_refinery_workers/processors/test_imports.py

Fixes #2749 and #1348
When we run our tests, we sometimes filter based on specific tags. Django has a bug/feature that means that if it cannot load a specific test file, it just skips it. This turns out to be a necessary part of our tests, because, for example, only the compendia docker image contains all the packages needed to successfully import the compendia processor.
Unfortunately, a side effect of this is that even when we are on the right docker image, tests can sometimes fail silently. This fixes that by adding a test corresponding to each project/tag which imports each relevant test file dynamically, to make sure that no exceptions are thrown.
All of the tests pass, except the …

Add tests that make sure we can import our test files

---

foreman/data_refinery_foreman/foreman/test_end_to_end.py
foreman/requirements.in
foreman/requirements.txt
foreman/run_end_to_end_tests.sh
infrastructure/permissions.tf
infrastructure/policies.tf
infrastructure/variables.tf
workers/batch-job-templates/smasher.tpl.json

https://github.com/AlexsLemonade/refinebio/issues/2762
This end to end test creates database objects that reference files that exist in the test assets bucket and uses them to smash up a dataset.
It uses the python client to create the dataset through the API! This was actually easier than any other option!
The tests pass when I run them against a dev stack.

Smasher end to end test

---

scripts/update_models.sh

Fix #2760
The old version scheme was not PEP 440 compatible, so there was a deprecation warning every time we installed the data_refinery_common package that might eventually turn into an error in future pip versions.
From https://www.python.org/dev/peps/pep-0440/#version-scheme, `0.0.0.devN` is a valid PEP 440 version, so we'll use that instead.
I built some docker images locally and verified that the deprecation warning no longer appears.

Change version scheme for local versions

---

.github/scripts/remote_deploy.sh
.github/scripts/slackpost_end_to_end.sh
.github/workflows/config.yml
api/data_refinery_api/settings.py
common/data_refinery_common/logging.py
common/data_refinery_common/settings.py
foreman/batch-job-templates/surveyor.tpl.json
foreman/data_refinery_foreman/settings.py
foreman/run_end_to_end_tests.sh
infrastructure/permissions.tf
infrastructure/policies.tf
infrastructure/secrets.tf
infrastructure/variables.tf
workers/batch-job-templates/affymetrix.tpl.json
workers/batch-job-templates/create_compendia.tpl.json
workers/batch-job-templates/create_qn_target.tpl.json
workers/batch-job-templates/create_quantpendia.tpl.json
workers/batch-job-templates/downloader.tpl.json
workers/batch-job-templates/illumina.tpl.json
workers/batch-job-templates/janitor.tpl.json
workers/batch-job-templates/no_op.tpl.json
workers/batch-job-templates/qn_dispatcher.tpl.json
workers/batch-job-templates/qn_reference.tpl.json
workers/batch-job-templates/salmon.tpl.json
workers/batch-job-templates/smasher.tpl.json
workers/batch-job-templates/transcriptome.tpl.json
workers/batch-job-templates/tximport.tpl.json
workers/data_refinery_workers/settings.py

#2584 
The secrets for the Batch jobs have been visible through the Batch UI. This makes them nice and safe in AWS Secrets Manager.
I also tried to fix some of the staging end to end test running in github actions. It's still untested though because it won't be tested until a deploy.
I can run the end to end tests on my dev stack!

Put secrets in AWS Secrets Manager

---

infrastructure/deploy_box_instance_data.sh

#2601
There was an issue with the deploy because boto3 wasn't installed. I installed it on the box using the command I added to this script.

Add boto3 installation to deploybox instance data.

---

infrastructure/deploy.sh
infrastructure/deploy_box_instance_data.sh

#2601 
This moves some code around because the batch-job-templates dir was missing when we went to enumerate the jobs to deregister them.
Add another python dep to the deploybox

Fix deploy script ordering to populate batch-job-templates sooner

---

DEBUGGING.md
common/data_refinery_common/message_queue.py
foreman/data_refinery_foreman/foreman/job_control.py
foreman/data_refinery_foreman/foreman/utils.py

#2601 
If the job queues were full we were logging exceptions because `batch_job_queue` was `None`. We also were dispatching Janitor tests incorrectly because we were appending ram_amount onto the job name when it's not necessary and therefore incorrect.
I'm running end to end tests with this change now to make sure I didn't break the message queue.

Fix a couple small issues with the new send_job function.

---

api/data_refinery_api/test/test_api_general.py
api/data_refinery_api/views/jobs/downloader_job.py
api/data_refinery_api/views/jobs/processor_job.py
api/data_refinery_api/views/jobs/survey_job.py

https://github.com/AlexsLemonade/refinebio-frontend/issues/950
https://github.com/AlexsLemonade/refinebio/issues/2812
https://github.com/AlexsLemonade/refinebio/issues/2791
This removes `nomad` as a parameter to the job endpoints and instead just adds a `is_queued` to all job objects. This field isn't filterable because it isn't added until after the job has been retrieved.
I've also tried to address https://github.com/AlexsLemonade/refinebio/issues/2791 by just making a few more API calls to make sure a bad timing window won't prevent the 429 from being triggered.
I've updated unit tests to test this. I've also run the unit tests a bunch of times to see if I can still trigger …

Add isQueued field to all three job endpoints.

---

infrastructure/instances.tf

https://github.com/AlexsLemonade/AdminItems/issues/357
I either forgot to tag these before or wasn't able to.
The `aws_launch_templates` that are used by Batch don't allow me to tag their EBS resources... Hopefully they just pass their tags down to all resources they spin up...
- Cost tagging
I've run a deploy to make sure this doesn't break terraform

Tag the pg_bouncer, foreman, and API instances with team/project.

---

foreman/batch-job-templates/surveyor.tpl.json
infrastructure/foreman-configuration/foreman-server-instance-user-data.tpl.sh
workers/batch-job-templates/affy_to_pcl.tpl.json
workers/batch-job-templates/create_compendia.tpl.json
workers/batch-job-templates/create_qn_target.tpl.json
workers/batch-job-templates/create_quantpendia.tpl.json
workers/batch-job-templates/downloader.tpl.json
workers/batch-job-templates/illumina.tpl.json
workers/batch-job-templates/janitor.tpl.json
workers/batch-job-templates/no_op.tpl.json
workers/batch-job-templates/qn_dispatcher.tpl.json
workers/batch-job-templates/qn_reference.tpl.json
workers/batch-job-templates/salmon.tpl.json
workers/batch-job-templates/smasher.tpl.json
workers/batch-job-templates/transcriptome_index.tpl.json
workers/batch-job-templates/tximport.tpl.json

https://github.com/AlexsLemonade/refinebio/issues/2823
Not sure what the right thing to do with this is yet, but we need to disable it.
I've stopped the docker container in prod so it's not running.
This is also going to add job timeouts because we shouldn't ever spend more than 3 hours running a job but I saw some jobs today that had been hung since `4:34:00` (and terminating them manually through the console didn't seem to work, I terminated the instance to force them all to end).
- Ops-ing
I've spun up a dev stack to make sure the job timeouts don't break job definitions.

Disable job filler because it's running too many jobs and add job timeout

---

infrastructure/deploy.sh

#2830 
Taint instances because updating the keypair won't cylce instances, despite not updating authorized_keys.

Cycle instances to change SSH keys

---

ami/instance.tf

#2832 
After cycling the instances, the old key was still there because it was baked into the AMI. This removes it. 
I've already updated the AMIs and tested it on staging. (Once the AMIs were updated, I just reran the deploy since they're outside the deploy process.)

Remove SSH key from AMI template

---

foreman/data_refinery_foreman/foreman/test_end_to_end.py

N/A Will and I noticed this in the end to end tests
The end to end tests run right after the deploy, so sometimes the API isn't yet up by the time we're trying to use it to download a dataset.
I ran an end-to-end test against a dev stack, it worked! I tried to have the API down, but I couldn't get it quick enough. I guess staging will be the final test.

Poll the smasher end to end test so it doesn't fail when the API isn't up yet.

---

foreman/data_refinery_foreman/foreman/test_end_to_end.py
foreman/requirements.in
foreman/requirements.txt

Came up while deploying
Because we locked down the S3 buckets, `.sync_from_s3()` no longer works inside the end-to-end tests. Because we were only trying to grab a quant file, the easiest solution is to use the smasher to download the quant file.
I spun up a devstack and verified that the tests pass.

E2E tests: Download the quant file using the smasher

---

api/data_refinery_api/views/stats.py

https://github.com/AlexsLemonade/refinebio/issues/2371
This PR reduces the number of queries we execute as part of the stats endpoint by computing the average time at the same time as the other summary statistics.
This brings the total number of queries we execute on the job tables down to 2. I spent lots of time researching and brainstorming ways to do everything in 1 query, but it turns out that SQL and Django need multiple queries if you want to group by a field for some data and not for other data. I tried to get around this by grouping by `start` (the truncated start time that we use in the timelines) and then computing the other summary stats by iterating through this list, but this ended up being just as slow as the current two queries we have.
I think this is about as much …

Reduce the number of queries on the stats page

---

api/data_refinery_api/test/test_search.py
api/data_refinery_api/views/experiment_document.py
common/data_refinery_common/models/documents.py
common/data_refinery_common/models/experiment.py

Fixes #2840
This PR moves the old behavior to a field called `downloadable_organism_names` field and makes `organism_names` return all of the organism names. I wired up the filters to point to `downloadable_organism_names`, but the frontend takes the data from `organism_names` to populate the UI, so this makes the new behavior consistent with the experiment detail view.
I need to file a tiny frontend PR to go along with this one that just changes the facet name.
I ran the API locally alongside the frontend changes and made sure everything looks right.

Add a separate `downloadable_organism_names` field to the experiment doc

---

foreman/requirements.in
foreman/requirements.txt

https://github.com/AlexsLemonade/refinebio-py/pull/64
This should fix the end to end test because it changes to the exception we're expecting.
The end to end test is already expecting a ServerError, which this switches to.
N/A This should really only affect the end to end tests.

Update pyrefinebio version to fix end to end tests

---

workers/data_refinery_workers/processors/compendia.yml
workers/data_refinery_workers/processors/create_compendia.py
workers/dockerfiles/Dockerfile.compendia

https://github.com/AlexsLemonade/fancySVD/pull/1
The tests broke because of a new fancyimpute version makes the delicate dependency balancing act we were doing fall apart. Therefore I've created a fancySVD package that doesn't need many dependencies. This is much easier to install and I think is maybe even working.
`./workers/run_tests.sh data_refinery_workers.processors.test_imports.ImportTestCase.test_compendia_imports` worked locally!

Trying only switching to fancySVD.

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

N/A Certbot failed to install last night so we had no HTTPS
This is the new recommended way to install certbot. I did this on the prod server last night, so I think it'll work but I can't really test without at least hitting staging.

Install certbot via snap instead of apt.

---

api/data_refinery_api/views/sample.py
common/data_refinery_common/models/sample.py

Closes https://github.com/AlexsLemonade/refinebio/issues/2892
Adds two new `@property` methods to render a sample's attributes and keywords and adds those properties to the Sample view.
We might want to think about tweaking the schema of these dicts or making them only render on the sample detail view.
I ran the API locally and made sure the new output was there.

Add initial implementation of sample metadata to the sample view

---

foreman/requirements.in
foreman/requirements.txt

https://github.com/AlexsLemonade/refinebio-py/pull/67
The end to end tests sometimes failed because the API wasn't returning a JSON body in the error responsed. This updates version of pyrefinebio, which should handle this error correctly now.

Harden end to end tests

---

workers/data_refinery_workers/processors/create_compendia.py
workers/data_refinery_workers/processors/smashing_utils.py

https://github.com/AlexsLemonade/refinebio/issues/2092
Pretty straightforward. We'll see how this works on smaller, then larger compendia.
This option shouldn't be needed any more, so I've just removed it entirely.
Unit tests will cover it some, but then I'll test in prod for scale.

Set compendia results back to public, remove ks-check as an option

---

infrastructure/networking.tf

#2912 failed
It failed with
```
Error: error deleting ACM Certificate (arn:aws:acm:us-east-1:589864003899:certificate/aa11bfaf-4c2c-460f-a8ce-2464816ae6f4): ResourceInUseException: Certificate arn:aws:acm:us-east-1:589864003899:certificate/aa11bfaf-4c2c-460f-a8ce-2464816ae6f4 in account 589864003899 is in use.
```
I pushed a hotfix to see if the extra time would make it work, but it seems to be stalled at the same destroy as last time.
https://github.com/hashicorp/terraform-provider-aws/issues/4537 suggests this might fix it.

Apparently a lifecycle on ACM certs can help with deploys.

---

infrastructure/instances.tf

Remakes #2658
See #2658. It got impossible to merge dev in after git-crypt was removed. Yeah it sat around that long. Ooops.
I ran a deploy with this on top of what's in dev.

Remove temporary parameter group. Stop logging checkpoints.

---

infrastructure/batch/compute.tf

N/A I just thought of this. I should have thought about it sooner but at least I thought about it before instance cycling interrupted a job.
The big compendia jobs that get put into the compendia job queue take like 5 days, which means they'll probably get cycled at some point if they're spot instances. This puts them onto on demand instances.
I'll test this on staging because it has data for it.

Make the compendia queue use on demand instances.

---

infrastructure/batch/compute.tf
workers/batch-job-templates/create_compendia.tpl.json
workers/batch-job-templates/create_quantpendia.tpl.json

#2929 
I think that one instance of that size was more vCPUs then our max, so it never came up and the jobs got stuck at runnable.
Also fixes RAM amounts for *pendia jobs.
I'm going to test in staging because there's enough human/mouse data there already.

Tweaks params for compendia compute env

---

workers/batch-job-templates/create_compendia.tpl.json
workers/batch-job-templates/create_quantpendia.tpl.json

#2931 
The timeout was set for 3 hours. The compendia take more like 5 days I think. This sets it to 10 days, just so that if it takes longer than I thought it won't be wasted, but if it goes past 5 days I'll be checking on it daily to make sure it's not hung.
N/A

Bump the timeouts for compendia to 10 days.

---

common/data_refinery_common/models/computed_file.py

#2935 
I saw this exception a whole lot, which was to be expected since the whole reason we're deleting these files is that these fields are null.
It worked well and cleaned up the files though. There were no samples that needed be requeued, but that's not surprising to me since we've tested `retry_samples --computed-files-not-uploaded` in staging before.
N/A, I'll test again on staging but there's nothing left to be done so we won't even be able to hit this branch point. I think this is low risk though.

Make remove dead computed files less noisy

---

common/data_refinery_common/message_queue.py
foreman/data_refinery_foreman/foreman/management/commands/stop_jobs.py
infrastructure/permissions.tf
infrastructure/policies.tf

N/A This came up while I was running compendia
Stopping a compendia job I don't want to run any more is annoying because it gets retried. This is a better way of doing it.
I've tested this on a dev stack

Add stop jobs command so I don't have to go into the database as much.

---

infrastructure/permissions.tf

https://github.com/AlexsLemonade/refinebio/pull/2959
The API didn't have permission for the result files, so it wasn't able to create presigned URLs for them. Thank god for end to end tests!
I'm running end to end tests locally to verify this, but I couldn't download before this change and I could after so I think it'll work!

Give API permission to generate S3 presigned URLs for results

---

workers/data_refinery_workers/downloaders/transcriptome_index.py

N/A trying to get staging end to end tests to pass
Most of the short original file's properties should be the same, but the absolute file path should not.
It's a bit late to start spinning up a dev stack, but I'll test this on one tomorrow.

Fix transcriptome index file downloading/deletion

---

infrastructure/disk.tf

N/A discovered while pulling some stats
We discovered that a CloudTrail event was failing because of a ResourceNotFoundException. This event was trying to create a log stream inside of `"logGroupName": "/aws/events/data-refinery-compendia-log-group-circleci-pr",`, which seems to be missing the last two characters.
I think this may have been necessary in an older terraform/AWS provider version. The last log event that worked was around June 20th which is around the time we upgraded.
I've deployed a dev stack to make sure it's not broken, but this will really get tested in staging.

Fix aws events log group ARN.

---

.github/scripts/remote_deploy.sh
infrastructure/deploy.sh

N/A came up during the deploy tour
We have determined these checks don't do anything because the GITHUB_ACTIONS env var isn't passed through to the deploy box. I did leave the check for it in `scripts/prepare_image.sh` because that is invoked withing github actions during the tests.
- Remove dead code
This will be checked partially by unit tests, but when this goes into a staging deploy I will double check its outputs to make sure there's nothing that shouldn't be there.

Removes checks from deploy.sh for unused env var

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

#2975 
See if curling ourselves can be a better test for the API server coming up. If the output changes before the target group attachment comes up, then I can use that output to poll until it does. In some cases it might be faster, but it'll also prevent us from ever running into that timing issue again.
- Temporary debugging

Add some changes to API startup for debugging certbot challenge

---

api/run_tests.sh
api/serve.sh
api/serve_production.sh
common/run_tests.sh
config/externally_supplied_metadata/metasra/translate.sh
foreman/run_end_to_end_tests.sh
foreman/run_management_command.sh
foreman/run_tests.sh
foreman/test_survey.sh
infrastructure/deploy.sh
infrastructure/destroy_terraform.sh
scripts/create_virtualenv.sh
scripts/format_batch_with_env.sh
scripts/install_all.sh
scripts/kill_all_jobs.sh
scripts/make_migrations.sh
scripts/prepare_image.sh
scripts/rebuild_es_index.sh
scripts/reinit_database.sh
scripts/run_all_tests.sh
scripts/run_manage.sh
scripts/run_postgres.sh
scripts/run_shell.sh
scripts/update_models.sh
scripts/update_my_docker_images.sh
workers/run_command.sh
workers/run_janitor.sh
workers/run_job.sh
workers/run_tests.sh

#3108 
Stacked on #3106 
The refine.bio .sh scripts have an identical piece of code making sure it runs from the `scripts` directory. It involves running perl code using File::Basename and Cwd modules:
```
script_directory="$(perl -e 'use File::Basename;
use Cwd "abs_path";
print dirname(abs_path(@ARGV[0]));' -- "$0")"
```
This PR changes it to an equal bash code eliminating the perl dependency.
N/A
N/A

Refactor `script_directory` setting logic for sh scripts

---

api/data_refinery_api/views/dataset.py
api/tests/views/test_dataset.py

Resolves #3055 
Change some checks to more readable versions.
Use sets instead of lists for entity IDs tracking (accessions, experiments).
Get rid of str + str.

Update `validate_dataset` to allow for experiments with duplicate samples

---

common/dockerfiles/Dockerfile.migrations
foreman/dockerfiles/Dockerfile.foreman

The
```
#18 7.045   Preparing metadata (setup.py): started
#18 7.168   Preparing metadata (setup.py): finished with status 'error'
#18 7.168   ERROR: Command errored out with exit status 1:
#18 7.168    command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9po9zfhg/psycopg2-binary_557e3f35b68149979eba67a9404b7463/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9po9zfhg/psycopg2-binary_557e3f35b68149979eba67a9404b7463/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_xroqrlo …
```

Add psycopg2 package dependencies.

---

scripts/prepare_image.sh

Hi `AlexsLemonade/refinebio`!
This is not an automatic, 🤖-generated PR, as you can check in my [GitHub profile](https://github.com/p-), I work for GitHub and I am part of the [GitHub Security Lab](https://securitylab.github.com/).
While performing a code search for container registry domains we noticed that this repo contains a misspelled domain name.
If a malicious actor were in control of that misspelled domain, they could potentially perform an attack on the software supply chain of this project and/or steal the credentials used to connect to the container registry (depending on how the misspelled domain name of the container registry is used).
Please fix this typo and check your documentation for similar typos.

Fix typo in container registry domain

---

api/data_refinery_api/views/computed_file.py

N/A
Adding the ability to filter `ComputedFiles` by `filename` to support: https://github.com/AlexsLemonade/refinebio-py/issues/79
N/A
N/A

add filename to filter for computed files

---

workers/tests/processors/test_salmon.py

N/A
This fix was on another PR that was cancelled, this is a PR just for this change.
It just corrects the path of `test_tximport.R` in `test_salmon.py`.
n/a
n/a
n/a

Fix test_tximport.R path

---

foreman/data_refinery_foreman/surveyor/sra.py

#3320
In the latest e2e tests, a SRA surveyor job failed because it could not get the file report. I went to the url that was attempted and the API responded with an error saying that `accession` and `result` were missing. This PR adds a fix for the url construction.
n/a
n/a
n/a

Fix for SRA file report API url construction

---

foreman/data_refinery_foreman/surveyor/sra.py
workers/data_refinery_workers/downloaders/sra.py
workers/tests/downloaders/test_sra.py

#3326 
This PR fixes a bug where variable type was not being checked correctly.
From the e2e tests logs:
> AttributeError: 'dict' object has no attribute 'append'
Additionally, it refactors the `update_sample_protocol_info` method that takes an experiments protocol and adds to the sample to now take a sample and an experiment.
Update:
This PR also contains a fix for the downloaders test. It seems that the particular sample we were testing (also SRA) was not able to be downloaded via ascp.
Also, I noticed that when ENA aspera downloader performed a retry, the original_file parameter was missing which caused it to try to use the NCBI instead of ENA configuration for downloading.
To replace the sample tested in the downloader @jaclyn-taroni provided the following query:
```bash
curl -X POST …
```

Refactor sample_protocols update

---

workers/data_refinery_workers/processors/salmon.py

N/A
We are now pulling NCBI SRA data from s3. When we go to determine the transcriptome index length to process these files we need to use `sra-stat` to read the file. In order for that code path to execute we need to ensure that we define `sra_file_input_path`.
Note: I think it would be better instead of looking at the download source, to instead inspect the file to determine its type before determining index length.
n/a
n/a tested locally
N/A

add s3 to sra urls to check

---

infrastructure/batch/launch_templates.tf

Increase launch templates /dev/xvda volume size. 
Avoid docker no space left on device error.

Increase launch templates /dev/xvda volume size

---

.github/workflows/config.yml
scripts/common.sh

The deploy box Docker builder is a SPOF and doesn't handle its workload well. 
This PR aims to:
- Remove remote docker builder for Github tests.
- Move Foreman tests to larger runners.

Use CI/CD local Docker builders

---

config/supported_microarray_platforms.csv

N/A. The following error came up in processing on staging:
> Unhandled exception caught while running processor function _run_scan_upc in pipeline: 'clariomsmouseht'
Which drew my attention to the `supported_microarray_platforms.csv` file.
Here, I'm updating the internal accession column for [`GPL24242`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL24242) `clariomsmouse` -> `clariomsmouseht`, which is an error.
I'm not sure if this will fix the failure we saw in staging.
N/A

Update supported_microarray_platforms.csv to fix GPL24242 internal accession field

---

infrastructure/deregister_batch_job_definitions.py

It looks like the production deploy process failed because of AWS API rate limit. 
```
File "deregister_batch_job_definitions.py", line 28, in <module>
response = batch.describe_job_definitions(**data)
File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (TooManyRequestsException) when calling the DescribeJobDefinitions operation (reached max retries: 4): Too Many Requests
```
In order to slow down our request rate we are going to add some sleeps to the …

Slow down batch job deregistering process

---

scripts/common.sh

#3380 
Extend using of staging images cache.
It's mostly done to speed up the prod (different docker registry) build process.

Extend using of staging images cache

---

foreman/data_refinery_foreman/foreman/management/commands/track_data_request.py
foreman/tests/foreman/management/commands/test_track_data_request.py

#3361 
Add a command that gathers/shows stats based on a accession code list. 
The areas of interest include attempted/available experiments (total and broken down by source) as well as attempted/available samples (total and broken down by source).
The total number of jobs created includes all job types.

Implement data request tracking

---

.github/workflows/config.yml

Move smasher test jobs to larger runners. The culprit is pretty much the same -- insufficient disk space.

Move smasher test jobs to larger runners

---

infrastructure/networking.tf

Replace deprecated syntax with a new one (the actual change is about `domain = "vpc"`)

Update deprecated AWS elastic IP address configuration

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh

Clean up existing API server containers before running a new one.

Explicitly remove existing API containers

---

workers/dockerfiles/Dockerfile.downloaders

Set proper gnupg path.
// The downloaders tests pass, no-op job is failing with `We found an Illumina file to NO_OP that we're not set up to process yet` though.

Update downloaders image

---

.github/workflows/config.yml

Make downloaders and no_op test separate jobs to indicate better what's exactly broken when a job is failing.

Split downloaders/no_op test jobs

---

infrastructure/deploy.sh

Resolves #3437 
Add an explicit API server availability check by a SSH session establishing attempt. Exit if the API server is unavailable via SSH.

Add API server SSH connection check

---

infrastructure/deploy.sh

Removing 30d+ old Docker images on every deploy would make sure we have enough disk space for the next one while keeping relatively fresh images in place. 
This will address
`#18 ERROR: write /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/4383/fs/usr/local/lib/R/site-library/pd.genomewidesnp.5/extdata/pd.genomewidesnp.5.sqlite: no space left on device` 
type of issues.

Add deploy box cleanup instructions

---

.github/workflows/config.yml
workers/dockerfiles/Dockerfile.no_op

Resolves #3436 
Fix no-op tests
- Use wget instead of curl for gene index downloads
- Set specific unzip/rm file instructions
- Set pre-commit to use Python 3.11

Fix no-op tests

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
infrastructure/deploy.sh

Add restart flag to API docker container to ensure it's running after failures/reboots.

Add restart flag to API docker container

---

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
infrastructure/api-configuration/nginx_config.conf

#3452 
Pretty straight forward change that does 2 things.
- Moves nginx logs from `/tmp/[access / error].log` to  `/var/log/nginx/[access / error].log`
- Moves where we serve static files from `tmp/volumes_static` to `/var/www/volumes_static` 
n/a 
n/a
n/a

3452 move nginx logs and static files to /var

---

infrastructure/deploy.sh

#3452
This PR is related to #3453 and adds the same mapping from the API's user data script for static files. This should allow us to generate the static files / documentation on deploy when the API is not tainted.
N/A
n/a
n/a

Map static dir on API to /var/www/volumes_static on deploy

---

infrastructure/deploy.sh

#3452 
This PR adds the same creation and permission settings to the static dir when the API container is restart. We have already moved the static dir out of `tmp`. This change could safely be removed in the future.
Thoughts for the future: We probably should consider pulling out the starting of the container to it's own script so that we can just call that remotely on the API instead of duplicating the setup in user data and deploy scripts. That change is more involved than what we need at this moment. If we encounter issues with the API standing up or docs not being available again I strongly recommend addressing that then.
n/a
n/a
n/a

3452 Ensure /var/www/volumes_static exists on container restart

---

infrastructure/batch/launch_templates.tf

n/a
While processing a batch of requested experiments we encountered a high failure rate due to a lack of available storage attached to the batch instance. This PR doubles the available working space.
n/a
n/a
n/a

scale up worker volume
